### ISSUE TITLE
[Survey] Do you use these 2 components ?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#103]
**This is not a issue, it's survey. Please answer if you use it.**

I have disabled this 2 components when I first started using CIDRAM. But I have a feeling some of the scrapers are slipping through because of it. I am now considering enabling them but the **medium risk** is actually stopping me.

Do you use this 2 components?

![chrome_2019-04-09_11-56-41](https://user-images.githubusercontent.com/18257605/55777771-90bb7080-5abe-11e9-8b93-d4e6dcc365b9.png)

If yes, please click on 👍.
If no, please click on 👎.

**Comment by DanielRuf** [comment]
If yes, please 👍 on the initial comment.
If no, please 👎 on the initial comment.

**Comment by harryqt** [comment]
@DanielRuf Sorry there was actually 2 question at the end so I'm a little confused. I edited the post now.
So, just to clarify you don't use this 2 components, right?

**Comment by mikeruss1** [comment]
yes I use them

**Comment by DanielRuf** [comment]
> So, just to clarify you don't use this 2 components, right?

Right, I don't use them.

**Comment by DanielRuf** [comment]
> yes I use them

@mikeruss1 Please add the upvote reaction to the first comment. We can filter by this in the issues list and it keeps the list of "I use it too / not" short.

> If yes, please 👍 on the initial comment.
> If no, please 👎 on the initial comment.

**Comment by DanielRuf** [comment]
> If yes, please 👍 on the initial comment.
> If no, please 👎 on the initial comment.

**Comment by Maikuolan** [comment]
I run multiple installations, across multiple websites. On some, I use them. On some, I don't. So, in my case.. a little bit both ways, depending on the needs of the website, installation context, etc.

**Comment by ghost** [comment]
I'm using both so :+1:  :+1: 
And to answer the original second question: I don't care. :cake: 
@ :de: :cactus:  It could be a nice idea to tell people where/how to react. :innocent:

**Comment by 737simpilot** [comment]
I use both. Then again, I also block a ton of countries I really have no use for and don't intend on having traffic from those countries so the scrapper issue is more minimized. Not only that, but I use CloudFlare and have loads of ASNs and what not blocked there and/or presents a captcha. Then on top of that CloudFlare does their own filtering on bad requests.  False positives? Forgetabouit. LOL  But it does indeed matter what type of site you have and all that.
