### ISSUE TITLE
Strange Block in Log

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#104]
Hello.

I see several of these:

Script Version: CIDRAM v1.12.0 »
Date/Time: Sat, 20 Apr 2019 04:34:20 +0300 »
IP Address: 173.248.191.183 »
Referrer: xxxxxxxxxxxxxxxxxxxxxxxx
Signatures Count: 1 »
Signatures Reference: 173.248.128.0/18 »
Why Blocked: Cloud service ("Handy Networks", L10257:F0, [US])! »
User Agent: WordPress/4.9.10; xxxxxxxxxxxxxxxxxx
Reconstructed URI: xxxxxxxxxxxxxxxxxxxxxxxxxx »

The IP belogs to our CRON ip (server) and i have whitelisted it. But it shows and IS blocked not to mention in a wrong Signature Reference.

I'm not using the plugin version. Just auto prepend.

Am i missing something ?

Thanks

**Comment by Maikuolan** [comment]
> not to mention in a wrong Signature Reference.

The IP address `173.248.191.183` belongs to the CIDR `173.248.128.0/18`, which is part of the signature, which currently exists in the IPv4 signatures file, and which is responsible for the block event occurring, so, the signature reference is correct. :-)

The block event definitely should not be occurring if the IP address has been whitelisted though.

Is the signature file that contains the whitelist signature currently listed in the IPv4 signature files list in the configuration (`config.ini->signatures->ipv4`)? If a signature file isn't "active" (i.e., not listed in the relevant signature files list), that could cause what we're seeing here (i.e., specific signatures, e.g. for whitelisting, to not work properly).

Also (or alternatively), if there's any chance that the IP address used for cron might change over time (e.g., if the hosting provider uses multiple different servers for handling cron jobs), it might be easier to just list the offending signature section in the `ignore.dat` file, effectively greylisting the entire hosting provider (that way, if the cron IP address changes in the future, you won't need to write new whitelist signatures to whitelist the new IP addresses being used by cron).

**Comment by 737simpilot** [comment]
Did you add the IP to the ipv4_custom.dat file and does it look like this?

173.248.191.183/32 Whitelist

Not sure if that should be a /32 or /18.

**Comment by Maikuolan** [comment]
> Not sure if that should be a /32 or /18.

`/32` to whitelist the specific IP address (`173.248.191.183`), or `/18` to whitelist the entire affected CIDR (`173.248.128.0/18`). So, either of these two things, should work:

```
173.248.191.183/32 Whitelist
173.248.128.0/18 Whitelist
```

But this, will *not* work:

```
173.248.191.183/18 Whitelist
```

**Comment by eurobank** [comment]
Ok, what i have in my ipv4_custom.dat is:

```
# Below is our CRON
173.248.128.0/18 Whitelist
```

Everything else is working just fine. And no the IP of my server Cpanel doesn't change. I will check the "ignore" option you suggested and update.

**Comment by eurobank** [comment]
Ok, what i think it happened is that our Wordpress cache preload was working (via Crons) and also during that time i made 3 changes in the ip4 custom or other files via FTP.

That resulted 3 blocks logged in the log files. 

Because i re-did the preload of cache a while ago, it finished and no blocks found.

I will keep an eye open for 1-2 days and then i will close this.

Many thanks

**Comment by Maikuolan** [comment]
I've seen some other strange, unexpected behaviour before when CIDRAM and various website caching systems have come into contact with each other in the past, so, not too surprising, and makes sense, as a likely culprit for the behaviour encountered in this case too. :+1:

> I will keep an eye open for 1-2 days and then i will close this.
>
> Many thanks

Sounds good, and you're welcome. :-)
