### ISSUE TITLE
Pagination (Fancy)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#105]
Hello.

We are using monthly logs, mainly for statistic reasons. The thing is that we are getting a huge ammount of logs and they seem to display in one page (fancy is what lik use).

Is there any way to have them paginated, in the future maybe ?

Thanks

**Comment by Maikuolan** [comment]
Good idea.. definitely worth looking into. :-)

There are a few things I'm working on at the moment (e.g., completing the "signature file fixer" feature on the front-end; related to issue #101), but I hope to finish those things within the next few days or so. After that, I could experiment a little with pagination and try to come up with something, I think.

**Comment by eurobank** [comment]
An interim (and easy) solution for people with huge log files, could be just a "press a key for the next bunch" every 100 (for example) logs.

**Comment by eurobank** [comment]
My above idea is not so good, because you will not be able to go directly to the last records (the newest blocks).

**Comment by DanielRuf** [comment]
For this we just calculate something like `ceil(log_lines / show_lines)` if there are log_lines > 0. And add this as pagination or dropdown.

**Comment by eurobank** [comment]
@DanielRuf also not practical if you use a monthly log. Right now i have a log of 10.000+ entries (central for all 5 sites in the server). And is has been only a week or so i'm using CIDRAM.

**Comment by DanielRuf** [comment]
> @DanielRuf also not practical if you use a monthly log. Right now i have a log of 10.000+ entries (central for all 5 sites in the server). And is has been only a week or so i'm using CIDRAM.

Normally log rotation should be daily.

**Comment by eurobank** [comment]
If i rotate daily, how can i have monthly stats ? Is there a way ?

**Comment by Maikuolan** [comment]
> If i rotate daily, how can i have monthly stats ? Is there a way ?

I'm not sure that this is possible currently. I might need to rethink the logic behind CIDRAM's log rotation system a little, maybe.

I'll reply again soon.

**Comment by Maikuolan** [comment]
Logs pagination has now been implemented. :-)
