### ISSUE TITLE
[SUGGESTION] Updates Do not default to Deactivate

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#108]
In updates it would be better **not** to default to Deactivate (when all is updated). Because it is very easy to select OK and Deactivate the modules. If you do that fast and not very careful. Just did it myself.

You would be better to default to something like "Select an Option".

Thank you !

**Comment by Maikuolan** [comment]
Good point. :-)

I should be able to do this easily, I think.

**Comment by Maikuolan** [comment]
*Implemented via ad1bb8cd56c75b1c674fd26938a25b30f180d3c6 and 88f106763e387a61ec5e2faeed9d719869031f77. Marking as implemented and closing.*
