### ISSUE TITLE
Move docs to their own repository.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#109]
I propose moving the documentation, currently stored in `CIDRAM/CIDRAM/_docs`, out from `CIDRAM/CIDRAM`, and into its own repository, `CIDRAM/Docs` (or similar), and invite everyone to vote on this. The reason I propose this, is that I feel that separating the documentation from the main repository will make the documentation easier to manage and maintain (especially seeing as I intend to maintain separate branches for future v1 and v2 releases herein, and I don't particularly want to maintain separate branches of documentation, which then begs the question, whether to favour a particular branch, or.. to just move it out to its own repository entirely, per this proposal). The reason I put it forward as a vote, is that there are numerous external links on numerous websites that point to the documentation, and changing the location of the documentation would invalidate those links, thereby potentially affecting some users (and there could be reasons to vote against this proposal that I haven't thought of yet). You can signify your vote by reacting to this issue, :+1: to vote yes, and :-1: to vote no. As this vote is informal, there won't be a specific deadline nor schedule for it (we can consider the vote closed, whenever we decide there are enough votes, or whenever a decision has been made). Comments and/or alternative suggestions also invited. Thank you. :-)

**Comment by Maikuolan** [comment]
PS, I should mention: Either way, regardless of whether the docs are moved or stay where they are, it won't break workflow, and won't prevent the package from moving forward. So, voting one way, because the other seems like it might prevent future releases, isn't necessary (neither way will prevent future releases). However, whether the docs move or stay where they are, will *affect* workflow slightly, obviously and foremost in the sense of where future commits to the documentation must go, but also in the sense of whether I need to account for documentation when deciding which pull requests to the main package repository here to accept or decline, which branches future commits should go to for any particular changes to any particular version and so on (which is the other reason that I felt I should ask about this).

**Comment by ghost** [comment]
As it is not uncommon that documentation is released as a separate package, and this kind of separation would in much give the documentation a kind of perma-link (its own repository - which would ease external linking a lot), and as it from a developer perspective would be easier to maintain it as a separate project I'm positive to it even though it might look from a user perspective as less optimal as you suddenly need to look in two different repositories (one for code and one for documentation).  But then we have to assume that our users have a bit more than a basic understanding of technology due to how CIDRAM is installed and hooked up to a site, so they should be able to find the needed documentation easily enough, even on a separate link, I think.

**Comment by DanielRuf** [comment]
With Git submodules you can directly link / include them.

**Comment by ghost** [comment]
Sounds like a plan then :)

**Comment by 737simpilot** [comment]
I don't see a problem with it. Thumbs up from me.

**Comment by harryqt** [comment]
Green light from me too. 👌

**Comment by Maikuolan** [comment]
(Had intended to reply to this issue again tonight, but it's getting super late, and I need some sleep. Will reply here again in the morning or at some point during the day tomorrow).

**Comment by Maikuolan** [comment]
Thanks for all your votes and feedback; I appreciate it. :-)

Current vote tally at the time of this reply is 7 for, 1 against (if I include feedback I've received elsewhere and via private channels, it would be brought up to 8 for, 2 against), which is good enough for me. I'll get started on the move shortly. :+1:

Something that one of the against mentioned to me though (via a different channel), is that they (and possibly other users) are familiar with the documentation already existing inside the package, at least with current versions, and that retaining at least the original English version of the documentation would be good, due to it historically being a part of the package (and for users accustomed to just downloading the zip, to prevent confusion if they don't find a copy in the zip file anymore). So, to keep those particular users happy, I'm thinking I'll retain just an unmaintained copy of the English version of the documentation in the v1 branch (ditching all the others), and add a notice to it (that it isn't maintained anymore), directing users instead to the maintained version, in the newly created `CIDRAM/Docs` repository. The v2 branch won't retain any versions of the documentation, and all future changes to the documentation (e.g., pull requests) can be directed to the newly created `CIDRAM/Docs` repository.

> With Git submodules you can directly link / include them.

I'm a little wary of submodules. I created a temporary test repository a few days ago to test out submodules, and.. although submodules seem to work as advertised, it seems that any files/data belonging to a submodule are ignored by GitHub when generating downloadable zips/tarballs for the parent repository (meaning that, if someone was to download a zip/tarball copy of CIDRAM, or anything else that uses submodules, the downloaded zip/tarball wouldn't contain anything connected to said submodules), which.. could be a problem. So, unless GitHub can do something about that, I'm not sure that linking the documentation to the repository via submodule would provide much benefit above simply keeping it in a separate repository entirely and just pointing users in that direction whenever the documentation is needed. To a lesser extent, the additional steps required by contributors to be able to contribute to a repository that uses submodules (e.g., `git submodule init` to fetch submodule files/data), and the risk of accidental reversion of submodule references due to hidden commit statuses and such (for those not familiar with submodules) could potentially become a problem. A good idea, and I can see the benefit of submodules in some cases, but better to not worry about it at the moment, I think.

**Comment by Maikuolan** [comment]
Removed from `CIDRAM/CIDRAM/v1` via https://github.com/CIDRAM/CIDRAM/commit/4fc900d0390d4f415afece5c5d018046b130a717.
Removed from `CIDRAM/CIDRAM/v2` via https://github.com/CIDRAM/CIDRAM/commit/e3fd3a86237ac1f50f4237a290d4946e9fdaa9db.
Added to `CIDRAM/Docs` via https://github.com/CIDRAM/Docs/commit/7d1f1811a26641954d0f7213e87d52ed2b420c7e.

(Leaving `CIDRAM/CIDRAM/master` alone for the moment. Want minimal changes there until the transition to v2 is complete, due to possible merges needed between v1 and v2, and then can dump it later anyway).
