### ISSUE TITLE
Fatal error when activating blocklist

### ISSUE THREAD

**Issue by frank4360** [CIDRAM/CIDRAM#113]
Fatal error: Uncaught TypeError: Argument 2 passed to {closure}() must be of the type array, string given, called in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php on line 1974 and defined in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php:723 Stack trace: #0 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php(1974): {closure}('ipv4', 'BD_cidram.inc') #1 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php(1578): {closure}('BD_cidram.inc') #2 /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend.php(1500): {closure}('activate-compon...', 'BD_cidram.inc') #3 /homepages/*****Med-and-Mountain/CIDRAM/loader.php(102): require('/homepages/46/d...') #4 {main} thrown in /homepages/*****Med-and-Mountain/CIDRAM/vault/frontend_functions.php on line 723

**Trying to activate blocklist for Bangladesh IPv4.
Same for other blocklist, eg ChinaIPv4

Installs worked without a problem, but all Activates fail.**

**Comment by DanielRuf** [comment]
See https://raw.githubusercontent.com/macmathan/Blocklists/master/cidramblocklists.dat

https://github.com/macmathan/Blocklists

**Comment by ghost** [comment]
@DanielRuf Maybe better to link to the repo rather than the actual data file next time? 

I am able to reproduce the exact same error on an install updated to current time of updates.
Definitively a mismatch in the frontend_functions.php that we need @Maikuolan to have a look at.

**Comment by DanielRuf** [comment]
> @DanielRuf Maybe better to link to the repo rather than the actual data file next time?

I have added a link to the repo. Basically we can see the repo URL in the raw URL ;-)

**Comment by ghost** [comment]
Not everyone likes to read raw data, user friendliness you know? 

AFAIK not an issue with my lists, the issue lies in the frontend_functions.php file and concerns only activation and deactivation of files from the update page from what I can see. Installing the file, then adding it manually in the config works without errors (_and is an usable workaround for the time being_).

**Comment by ghost** [comment]
> I have added a link to the repo. Basically we can see the repo URL in the raw URL ;-)

https://bitbucket.org/macmathan/blocklists is the official main repository (and place for support) for my lists btw.

**Comment by Maikuolan** [comment]
Had some guests over and didn't see the notification about this until just now. '^.^

Investigating this now.

**Comment by Maikuolan** [comment]
Found the problem. Basically the same problem as #112; just a different part of the codebase. Working on a fix now.

**Comment by DanielRuf** [comment]
@macmathan

Well that's why I wrote

> Not related to docs but the frontend_functions.php file.

**Comment by DanielRuf** [comment]
We should add some unit tests to prevent this in the future.
How should such a test look like?

**Comment by Maikuolan** [comment]
Fix has been committed and pushed. :-)

**Comment by Maikuolan** [comment]
> We should add some unit tests to prevent this in the future.
> How should such a test look like?

Because the problem was wrong type hints used, that's what we would need to test for, I guess. I'm not sure exactly whether that would be simple to do, but in theory, checking that the parameters supplied wherever closures are called actually matches the specified type hint (wherever specified) would probably be the unit test way to prevent the problem happening in the future. (But, even as I write this, I can't help but think that it sounds like a PITA to implement a unit test like this :P).

Anyway.. nearly 4AM where I am. I'm going to bed. I'll come back to this again during daylight hours.

**Comment by DanielRuf** [comment]
This is not needed in most cases, just catch the error - there are methods for this in phpunit. https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions.examples.ExceptionTest.php

Also simple asserts and error_handler checks should work. Don't overcomplicate it. If there would be an exception a test would fail per default in phpunit - the test only has to activate the rules and run the same methods.

**Comment by DanielRuf** [comment]
I will try to provide some tests if I finally find some time. But please start always small and simple and run the methods as excepted - a fatal error would produce an F in the phpunit reporter.

Codeception might be also interesting for testing the frontend using ChromeDriver / headless Chrome (BDD, acceptance tests) and it can also create unit tests using phpunit + API tests and more.

Oh, please go to bed and get some sleep. No hurry / rush. Still being awake at 4am is not good ;-)

**Comment by Maikuolan** [comment]
(Fast forward, next day, properly rested..) Sounds good. Will investigate those hopefully during the week.
