### ISSUE TITLE
Block page audio no longer works

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#115]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.

N/A

### CIDRAM version used (if known, please also include the exact commit hash).
Latest as of 5-20-19 midnight U.S. Mountain time. version 1.12.0

### Signatures version (if known).

N/A

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
litespeed

### PHP version installed (`<?php echo phpversion(); ?>`).
7.2.17

### Operating system used (`<?php echo php_uname(); ?>`).
Linux

---
## Issue
I had you create a module to play audio on a block page to those that had JS on. It now no longer works and I don't know when this behavior started.  

### Expected behavior
Play audio to a JS enabled browser on the block page.

### Actual behavior
Nothing.

### Last known working version without this issue.
Don't know.
---
## Debug information

What's that?

**Comment by Maikuolan** [comment]
Got the old code still available, per chance? I remember writing it, but it was a fair while back, back when I was using my previous laptop for coding, which is currently packed away in a box. Don't have a copy of the old code on my current, slightly newer machine. Just asking in case it's handy, to be lazy; If it isn't handy, I can pull out the old machine in the morning to access it and figure out what's going on, what needs changing and such. :-)

**Comment by 737simpilot** [comment]
Contents of audio.php

`<?php $CIDRAM['FieldTemplates']['Output'][] = '<div id="bgaud" style="display:none;"></div> <script language="Javascript"> var aud=document.createElement(\'audio\'),x= "https://cyberpcforum.com/images/magicword_old.mp3" ,z=\'audio/mp3\',a=\'<audio autoplay id="bgsound"><source src="\'+x+\'" type="\'+z+\'"></audio>\',b=\'<object><param name="autostart" value="true"><param name="src" value="\'+x+\'"><param name="autoplay" value="true"><param name="controller" value="false"><embed src="\'+x+\'" controller="false" autoplay="true" autostart="true" type="\'+z+\'" /></object>\',au={audio:aud.play?a:b};document.getElementById(\'bgaud\').innerHTML=au.audio; </script>';`

Seems like I got it working. It was CloudFlare's hotlink protection. For a while there even after turning it off it wasn't working and I thought it was something in the htaccess file. But it appears it took a while for CloudFlare to omit hotlink protection. 

Have a listen to the audio. LOL!

**Comment by 737simpilot** [comment]
Crap, just closed this. 

I remember in ZBblock when I had this the audio  link was encoded in base64?

**Comment by Maikuolan** [comment]
> Seems like I got it working. It was CloudFlare's hotlink protection. For a while there even after turning it off it wasn't working and I thought it was something in the htaccess file. But it appears it took a while for CloudFlare to omit hotlink protection.

No worries at all; Good to hear you've got it working, haha.

> I remember in ZBblock when I had this the audio link was encoded in base64?

Yeah, I think I remember about that. I feel like we might've decided to get rid of the base64 encoding to make it easier to change the URL of the audio file when needed, in case you ever changed domains, wanted to change the address of the audio file to something else or whatever else, but I might be remembering wrong. Not sure.. Was a while back '^.^

The URL can be pretty easily obfuscated again if needed though.

**Comment by 737simpilot** [comment]
Ah! I think you're right. It was due to the ability to easily change the URL

I have an addon in my browser to encode in base64. But do you use a website or something? 

Would this be correct? `aHR0cHM6Ly9jeWJlcnBjZm9ydW0uY29tL2ltYWdlcy9tYWdpY3dvcmRfb2xkLm1wMw==`

**Comment by 737simpilot** [comment]
Just came up with a great idea to keep hotlink protection and also have the banned audio. I changed the mp3 link to my Amazon S3 storage. Should have done that a long time ago.

**Comment by Maikuolan** [comment]
> Would this be correct?

Yep.

> Just came up with a great idea to keep hotlink protection and also have the banned audio. I changed the mp3 link to my Amazon S3 storage.

That works. :-)
