### ISSUE TITLE
Todo: add security policy

### ISSUE THREAD

**Issue by DanielRuf** [CIDRAM/CIDRAM#116]
**Is your feature request related to a problem? Please describe.**
We should create a SECURITY.md file which is supported now as policy to inform users how and for how long we support CIDRAM with security patches and how they can contact us about security related issues.

**Describe the solution you'd like**
A SECURITY.md file with our policy for users of CIDRAM.

**Describe alternatives you've considered**
Alternatively we can also add this to the docs and link to it.

**Additional context**
https://github.com/CIDRAM/CIDRAM/security/policy

**Comment by Maikuolan** [comment]
*Marking as implemented (85c3be4cfd65b91409582b0ae21fcfad94a49665 + bd7531668b585a8a4c4c2be16a3aebf905d89efe). Keeping the issue open until the next tagged release to invite further discussion if needed, suggestions for possible improvements, etc.*

**Comment by Maikuolan** [comment]
*New version tagged/released. Closing.*
