### ISSUE TITLE
"Illegal use of $_SERVER."  in loader.php

### ISSUE THREAD

**Issue by frank4360** [CIDRAM/CIDRAM#117]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.

  | Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Running on ionos.fr (ex 1and1.fr) server
-- | --

### CIDRAM version used (if known, please also include the exact commit hash).
CIDRAM-CIDRAM-v1.12.0-23-g5552ade.zip

### Signatures version (if known).
All latest

### PHP SAPI used (`<?php echo php_sapi_name(); ?>`).
CGI/FastCGI 

### PHP version installed (`<?php echo phpversion(); ?>`).
PHP Version 7.2.18

### Operating system used (`<?php echo php_uname(); ?>`).
Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux 
Build Date | May  6 2019 10:44:34

---
## Issue
I am trying to install CIDRAM on a phpBB forum - I already have it running on a Drupal 7 system on the same server. I have added the hook into the index.php file for phpBB 
`include($phpbb_root_path . 'CIDRAM/loader.' . $phpEx);

On accessing the phpBB board I get the error message:-`

General Error
Illegal use of $_SERVER. You must use the request class to access input data. Found in /homepages/**/******/*****/forum/CIDRAM/loader.php on line 46. 
This error message was generated by deactivated_super_global.

### Last known working version without this issue.
The same version of CIDRAM and loader.php are running on the same server on a Drupal 7 site.
---

**Comment by Maikuolan** [comment]
After some cursory googling and reading, I've found that it seems that phpBB, as of 3.2.x, doesn't like it anymore when scripts, modules, etc call globals directly, and wants everything to go through phpBB's own, internal class for dealing with globals instead.

Assuming we don't find a way around this, it could definitely be a problem for us, seeing as CIDRAM is designed to be a general solution to work across all different CMS, forum systems, frameworks, etc, and can't therefore lock itself to particular specific system in the way that phpBB 3.2.x seems to want.

*References:*
- https://www.phpbb.com/community/viewtopic.php?f=556&t=2418236
- https://www.reddit.com/r/PHPhelp/comments/5w1wyn/illegal_use_of_post_referencing_request_input/

Any chance you'd be able to try prepending CIDRAM before anything to do with phpBB executes? If CIDRAM can do its thing before phpBB loads, it's possible we mightn't need to worry about phpBB's policies on globals at all (but I haven't tested this out with the latest versions of phpBB 3.2.x yet myself).

**Comment by delle54** [comment]
Why don't you use the "common.php"?
"<?php require($phpbb_root_path . 'cidram/loader.php');"

**Comment by frank4360** [comment]
I have got round the problem by using a local php.ini file with the "prepend" directive.
