### ISSUE TITLE
QUESTION - Is it possible to whitelist IP addresses?

### ISSUE THREAD

**Issue by frank4360** [CIDRAM/CIDRAM#118]
I have a number of authorised users who have IP addresses which are on blocklists (because they are using a cloud service or a questionable ISP).
I have edited the signature file to allow these users, but when I update the signature list I will have to remember to edit the file(s) again.

There is a reference to a whitelist file being available after reCaptcha success - is it possible to add IP addresses to a whitelist file to avoid editing signature files?

**Comment by Maikuolan** [comment]
Yep. :-)

You can also permanently whitelist IP addresses, without needing to re-edit updated signature files, in several ways.

If you create a custom signature file (or modify one of the two custom signature files included by default), you can include "whitelist" signatures, to permanently whitelist the IP addresses in question. The front-end updates page will never modify the custom signature files, so those are safe against needing to re-edit down the track (assuming no accidental deletions and such, of course).

*Reference information: https://github.com/CIDRAM/Docs/blob/master/readme.en.md#70-basics-for-signature-files*

As an example (obviously not real IPs, but enough to give a general idea about it):
```
1.2.3.4/32 Whitelist
2.3.4.5/32 Whitelist
1:2:3:4::0/128 Whitelist
```

You'll also need to make sure that the custom signature files used are "active", of course. You can do this by listing them in the "ipv4" or "ipv6" configuration directives (according to whichever type of IP addresses are being whitelisted).

Whitelisting will ensure that the IP addresses should never be blocked. If you only want to ensure that they'll never be blocked by signature files, but that they can still potentially be blocked by modules (e.g., maybe a particular user is legit, but not entirely trusted), greylisting is an alternative to whitelisting that can provide that (a greylisted IP address will have any already enforced blocks revoked for the request, but will still be blocked if a later, subsequent signature from a later processed signature file or module triggers).

Alternatively, the "auxiliary rules" feature also allows IP addresses to be whitelisted (or greylisted, too). That can be accessed from the front-end. :-)

**Comment by Maikuolan** [comment]
*Marking as resolved.*
