### ISSUE TITLE
To-do: Upgrading to v3 from previous major versions.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#121]
*To-do: v1->v2 migration guide.*

**Comment by harryqt** [comment]
A description regarding what's the advantages/disadvantages and difference between v1 and v2 would be also nice.

**Comment by Maikuolan** [comment]
Definitely; I agree. :-)

I'll include that information in the guide too.

**Comment by Maikuolan** [comment]
*As upgrading from v1 to v2 is somewhat irrelevant now in the face of v3, but an upgrade guide for v3 is still needed regardless, I've renamed this issue accordingly.*

**Comment by Maikuolan** [comment]
Done.
