### ISSUE TITLE
PHP Warning preg_match(): Delimiter must not be alphanumeric or backslash errors.

### ISSUE THREAD

**Issue by Gaffnet** [CIDRAM/CIDRAM#124]
CIDRAM generates numerous PHP `preg_match()` warnings in the php error log on every call via my Wordpress v5.2.1 blog.

I've tried running CIDRAM's signature file fixer on every signature file in use, removing my custom signature files and using only the default signature files and disabling all Wordpress plugins with no result.

I'm on a shared hosting plan so I'm limited in what I can modify with regards to server configuration.

I'm not an IT guy.  Please be gentle. ;-)  Any help is appreciated. Thanks!

<details>
 <summary>PHP Warnings in PHP error log:</summary>
 
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/function
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705
PHP Warning:  preg_match(): No ending delimiter '.' found in /home/mysite/public_html/cidramcf/vault/functions.php on line 1705

</details>

## Server information.

Apache Version 2.4.39

### CIDRAM version used 

v1.13.0

### PHP SAPI used

cgi-fcgi

### PHP version installed

PHP Version 7.2.13
PCRE (Perl Compatible Regular Expressions) Support 	enabled
PCRE Library Version 	8.41 2017-07-05
PCRE JIT Support 	enabled 

### Operating system used

Linux 2.6.32-696.18.7.el6.x86_64 

## Last known working version without this issue.

I can't recall the last version that did not generate this error.

**Comment by Maikuolan** [comment]
Could you share an example of some of the errors? (Any sensitive information like usernames, domain path, etc redacted, of course). Sometimes the errors will include useful information like variable names, line numbers, file names, etc that can help to isolate the exact cause the problem. Cheers. :-)

**Comment by DanielRuf** [comment]
@Maikuolan I guess there is already some information in the issue.

> PHP Warnings in PHP error log:

I think we need some info which has caused this (some rule).

**Comment by Maikuolan** [comment]
> @Maikuolan I guess there is already some information in the issue.

I see it now. Didn't see it when reading the message for the first time. My bad. '^.^

**Comment by DanielRuf** [comment]
No problem =)

**Comment by Maikuolan** [comment]
Yep.. @DanielRuf is correct. :-)

Line 1705 (the line reported by the errors) is part of the code responsible for handling auxiliary rules (specifically, auxiliary rules that use regular expressions as part of the match criteria). So yeah; the source of the problem is one of the auxiliary rules.

**Comment by Gaffnet** [comment]
Thanks for helping me narrow down the problem.  I kept deleting auxiliary rules until the errors stopped being generated.

When I deleted this auxiliary rule, the `preg_match()` errors stopped:

```
Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.
Mail Cron Bypass, MyBlog
	
If the following conditions are met, whitelist the request.
Use direct string comparison to test the conditions.

Hostname = myhost123.webhost.com
Query = abcdef-abcdef-abcdef-abcdef-abcdef
```

Oddly, the only remaining auxiliary rule, which is nearly exactly the same as the rule above except for a different query string in the same format (5 groups of 6 letters separated by hyphens), does not generate any new `preg_match()` errors.  

I've added the above rule back in again and no new `preg_match()` errors have appeared.

I added an actual regex auxiliary rule after the above rules and discovered this issue was likely caused by a regex syntax error on my part.  I had used:

 `microsoft.com|search.msn.com` (Generates error)
vs
`(microsoft\.com|search\.msn\.com)` (No error).

So, it was a PEBKAC.  :-P

**Comment by DanielRuf** [comment]
Hi @Gaffnet,

thanks for letting us know that you could solve the issue that you faced.

@Maikuolan we should probably extend the error_handler and output some more information like rule, filename, line number and so on.

https://www.php.net/manual/en/function.set-error-handler.php

https://stackoverflow.com/questions/1241728/can-i-try-catch-a-warning

**Comment by Maikuolan** [comment]
@DanielRuf Definitely; I agree.

I'll create a new issue for this shortly.

**Comment by Maikuolan** [comment]
*Closing in deference to #125.*
