### ISSUE TITLE
Statistics Empty

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#132]
My statistics is set TRUE but ...

![Screenshot(3)](https://user-images.githubusercontent.com/4467158/60338080-9e8ddd00-99ad-11e9-90e5-b0183db72483.png)

**Comment by DanielRuf** [comment]
So the start day was just a few minutes / seconds ago.

Can you check if there are any logfiles with data / stats and what they contain?

**Comment by eurobank** [comment]
Of cource there are logs, the current (monthly) and two monthly old ones. 

Checking again now, also empty with start date (also) a few seconds ago.

**Comment by eurobank** [comment]
Ok, found it !

For some reason APCU (that i activated today) did that. Turning that to false solve the problem and the stats show right.

Strange since i have APCu enabled (and shows also enabled). But this is minnor, i don;t care about it.

Sorry for the confusion.

**Comment by Maikuolan** [comment]
No problem at all, and glad to hear that it's working properly now. :-)

If you encounter any problems though, let us know.
