### ISSUE TITLE
[Documentation] How to use PDO with CIDRAM

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#142]
Creating this issue to track progress and so that I'll have a convenient location to tag interested parties (due to the discussion at #131, regarding race condition problems with flatfile caching, disappearing cache data, etc).

**Comment by mikeruss1** [comment]
thanks for this, I will certainly give it a try, it needs to have an easy way of reverting back to flat files in the event of problems

FWIW my feelings on flat files are - there is no point in spending effort on improvements that get around limitations in flat files, it will just produce more problems, and increase complexity

**Comment by mikeruss1** [comment]
if its relevant I am on php 7.3.3 - that seems to be the highest version available

**Comment by mikeruss1** [comment]
if this isnt a lot of work, any chance of getting it done?

still getting fairly regular stats wipe outs.

**Comment by DanielRuf** [comment]
> still getting fairly regular stats wipe outs.

Still, a (normal) database like MySQL is not meant for logging such high volume data.

**Comment by DanielRuf** [comment]
As this quickly becomes a big bottleneck.

**Comment by Maikuolan** [comment]
Many things which aren't much work, piled up together, adds up to become a lot of work.

I'll make a start on it soon.

**Comment by mikeruss1** [comment]
> Still, a (normal) database like MySQL is not meant for logging such high volume data.

used extensively on my site, never had a problem and very fast

**Comment by mikeruss1** [comment]
> I'll make a start on it soon.

understood - when you can is good

**Comment by DanielRuf** [comment]
> used extensively on my site, never had a problem and very fast

It makes your server(s) very slow =) But ok if you think it works for you. I would never recommend this. There are special databases for logging and MySQL is not  primarily meant for this.

@Maikuolan why don't we use Monolog as adapter which can store to FS and DB depending on the setting?

https://stackoverflow.com/a/7257296
https://softwareengineering.stackexchange.com/a/313584

**Comment by Maikuolan** [comment]
Can we use Monolog as a cache system? I'd thought Monolog was just for working with logs.

**Comment by DanielRuf** [comment]
Why would you want to abuse Monolog as caching system? For this there are PSR 6, PSR 16 and implementations like the Symfony Cache component:

https://github.com/symfony/cache
https://github.com/php-fig/cache
https://github.com/php-fig/simple-cache

**Comment by DanielRuf** [comment]
My comments where just about database vs filesystem for anything in general.
Monolog for logging, Cache implementation for caching (FS, with adapters).

**Comment by DanielRuf** [comment]
See https://symfony.com/doc/current/components/cache.html and especially https://symfony.com/doc/current/components/cache/cache_pools.html

**Comment by Maikuolan** [comment]
Cool cool, no problem. Was just asking because CIDRAM's cache system supports PDO, but its logging mechanisms don't (so, seeing Monolog mentioned in the context of a discussion about documenting how to use PDO with CIDRAM, I wasn't sure whether I was misunderstanding something or missing something in the discussion here). :-)

**Comment by mikeruss1** [comment]
> > used extensively on my site, never had a problem and very fast
> 
> It makes your server(s) very slow =) But ok if you think it works for you. I would never recommend this. There are special databases for logging and MySQL is not primarily meant for this.
------------
I dont use it for logging, its used for data management and retrieval

**Comment by mikeruss1** [comment]
> Cool cool, no problem. Was just asking because CIDRAM's cache system supports PDO, but its logging mechanisms don't (so, seeing Monolog mentioned in the context of a discussion about documenting how to use PDO with CIDRAM, I wasn't sure whether I was misunderstanding something or missing something in the discussion here). :-)
------------
I am confused too, my focus is stopping stats and IP tracking wipe out

**Comment by Maikuolan** [comment]
Working on this currently. Will probably have it done by tomorrow or thereabouts.

**Comment by Maikuolan** [comment]
Okay.. I haven't finished any of the translations yet, but I've committed a new FAQ entry to the original English version for how to use PDO with CIDRAM. :-)

@mikeruss1 When you've got a spare moment, mind taking a quick look, and letting me know whether it all makes sense, whether it's relatively straightforward, easy to understand, etc, or whether you can see any potential room for improvement, things that should be added and so on? Cheers. :-)

Link: https://github.com/CIDRAM/Docs/blob/master/readme.en.md#HOW_TO_USE_PDO

**Comment by mikeruss1** [comment]
thank you

I think I understand - but its written as a general background info for 
a tech person.

suggest you add a series of instructions like,

* setup a MYSQL DB if not already using one, follow instructions on your 
host to do this
* add a DB named "cidram"
* it will auto create and use a table named "Cache"
* check the config is OK for your host - 
mysql:dbname=cidram;host=localhost;port=3306
* turn on PDO in the CIDRAM cache config
* username /pw - is this the same as the standard MYSQL id/pw in the php 
setup to use a MYSQL DB

and so on

is going back to flat files just turning off the PDO enable

delete the table before reenabling ?

regards .. Mike

**Comment by Maikuolan** [comment]
Cheers for the feedback, and good ideas. :-)

I'll work towards covering all those points over the next few days.

**Comment by 737simpilot** [comment]
Off topic but PDO reminds me of an episode of the X-Files called D.P.O staring Giovanni Ribisi who had to audition twice to get the part. He also started in Saving Private Ryan as the medic attached to the group out looking for private Ryan. 

We now return you back to the issue at hand. :D

**Comment by Maikuolan** [comment]
The main essence of this issue has basically been resolved now, with all translations completed and some basic information added as of the latest commit to the documentation, so I'm going to mark this as resolved and close it. There may be some underlying issues with PDO here which weren't considered earlier, which may require some changes to be made to the actual codebase itself, but that's also technically a separate issue, seeing as this particular issue here was just intended to track progress towards completing its documentation. Holding off adding further details until I can further investigate these possible underlying issues, and may create a new issue to deal with that in the near future.
