### ISSUE TITLE
[Question] Do I manually need to whitelist Cloudflare ips?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#143]
Today while I was going through the cidram I found that `ipv4_custom.dat` contains the following rules:

```
# Cloudflare
103.21.244.0/22 Whitelist
103.22.200.0/22 Whitelist
103.31.4.0/22 Whitelist
104.16.0.0/12 Whitelist
108.162.192.0/18 Whitelist
131.0.72.0/22 Whitelist
141.101.64.0/18 Whitelist
162.158.0.0/15 Whitelist
172.64.0.0/13 Whitelist
173.245.48.0/20 Whitelist
188.114.96.0/20 Whitelist
190.93.240.0/20 Whitelist
197.234.240.0/22 Whitelist
198.41.128.0/17 Whitelist
```
Similarly `ipv6_custom.dat` contains:

```
# Cloudflare
2400:cb00::/32 Whitelist
2405:8100::/32 Whitelist
2405:b500::/32 Whitelist
2606:4700::/32 Whitelist
2803:f800::/32 Whitelist
2c0f:f248::/32 Whitelist
2a06:98c0::/29 Whitelist
```

I must've added them a long time ago which I don't even remember.
My question is do I need them? or cidram already handles them at its core?

**Comment by ghost** [comment]
You do not need to whitelist them normally, definitively not for any human endpoints at least. 

These are the outward facing IP-numbers, and they should not AFAIK connect to any site as they are receiving inbound connections. _Only if you need to allow a site behind the proxy to reach your site, and your site is outside the proxy, it might be necessary._

**Comment by harryqt** [comment]
Understood. Thank you. 👍

**Comment by Maikuolan** [comment]
What macmathan wrote. :-)

It's possible that you might encounter problems though if [ipaddr](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#ipaddr) isn't configured properly (generally, if any CIDRAM users sitting behind Cloudflare ever start seeing Cloudflare IPs turning up in their logs, the first thing that I would recommend for them to do, is double-check that ipaddr has been configured correctly).

**Comment by harryqt** [comment]
It is correctly configured using `HTTP_CF_CONNECTING_IP` 😊

**Comment by Maikuolan** [comment]
Cool cool. :-)
