### ISSUE TITLE
WordPress user enumeration not allowed

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#146]
Using the forum software phpBB I saw a legit block for a user doing a search for a user of 7895. 7895 is a user on my forum, but doing a search query for that user and only that user name gives me this block: 

```
ID: 1568406629-923363-7677477249
Date/Time: Fri, 13 Sep 2019 14:30:29 -0600
IP Address: 
Hostname: 
Query: keywords=&terms=all&author=7895&sc=1&sf=all&sr=posts&sk=t&sd=d&st=0&ch=300&t=0&submit=Search
Referrer: https://cyberpcforum.com/
Signatures Count: 1
Signatures Reference: module_extras.php:L48
Why Blocked: WordPress user enumeration not allowed!
User Agent: 
Reconstructed URI: https://cyberpcforum.com/search.php?keywords=&terms=all&author=7895&sc=1&sf=all&sr=posts&sk=t&sd=d&st=0&ch=300&t=0&submit=Search
```

Using version 2 of CIDRAM.

**Comment by Maikuolan** [comment]
I've added a new bypass to the extras module just now which should resolve this problem, I think. (https://github.com/CIDRAM/CIDRAM-Extras/commit/073f566015ea2d41e62fdd99d593f0ac6312ea2e).

Let me know if the problems persists after updating. :-)

**Comment by DanielRuf** [comment]
There are more than one way to enumerate users in WordPress. Your code probably does not cover the archives, REST and XML-RPC API.

https://medium.com/@ahmed_elhady/wordpress-username-enumeration-techniques-2ca0510df632

**Comment by 737simpilot** [comment]
And it works. Thanks.

**Comment by Maikuolan** [comment]
> And it works. Thanks.

Awesome! :-)

> Your code probably does not cover the archives, REST and XML-RPC API.

Yep. The module just checks the requested URL for `~author=\d+~i` (basically, the first method mentioned by the linked article). The other methods (like brute-forcing the WordPress login with various permutations of possible usernames and then checking the returned error message to determine whether a username is valid, for example) aren't covered by the module.

Though IMO, that particular latter method (brute-forcing the login and checking the returned error message) would be something better dealt with using a dedicated, purpose-built WordPress plugin or similar such thing, and isn't something that CIDRAM should be trying to deal with itself. (The linked article suggests adding code into a theme to deal with the problem. I'm not convinced that modifying themes is necessarily the best approach there, and would suggest that plugins would be a better approach than themes, but that's a different discussion for another day anyway).

**Comment by DanielRuf** [comment]
I also meant `/author/1` or names ;-)

**Comment by DanielRuf** [comment]
> The linked article suggests adding code into a theme to deal with the problem. I'm not convinced that modifying themes is necessarily the best approach there, and would suggest that plugins would be a better approach than themes, but that's a different discussion for another day anyway

functions.php is recommended for customizations which do not need a full blown plugin which is harder to setup ;-)

Both are recommended ways.

**Comment by dev-101** [comment]
Which gets overwritten with every theme update ;)

**Comment by DanielRuf** [comment]
Not if you create a child-theme which is recommended. Never change the original theme or core files.

**Comment by dev-101** [comment]
Which is more work than plugin's header imho :)

**Comment by DanielRuf** [comment]
Not really =) And most themes already ship with a child theme.

Back to the topic, we should refactor this in the future.

**Comment by 737simpilot** [comment]
I opted to add the htaccess code to my WordPress site instead of messing with a theme. Done and taken care of. However, the link you posted mentions a plugin called Unified Login Error Messages and it hasn't been updated in some time.

**Comment by 737simpilot** [comment]
I do have a WordPress firewall plugin installed and use NinjaFirewall so I'm sure one or both handle those.

**Comment by DanielRuf** [comment]
NinjaFirewall already correctly covers this. The link was just about the different ways to get this information about users / authors. Don't pay too much attention on the rest.

Generally I would say this feature in CIDRAM (detecting user enumeration) is feature creep as it is more a WAF feature than a feature of a CIDR / IP filter.

**Comment by DanielRuf** [comment]
NinjaFirewall already correctly covers this. The link was just about the different ways to get this information about users / authors. Don't pay too much attention on the rest.

Generally I would say this feature in CIDRAM (detecting user enumeration) is feature creep / out of the application scope as it is more a WAF feature than a feature of a CIDR / IP filter.

You should not install another firewall plugin. One is enough (NinjaFirewall) and the others have many issues and the code could be better.

**Comment by 737simpilot** [comment]
The Wordpress firewall plugin offers other features that the free NinjaFirewall I use doesn't. This is what I'm using, albeit the free version. https://wordpress.org/plugins/wp-simple-firewall/
