### ISSUE TITLE
v1 tests.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#149]
Something has gone wrong with the v1 tests (..again). They *were* working for a while, and now they're not. (v2 tests are still perfectly fine, BTW). Pretty sure it's just a matter of changing something in the configuration, and is probably something small, but I'm not quite in the headspace for it at the moment, so, if anyone wanted to have a go at it, whether for the sake of being able to replace those failed __X__ marks next to our commits with some nice __✔__ marks, whether for the sake of a reasonably quick and easy pull request for Hacktoberfest or whatever else, I'd happy for them to do so. Otherwise, if nobody wants to have a go at it, no worries, and I should be able to get around to it eventually, but TBH, I don't consider it a particularly high priority at the moment either, so in that case, I hope nobody minds the wait. :-)

**Comment by akshay-achar** [comment]
@Maikuolan : Can you share more details on this . Which one to test. Would be happy to test this. Thanks.

**Comment by Maikuolan** [comment]
@akshayachar2011 Cheers. :-)

The problem is at the v1 branch. Currently, all the actual unit tests between v1 and v2 should be the same anyway, and v2 works fine. Probably, something has just recently changed at Travis again, or with Conception, and it's probably some kind of configuration problem (but, I haven't looked too deeply at it yet, so I don't know).

![Untitled](https://user-images.githubusercontent.com/12571108/67543591-bf302e80-f724-11e9-82f5-02701bac315b.png)

**Comment by DanielRuf** [comment]
https://github.com/CIDRAM/CIDRAM/commit/e559b135a8a75f41b58bab305a8f6fb6eb4f06dd was the first failing commit.

The `Vault` index is not available anymore. See https://travis-ci.org/CIDRAM/CIDRAM/jobs/588854884#L569 and https://travis-ci.org/CIDRAM/CIDRAM/builds/588854882?utm_source=github_status&utm_medium=notification

**Comment by DanielRuf** [comment]
https://github.com/CIDRAM/CIDRAM/commit/e559b135a8a75f41b58bab305a8f6fb6eb4f06dd was the first failing commit.

The `Vault` index is not available at the shown line. See https://travis-ci.org/CIDRAM/CIDRAM/jobs/588854884#L569 and https://travis-ci.org/CIDRAM/CIDRAM/builds/588854882?utm_source=github_status&utm_medium=notification

```
  [PHPUnit\Framework\Exception] Undefined index: Vault  

#1  /home/travis/build/CIDRAM/CIDRAM/vault/functions.php:2249
```

**Comment by DanielRuf** [comment]
`git-bisect` will likely show the same commit.

**Comment by DanielRuf** [comment]
@Maikuolan you should make smaller and easier testable commits. Maybe we should also create some git hooks using https://github.com/CaptainHookPhp/captainhook for example so we can not push code that breaks the tests (without some tricks).

**Comment by DanielRuf** [comment]
https://github.com/CIDRAM/CIDRAM/commit/e559b135a8a75f41b58bab305a8f6fb6eb4f06dd#diff-a280b2eecaa2bd1690b9f424e3fccb93R2249

**Comment by Maikuolan** [comment]
Cheers.. Makes sense. :+1:

As an interim workaround, I could encapsulate the `require` with a simple `isset` check for `Vault`. Easy to do, and shouldn't break anything. Weird that it works on v2 though.. the suspected offending code (the `require` which uses the `Vault` index) exists in both branches, so, I'm still not quite sure what's going on there.

**Comment by Maikuolan** [comment]
CaptainHook looks interesting. I hadn't ever seen or heard of it before.

**Comment by Maikuolan** [comment]
Well, that seems to have "fixed" it (i.e., not failing now).

I feel like I'm still missing something though, with how v2 tests were still working anyway when v1 wasn't working before. But, I guess, as long as it's working again, I can technically mark this as resolved now..? `¯\_(ツ)_/¯`

But yeah.. Adding some hooks could be a good idea, I think.

**Comment by Maikuolan** [comment]
I'll do some more research into improving hooks/tests/etc in the near future. Anyway, I'll close this issue now, seeing as it has basically been resolved.
