### ISSUE TITLE
Compatibility with multiple vHosts/domains

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#15]
_Refer: https://github.com/Maikuolan/CIDRAM/commit/ffc567bb5fc2e8ae27a8c2057e63f9a2f4788a2d#commitcomment-18789234_

Creating issue to track progress regarding compatibility with multiple vHosts/domains.

> Hi, I see a potential problem here. This will be fine for domains/vhosts and separate CIDRAM instances, but in case we use common/centralized single instance in stack or prepend mode, this will work for one domain only whose keys are matched, and all others will fail. We need to add support for multiple vHosts/domains and then check coming requests with HTTP_HOST to retrieve proper key pairs.

**Comment by Maikuolan** [comment]
*Note: This issue is valid, in the sense that a singular CIDRAM installation protecting multiple domains may require different sets of keys in order to be able to use reCAPTCHA for each of the protected domains, if the keys associated with those domains have domain name validation enabled. However, due to that domain name validation can be disabled from within the reCAPTCHA dashboard, it is possible to use a single set of keys for any domain name, if a key owner chooses to allow this. Leaving this note here in order to inform anyone that mightn't yet be aware of this. See: https://developers.google.com/recaptcha/docs/domain_validation*

> ## Domain Name Validation
> A reCAPTCHA key is normally tied to a set of individual domains. However, if your list of valid domains is extremely long, fluid, or unknown, we give you the option to turn off the domain name checking on reCAPTCHA's end, and instead check on your server.
>
> To do so, in the admin console, go to "Advanced Settings" for your key, and untick the "Domain Name Validation" box.
>
> ## Security Warning
> Turning off this protection by itself poses a large security risk - your key could be taken and used by anyone, as there are no restrictions as to the site it's on. For this reason, when verifying a solution, you are required to check the hostname field and reject any solutions that are coming from unexpected sources.

**Comment by Maikuolan** [comment]
So, my current thoughts about this were to implement the ability to optionally include additional configuration files within installations, to allow directives set by the main configuration file to be overridden on the basis of `HTTP_HOST` header.

Say, for example, for a multi-domain installation, directive "X" is defined as "foo" in the main configuration file (`config.ini`), and this is the way that we want it for all domains, except for the special domain `hxxp://www.something-special.tld/`, because this special domain needs "X" to be defined as "bar" in order for it to operate normally and as intended.

In the event of configuration overrides based on the `HTTP_HOST` header, we could write a new configuration file where "X" is specially defined as "bar" instead of "foo", give this configuration file a name like `something-special.tld.config.ini` (and/or maybe `something-special.tld.config.yaml`, depending on whether we'd prefer to stick with INI, use YAML instead for the override configuration files, and/or maybe something else entirely, like NEON, CSV, whatever). Upon each request, during the normal process for loading configuration data, after loading the main `config.ini` configuration file, CIDRAM then checks for the existence of a `HTTP_HOST.config.(ini|yaml|csv|neon|.+)` file, and if it finds it, uses the values contained therein to override whatever was previously set, in a similar manner to how the values of the directives defined by `config.ini` will override the configuration defaults defined by `config.yaml` (meaning also then that these override configuration files could contain either a complete set of configuration values, or a reduced subset of configuration values, depending on whatever was preferred; absence of a defined value for some directive would simply mean that there is nothing to be overridden from whatever was already defined).

Implementing this idea should resolve the issue of requiring different sets of API keys for different domains and/or sub-domains for multi-domain installations, but additionally, would allow further domain-specific customisation for multi-domain installations (such as, for example, if one was wanting to split logfiles into separate files on the basis of `HTTP_HOST`, define different languages for different sub-domains, use different sets of modules and signature files, etc). Another benefit to implementing this would be that unlike many of the alternatives, it would not require any changes to the front-end or UI, and so, wouldn't pose anything new to users that they need to learn how to use, effectively being a "silent" feature; Documented, of course, but not necessary to know about until users wanted to take advantage of it.

Might seem a bit more extreme than simply allowing arrays to be defined within the main configuration file for different domains, but the main problems with allowing arrays to be defined within the main configuration file are:
- INI files can't naturally contain a depth greater than two anyhow, due to the way that the format is structured. In regards to this, allowing arrays in the main configuration file would mean we'd either (1) be forced to switch to a different format (YAML would be the obvious candidate, seeing as this is already being used for the configuration defaults file anyhow, and our implementation of it doesn't enforce any depth limits), which honestly, I don't particularly mind the idea of doing, but doing this would definitely be a backwards-incompatible change, and is a type of backwards-incompatible change I'd rather leave out until some future `v2.0.0` release, at least (and I think it would be an unexpected change for most users if we were to implement it at this time, and might not be received very well), or, (2) be forced to use a (somewhat hacky) approach whereby arrayed data stored in the configuration file at a depth greater than two is flattened as serialized data, or somehow otherwise faked in a way as so to be able to contain the information required without exceeding the depth limit of two enforced by the INI file format. Either way though, the problem could theoretically be resolved quite easily.
- Allowing it may require that some heavy changes be brought about to the front-end configuration page, seeing as the front-end configuration page isn't currently designed in a such way whereby configuration files containing values at varying depths could be supported properly. Also, simply adding previously non-existent directives directly and manually to the main configuration file itself has the risk that they could be lost entirely when updating the configuration via the front-end configuration page, due to that it regenerates and overwrites the entire file when updating.

Would like to know your thoughts about this. @dev-101 @DanielRuf

**Comment by DanielRuf** [comment]
A good idea, like nginx and apache vhost configurations which overwrite settings from the default template.

**Comment by Maikuolan** [comment]
:-)
