### ISSUE TITLE
Yet another module: Project Honeypot

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#151]
I was just thinking, and I don't know why I didn't think of this before. I was using Project Honeypot today to cross check some IPs in my access logs and I use the Project Honeypot API with a WordPress plug-in and so I thought it would be a nice addition to CIDRAM to have a Project Honeypot module. I don't know all of the ramifications with something like this though. I looked over their API usage and what not and from what I understand is that they also have a rating system much like AbuseIPDB. They did mention something about giving back in the form of data. So I imagine this could be achieved like how CIDRAM reports back to AbuseIPDB of bad IP addresses doing things they shouldn't. 

Again, not sure on all of the ramifications, etc, but it sounds like a nice addition. Is it possible?

**Comment by Maikuolan** [comment]
Not entirely sure TBH. I'll do some investigating and reply back here a little later. :-)

**Comment by 737simpilot** [comment]
Okay, thanks.

**Comment by Maikuolan** [comment]
Sorry for the delayed reply. I've been working quite a bit and have been busy with other offline commitments quite a bit over the past week or so.

I've done some basic research into this, and to answer the question: It's absolutely possible and doable. :-)

I haven't started writing any code yet, but I'll most likely make a start on this some time this week or thereabouts, I think.

**Comment by 737simpilot** [comment]
Thanks, Caleb. That sounds great.

**Comment by Maikuolan** [comment]
Found a possible, theoretical Terms of Service issue regarding the way that the Project Honeypot HTTP:BL works (the transparent inclusion of API keys in requests, possible interception, etc). Could be something to worry about; Could be nothing to worry about at all; Not sure. Sent them an email about just a few minutes ago to ask them directly. Delaying further development of this module until I hear back from them (which probably won't take too long I imagine, but like I said, I sent the email only just a few minutes ago). Will reply again when I hear back from them.

**Comment by 737simpilot** [comment]
Not a problem, Caleb. If there is a security factor here then you can just skip it. I run a pretty tight ship on my computers and websites so I wouldn't want an API key exposure, etc. But like I mentioned, in WordPress I have a plugin that uses the API key from Project Honeypot, so not sure how that works.

**Comment by Maikuolan** [comment]
So.. I received a reply from them about my concerns, and it seems there's nothing to worry about (in the context of the concerns I had). Anyway, just replying again briefly to confirm that I'll resume working on this shortly. :-)

**Comment by 737simpilot** [comment]
That's great news. Thanks.

**Comment by mikeruss1** [comment]
seems like a good idea, implemented on my site

to state the obvious, (which I have just realised) the link to the honeypot page also needs to be on the CIDRAM block page

**Comment by 737simpilot** [comment]
Any news on this?

**Comment by Maikuolan** [comment]
Got all the data sitting on my desktop, almost ready to go. Just ended up on the back-burner due to other things coming up with more severe priority, plus various other distractions. Sorry for the delay. I'll continue on this as soon as I've got a moment. Shouldn't take too long to finish off and get it working properly once that moment comes up.

**Comment by Maikuolan** [comment]
Progress delayed due to other priorities. Temporarily removing *Work-In-Progress* label (will continue this a little later).

**Comment by Maikuolan** [comment]
Done ([`31fdba7`](https://github.com/CIDRAM/CIDRAM-Extras/commit/31fdba7619e9db49174dac00081d59b65c23388a)). :-)

I haven't yet coded in the ability to report back yet, but ordinary lookups should work properly now.
