### ISSUE TITLE
Recaptcha error ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#161]
while wondering around the config file I turned on error_log

I got a couple of these today and yesterday

[2019-12-30T10:40:42+00:00] Error at recaptcha.php:L161 (error code 8): "Undefined index: Salt". Eep.. Something went wrong during "reCAPTCHA".
[2019-12-30T10:41:55+00:00] Error at recaptcha.php:L119 (error code 8): "Undefined index: Salt". Eep.. Something went wrong during "reCAPTCHA".

**Comment by Maikuolan** [comment]
Thanks for reporting this. :+1:

Investigating now.

**Comment by mikeruss1** [comment]
in both cases the first entry coincides with a "Passed" in the log

**Comment by mikeruss1** [comment]
just tried it, Recaptcha works but throws the error. I only got one error, so the users must have done it twice

**Comment by Maikuolan** [comment]
Thanks for the added information. :+1:

For the particular blocked requests associated with the particular reCAPTCHA instances where these errors occurred, did the triggered signatures by any chance originate from modules or auxiliary rules (i.e., not from the standard IPv4/IPv6 signature files)? Looking over the parts of the code where the "salt" variable is supposed to be being populated, I think I can see why these errors occurred, and I should be able to come up with an easy fix for it, but knowing where the triggered signatures originated could help to indicate to me whether or not I'm on the right path with it.

**Comment by Maikuolan** [comment]
Just pushed a fix for this; Should be all good now. :-)

**Comment by mikeruss1** [comment]
That's quick.

Thank you.
Cheers Mike

**Comment by mikeruss1** [comment]
in both cases it was ..
Signatures Reference: botbrowsers_cidram.inc:L47 »

fix not visible yet
