### ISSUE TITLE
CIDRAM failing to match or only partially matching blocked IPs

### ISSUE THREAD

**Issue by Gaffnet** [CIDRAM/CIDRAM#169]
## Server information.
Apache Version v2.4.41 (Shared Hosting)

### CIDRAM version used (if known, please also include the exact commit hash).
2.4.0-DEV+20037259

### Signatures version (if known).
Custom signature
IPv4.dat 2020.42.247

### PHP SAPI used
cgi-fcgi

### PHP version installed
7.3.11

### Operating system used
Linux 3.10.0-962.3.2.lve1.5.27.el7.x86_64 #1 SMP Sat Nov 30 02:18:52 EST 2019 x86_64 

---
## Issue

I have signature entries that should block this IP, but CIDRAM isn't matching correctly:
172.241.250.173

This CIDR line is in IPv4.dat:
172.241.248.0/21 Deny Cloud

This CIDR line are in a custom IPv4 signature file.
172.241.240.0/20 Deny Cloud

In addition to the above, I have an Auxiliary Rule that does an ASN lookup for 7203 where these IPs reside.

### Expected behavior
This IP should match and be blocked based on multiple signatures:
172.241.250.173

### Actual behavior
Using the IP Test function, CIDRAM reports that 172.241.250.173 is not blocked at all by any signature files.

### Steps to reproduce the behavior
Entering the above IP, as well as testing random IPs that are within the specified blocked ranges fails to yield any matches.

### Other Notes
Stuff I've tried:
* Checked to make sure these IPs aren't whitelisted anywhere.
* Updated to latest CIDRAM
* Verified all signature files
* Used the Signature File Fixer on all signature files in both "Currently Active" mode and copy/pasted from Direct Input mode.
* Removed all signature files from config.ini, leaving only core versions of ipv4.dat and ipv6.dat for testing purposes.

### Last known working version without this issue.
Unknown.

---
### Relevant logfile entry (if applicable).
I just became aware of this error message after realizing my error_log was not specified for some reason.

Error at functions.php:L1645 (error code 8): "Undefined index: Bypass Flag". Eep.. Something went wrong during "SearchEngineVerification".

**Comment by Maikuolan** [comment]
Investigating now.

**Comment by Maikuolan** [comment]
Latest pushed commits should fix the undefined index error. :-)

Going to get some sleep for the night, but I'll continue looking into this in the morning and will reply with more details then.

**Comment by Maikuolan** [comment]
Having a little difficulty replicating the original problem (failing to match some IPs) at my end; the aforementioned IPs seem to be being blocked properly at my end, at least, at the moment.

Just to confirm: Are there *other* IPs still being blocked properly (i.e., it's just these specific IPs/ranges/etc)? Or is nothing being blocked properly at the moment at all? (An easy way to have something to test against could be by fetching some random ranges from the default signature files, cutting them back to a single IP address, and then testing against those).

**Comment by Gaffnet** [comment]
Found the error: **PEBKAC**

`block_cloud=false` was set.

My modus operandi was to allow all cloud ranges by default, then ban cloud ranges on an individual basis as needed.

I was under the impression that if `block_cloud` was set to false, CIDRAM would allow all IPs from cloud ranges _except_ for those cloud ranges banned by custom signature files. (i.e. custom signature files have the last word.) I didn't know that `block_cloud=false` would have exclusive priority.

172.241.250.173 (and some randomly chosen neighboring IPs/ranges) test correctly with `block_cloud=true`, and is matched by both core and custom signature files.

Looks like everything's fine. Sorry about that!

**Comment by Maikuolan** [comment]
> Found the error: **PEBKAC**
>
> ...
>
> Looks like everything's fine. Sorry about that!

No worries; Happens. ^.^

Glad to hear that everything's sorted out now. :-)
