### ISSUE TITLE
Is supplementary cache still experimental?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#173]
The [docs](https://github.com/CIDRAM/Docs/blob/master/readme.en.md#supplementary_cache_options-category) says:

> Currently, this is extremely experimental, and mightn't behave as expected! For the moment, I recommend ignoring it.

Is it still experimental? I wants to use **Redis cache** to have some performance benefit.
Will it give me performance boost?

**Comment by Maikuolan** [comment]
> Is it still experimental?

Not particularly; I think we should be pretty good by this point. I'd already removed the "experimental" notice displayed for those configuration directives at the front-end configuration page a while back, but forgot to update the documentation for them. '^.^

I'll try to get that sorted out tomorrow. :-)

> I wants to use **Redis cache** to have some performance benefit.
> Will it give me performance boost?

I don't have any specific benchmarks available at the moment to compare the various available caching options, but I believe that using Redis (as opposed to the default flatfile cache) should provide some performance benefit.

**Comment by harryqt** [comment]
Thank you for the update. I will let you know if I run into any issue. :slightly_smiling_face:

**Comment by harryqt** [comment]
Between **APCu** and **Redis** which one would be better (performance wise)?

**Update 1**: Just installed APCu extension; judging by the config all I have to set `enable_apcu` to `true`, right? Or do I have to do anything more than that? (Never used APCu before)

**Update 2**: Never mind. Looks like setting `enable_apcu` to `true` was enough. Working fine. 👍 

![2020-04-04_05-26-17](https://user-images.githubusercontent.com/18257605/78413426-f7715c80-7634-11ea-8ff3-5d9cfe096a5c.png)

**Comment by Maikuolan** [comment]
> I'd already removed the "experimental" notice displayed for those configuration directives at the front-end configuration page a while back, but forgot to update the documentation for them. '^.^

..and now implemented by https://github.com/CIDRAM/Docs/commit/5735355ccf87a09619528e3afa779ceb37e6d817. :-)

**Comment by Maikuolan** [comment]
> **Update 2**: Never mind. Looks like setting `enable_apcu` to `true` was enough. Working fine. 👍 

Awesome! :+1: :-)

> **Update 1**: Just installed APCu extension; judging by the config all I have to set `enable_apcu` to `true`, right? Or do I have to do anything more than that? (Never used APCu before)

(And correct; nothing more required at all).

> Between **APCu** and **Redis** which one would be better (performance wise)?

I would *assume* that **APCu** would be more performant than **Redis** in the context of CIDRAM's cache system, primarily due to **APCu** being a somewhat smaller, simpler, less intensive solution than **Redis**. That said though, I haven't actually compared the two in action directly, and without having done that nor with any benchmarks available, I couldn't quite yet *guarantee* which of the two would be more performant for CIDRAM.

**Comment by Maikuolan** [comment]
Good to have both options available, in case one or the other isn't available at some particular environment or hosting solution somewhere (although obviously, we wouldn't be using more than one at the same time, regardless). Possibly, if both *are* available at some particular environment or hosting solution, the actual usage and existing load on each one respectively (in particular, in the case of shared hosting solutions, where multiple customers may be making use of the two systems), *may* have a noticeable impact upon which of the two would be more performant (and would, therefore, be at least partially dependent on the specific environment/solution in question). It may be worthwhile, in such cases, even just testing each of them out, to get a "feel" for which of the two seems to be running better at that particular environment/solution.

**Comment by harryqt** [comment]
Thank you for the recommendations. Closing it.
