### ISSUE TITLE
Will logging to database improve performance over flat file?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#176]
Will it?

**Comment by DanielRuf** [comment]
It depends. We did no benchmarks of this and a database can only keep a specific number of connections open. You can easily take down a database server with too many connections / requests in a small time frame.

File systems are normally faster and do not have this problem but file locks.

See
https://dzone.com/articles/which-is-better-saving-files-in-database-or-in-fil
https://stackoverflow.com/questions/2147902/is-it-faster-to-access-data-from-files-or-a-database-server
https://www.quora.com/Which-is-faster-SQLite-or-MySQL

As we do mostly write / INSERT operations you can probably benchmark / test this.

**Comment by mikeruss1** [comment]
being simpler I would expect flat files to be faster. The issue for me was that every month or so they reset and I lost all my data. Since switching to DB early Jan there have been no problems.

**Comment by DanielRuf** [comment]
> being simpler I would expect flat files to be faster. The issue for me was that every month or so they reset and I lost all my data. Since switching to DB early Jan there have been no problems.

This would never occur if we would finally swithc to molog for a proper write- / append-only file with automatic logrotation.

I often mentioned that we should not reinvent the wheel and use this @Maikuolan as this works very well even in big production software solutions.
