### ISSUE TITLE
Punycode <-> UTF-8

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#177]
Anyone know any good libraries, classes, algos, methods, etc to convert between punycode and UTF-8? There are a few CIDRAM modules which could benefit from such functionality, and I'd like, if possible, to be able implement that kind of functionality into CIDRAM.

I know I could achieve this with [idn_to_utf8](https://www.php.net/manual/en/function.idn-to-utf8.php), but the problem with that function, is that it relies on the [Intl](https://www.php.net/manual/en/book.intl.php) extension, which isn't universally available for all PHP installations, and also doesn't always behave consistently or as expected for all operation systems. If there's a good polyfill available somewhere for that function, which doesn't itself rely on Intl, I could always implement that as a fallback to use for when that function isn't defined at an affected particular PHP installation, but basically, I'm all ears for any ideas that anyone might have here.

Not a super high priority, as it doesn't affect CIDRAM's core functionality in any way, but just something cool which could benefit certain CIDRAM modules, and I figure it would be worth creating an issue here, to invite ideas. :-)

**Comment by DanielRuf** [comment]
Check the Symfony packages.

**Comment by DanielRuf** [comment]
See https://github.com/symfony/polyfill-intl-idn

**Comment by Maikuolan** [comment]
The Symfony packages for this look pretty good; I reckon that they're the best way forward. Cheers. :+1:

Beginning work on this now.

**Comment by Maikuolan** [comment]
Done (https://github.com/CIDRAM/CIDRAM-Extras/commit/184a17d521426ed4f5d54b7215d0f8b7d228baf5). :-)
