### ISSUE TITLE
Logs not updating since update 1.17.2-DEV+20168400

### ISSUE THREAD

**Issue by htjoe38** [CIDRAM/CIDRAM#179]
Updated cidram to --
1.17.2-DEV+20168400

at 12:29 BST today - 19 June, along with a number of other updates, the cidram logs stopped at that point even though there are 403's in the Apache logs. The last entry in the cidram logs was at 12:28 BST   And when tested cidram is still giving 403's. But nothing in the cidram logs.

I did do a number of updates at that time so it could be something else that I did, and I'm looking into it. But the timing is very suspicious.

**Comment by Maikuolan** [comment]
Cheers. I'll investigate shortly.

**Comment by Maikuolan** [comment]
Found the offending code.

(In `functions.php`):
```
$Steps = preg_split('~[\\\/]~', $Path, PREG_SPLIT_NO_EMPTY);
```

Still don't quite understand *why* the problem is occurring though.. looking into it further. Will reply again as soon as I've figured it out.

**Comment by Maikuolan** [comment]
Uh.. okay. Feeling a little dumb now. <.<

Figured it out. Missing parameter. Fixing now. Will reply again as soon as the fix is up.

**Comment by Maikuolan** [comment]
Fixed (74b02d1450f79e67cf45f7bf50868fa2f3c9685c). :-)

Let me know whether the problem persists after updating.

**Comment by htjoe38** [comment]
No change.

Still no cidram killogs.

Updated to  cidram 1.17.2
I have the old "ctestc" at the end of my custom module which gives me the expected "Access Denied" page, the 403 is shown in the Apache logs but nothing in the cidram killog.

**Comment by Maikuolan** [comment]
Hm, okay. :-/

Just to confirm: What value is currently in your configuration for `logfile`?

**Comment by htjoe38** [comment]
configuration for general➡logfile:

{mm}killog.txt

This is unchanged for a very long time !
and gives me a new killog every month.

**Comment by Maikuolan** [comment]
Cheers. :-)

Just asking so that I can test the exact value against the latest code, to check whether any recent code changes are somehow not playing nicely with that value (and if so, why).

Tested it just now at my local copy, and it resulted in the creation of a new file, `06killog.txt`, with the blocked request correctly logged (so, the value itself doesn't seem to be connected to the problem at all).

Any error logs produced, or any unusual behaviour experienced other than the problem with logging?

**Comment by htjoe38** [comment]
This was in the error.log and the timing is when I updated. I have been adding new block lists - copied from www.blocklist.de which may or may not be relevant. This error was repeated 15 times.

[19-Jun-2020 12:28:42 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598
[19-Jun-2020 12:28:42 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598
[19-Jun-2020 12:29:04 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598

**Comment by htjoe38** [comment]
Just to test - I have removed my new block lists from "Configuration for signatures" and no change - still no killog.

**Comment by htjoe38** [comment]
After updating to cidram 1.17.2 last night I thought that the killogs were still not showing but ...
they are but not in the /public_html/cidram/vault/ directory. Instead there is a new directory 

/public_html/home/xxxxxxx/public_html/cidram/vault

and all the new 06killog.txt entries are now in this new directory.
So a partial success !

**Comment by Maikuolan** [comment]
Actually, that does help a bit. I think I've figured it out. Working on a fix now.

**Comment by htjoe38** [comment]
Just updated some signature files using the front end and it appeared to work correctly but this was added to the error.log.  The timing  corresponds with each update, which I did one at a time.

20-Jun-2020 12:05:23 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598
[20-Jun-2020 12:05:45 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598
[20-Jun-2020 12:05:57 Europe/London] PHP Notice:  Undefined index: Name in /home/xxxxxx/public_html/cidram/vault/frontend_functions.php on line 598

**Comment by Maikuolan** [comment]
Fixed both (a898c85e677fe05a86e7324213b1a0daaf470b49). :-)

Let me know how it goes after that.

**Comment by htjoe38** [comment]
Thanks Maikuolan
Updated cidram to  1.17.3-DEV+20171552
The logs are showing where they are supposed to be, and no new error logs.
All sorted.

**Comment by Maikuolan** [comment]
Awesome. :-)
