### ISSUE TITLE
PHP error on updating

### ISSUE THREAD

**Issue by htjoe38** [CIDRAM/CIDRAM#182]
Whilst updating (cidram  1.17.4-DEV+20193999 and signatures 2020.193.592 ) today these errors were thrown, unable to reproduce probably as they are only part of the update procedure. However I did update the signatures first and cidram last so it's possible that these errors have already been resolved in the latest cidram 
 Full file path reacted.

> [13-Jul-2020 10:50:21 Europe/London] PHP Notice:  Undefined index: Extended Description in /xxxx/vault/frontend_functions.php on line 749
> 
> [13-Jul-2020 10:50:22 Europe/London] PHP Notice:  Undefined variable: Reactivate in /xxxx/vault/frontend_functions.php on line 1903

**Comment by Maikuolan** [comment]
I'll investigate this shortly. Cheers. :+1:

**Comment by Maikuolan** [comment]
Haven't replicated the problem at my end yet, but I can see where/how it could theoretically occur within the codebase, and some possible ways to strengthen safeguards against it, so I'll go ahead and mark this as a bug and begin working on a fix shortly.

**Comment by Maikuolan** [comment]
Done. Problem shouldn't reappear now. :-)

**Comment by htjoe38** [comment]
Thanks  Maikuolan

**Comment by htjoe38** [comment]
Updated to 1.17.4-DEV+20195172 - and nothing else which repeated the same error codes --

```
[14-Jul-2020 10:23:31 Europe/London] PHP Notice:  Undefined index: Extended Description in /xxxxx/vault/frontend_functions.php on line 749
[14-Jul-2020 10:23:32 Europe/London] PHP Notice:  Undefined variable: Reactivate in /xxxx/vault/frontend_functions.php on line 1903
```
