### ISSUE TITLE
Automatically use log by default

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#183]
I'm finding my self all the time selecting a log file to view. An extra step not needed imho.

Is there a way to automatically view the latest log file?

**Comment by Maikuolan** [comment]
Sorry for the delay. Busy working on some other projects the past few days.

The problem with having CIDRAM automatically select a "default" log file right from the start, is that there are several different types of log files available, so it's difficult to know *which* log file should *be* the default.

Maybe I could code it that it just remembers the most recently viewed log file, and automatically loads *that* log file upon any subsequent visits to the logs page, when none others have been specified (and assuming that log file still exists at that time)? Not quite the same thing as setting a default, but should suffice to get rid of the extra step. :-)

**Comment by eurobank** [comment]
No problem.

How about reading the kind of the format of the log file (that varies but it is declared in ther settings) and use the latest by date?

**Comment by Maikuolan** [comment]
It should be possible now to set a "default" log file now by loading it once, selecting the "Remember" checkbox (a search option newly added tonight), and pressing "OK" ([`dfdf59e`](https://github.com/CIDRAM/CIDRAM/commit/dfdf59efc1481eb0c066655dc7a7fc9a97a03511), [`17275dd`](https://github.com/CIDRAM/CIDRAM/commit/17275dd994891e976542121c2e68ffced0599b23)).

This way, it isn't exactly "automatic" per se, but should basically achieve the same end-goal (ensuring that the same logfile is loaded automatically every time we access the logs page, without needing to explicitly click on it, or at least.. without needing to click on it anymore once we've clicked on it for the first time and opted to have our selection "remembered"), while avoiding the problem of how to "decide" *which* logs to "automatically" select.

I'll mark this as implemented.
