### ISSUE TITLE
Sorting of Log Entries

### ISSUE THREAD

**Issue by jjrueger** [CIDRAM/CIDRAM#189]
Please use this template when reporting bugs, problems, issues, etc.

## Server information.

CIDRAM version used: 2.4.3
PHP version used: 7.3.21
Extension➡Installed/Available

Operating system used: Linux cwh910.canadianwebhosting.com 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 #1 SMP Wed May 29 04:37:40 EDT 2019 x86_64
---
## Issue
A suggestion for the log files (and excuse my ignorance if what I am suggesting is actually already possible).
I access the frontend of CIDRAM to view the log files (I know my bad) and it would be nice to be able to sort the log entries by date, ip, etc.  Right now the log entries are ordered by date and time ascending so to get to the most recent entries you have to go all the way to the end of the log file.  Options to change the default behaviour of the log entries (i.e. display by date and time order either ascending or descending) would be very nice.  Even nicer would be a log output in some sort of CSV format where you could sort by column values.

A general question to other users of CIDRAM would be how do you look at the CIDRAM logs? Via the frontend or via some sort of log viewing tool the retrieves the actual log file via the backend?  Thanks.
 ### Expected behavior
What should normally happen?

### Actual behavior
What is actually happening?

### Steps to reproduce the behavior
* step 1
* step 2
* step 3
* …

### Last known working version without this issue.

---

**Comment by Maikuolan** [comment]
Definitely a good idea. :-) 

Not sure offhandedly how feasible the idea is, but I'll experiment a little at my end over the coming days to see whether I can come up with something like that or do something with it.

I'll reply again a little later.

**Comment by 737simpilot** [comment]
I just view the logs in the logs folder of the CIDRAM folder sitting in my public_html. You set this up from withen the CIDRAM frontend.

**Comment by Maikuolan** [comment]
I've began working on this. I should have something ready soon.

**Comment by Maikuolan** [comment]
Done ([`dfdf59e`](https://github.com/CIDRAM/CIDRAM/commit/dfdf59efc1481eb0c066655dc7a7fc9a97a03511), [`17275dd`](https://github.com/CIDRAM/CIDRAM/commit/17275dd994891e976542121c2e68ffced0599b23)). :-)

**Comment by jjrueger** [comment]
Looks wonderful and works like a charm!  Thanks so much for doing this.
