### ISSUE TITLE
The HTTP version checker module

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#194]
This is a module proposal for CIDRAM.

Purpose:

To catch very clever web scanners, hackers, etc.

Scope:

What this module would do is check the type of HTTP request and if it doesn't meet the module's settings will outright block or present a captcha. This firewall option is available in CloudFlare and I feel it would be a great addition to CIDRAM for those that either don't use CloudFlare or don't want to mess with CloudFlare. In CloudFlare you can you can allow, block, JS check or captcha a type of HTTP version that comes across. As of this post there are six HTTP versions that are listed in the CloudFlare firewall. And they are:  HTTP 1.0, HTTP 1.1, HTTP 1.2, HTTP 2, HTTP 3, and SPDY 3.1.

Evidence:

I have found that a majority of all shenanigans all use an older version of HTTP before version 2. With an HTTP version checker module like this, you can set the module so that if any HTTP version below say version 2 comes across they are presented a captcha (probably would be a good idea by default) or outright blocked. My browser and probably many more legit browsers now all use at least version 2. Anything lower than that will undoubtedly be either A) a very old browser, B) a very niche browser or C) shenanigans. Now in my case I do use a niche browser called Pale Moon and it does use HTTP 2. I'm sure Ice Weasel and the rest probably use version 2 as well. However, I'm sure very stubborn Internet/computer users may still use Windows XP and they may only have the ability for an older HTTP version. 

Not sure if CIDRAM can do this or not, but I present it here to get some opinions on its possibility.

Whats say you?

**Comment by mikeruss1** [comment]
there is certainly a fit, if they get a 403 on my site the vast majority are using 1.0 or 1.1. Some caution needed though, Googlebot and bingbot use 1.1. Most users are on 2.0.

**Comment by 737simpilot** [comment]
Googlebot et al is whitelisted by CIDRAM so shouldn't be an issue I think.

**Comment by Maikuolan** [comment]
I like the idea. I'll need to do some more research into this first though, I think (potential unknown factors at play). I'll reply back a bit later.

**Comment by bigalownz** [comment]
good idea

HTTP 1.0,  should be blocked but HTTP 1.1, HTTP 1.2, HTTP 2, etc are still active

I been blocking http 1.0 for years with

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{THE_REQUEST} HTTP/1\.0$
RewriteRule .* - [F,L]
</ifModule>
```

**Comment by 737simpilot** [comment]
So it's been 51 days now that I started blocking old HTTP version traffic at the CloudFlare level and my observations so far are that HTTP versions from 1.0 to 1.1 are all shenanigans. I have yet to see legit traffic come from those HTTP versions, and I'm pretty sure if I ever do it'd be someone on XP, Tor, using Kali or the browser in Raspberry PI OS and other niche stuff. I was blocked from going to my website in Raspberry PI OS due to the HTTP version and I see Tor hits use an old HTTP version. I think it's 1.1 or 1.2.. Since I'm not too concerned with the PI block due to the fact most people don't surf the Internet with a PI or would even hit my site, I left that HTTP version block alone. I think it was version 1.2. 

All of my legit traffic thus far in 51 days has come from HTTP version 2.  In fact, and this is crazy, I have hardly ever saw CIDRAM log one block since I started to block HTTP versions 1.0 - 1.2. There's been maybe one block show up in my CIDRAM log every two weeks or so that happened to pass the muster that is CloudFlare's firewall. Not their paid for WAF, but my personal firewall settings. On the other hand, I don't exactly have stellar SEO either. But I've never blocked any of my users yet either. I do run two forums. One with about 100 users and the other with only one user that so happened to sign up last week and me. LOL I think social media has killed the modern day tech computing forum medium. That, and I'm about 15 years late to the party. Oh well. I need to pull some Ads and other stuff. It's on the back burner.

Now Google bot et al do use HTTP version 1.2 so I whitelisted just the very specific CIDRs I've see thus far for Google et al in CloudFlare. Since crap can come from within those CIDRs, especially Microsoft's, I leave it up to CIDRAM and NinjaFirewall to block any of that should it get past my whitelist in CloudFlare. I would refrain from a UA whitelist. That can be faked, but of course CIDRAM should be able to catch that. I also only allow three prominent search engines bots to craw my site; Google, MS bot, and Yahoo. Most search engine traffic for me comes from Google or its country hosted Google page. The next being Microsoft and Yahoo is like a wallflower at a party. LOL If anyone does use DuckDuckGo or SwissCows, that works due to using Google's search facility or what ever it is. Even though I don't allow DuckDuckGo's bot which I've seen get blocked, they due list my site in their search results. I've seen their bot get blocked in CloudFlare, but they use an Azure server and I'm not tailoring any of that just for DuckDuckGo where I'll open the door for other crap in that CIDR or whole ASN. Bad thing about using CIDRs at CloudFlare is that they only allow a /16 and /24 I think it is. So if you just need a /21 you have to do a massive /16. Consequently, if you need a /9, you'd have to figure it all in to two or more /16s. I'm hoping one day CloudFlare will not only allow more CIDRs, but also wild cards in firewall rules. For example, I can't wild card UAs. If I could that'd really cut down on my massive rule lists. Right now there's like 40 or so. LOL!  Not including some 70 pages of ASN/IP and Country JS/captcha challenge rules. HAHAHA. I also just straight up block a whole country like China and Russia. Sorry, I really have no use for you, and my logs time and time again all show traffic from Russia being a WordPress hack finding vulnerability bot or other crap. China is off the scale in all their IP hits. I've seen them probe my router at home when I had the capability of monitoring SNMP.

Anyway, the HTTP version is indeed a strong indicator of shenanigans from what I have observed in the last 51 days. Only a good, prudent and savvy hacker wearing a black hoodie complete with a Time Warner owned Guy Fawkes mask would use a more up to date HTTP version. :) For me that still doesn't mean anything because the UA or IP could get blocked at the CloudFlare level. But the HTTP version block has proven to be massively effective and at the same time not block legit traffic that I can see. Of course YMMV depending on your platform, content, SEO and what not.

**Comment by 737simpilot** [comment]
> HTTP 1.0, should be blocked but HTTP 1.1, HTTP 1.2, HTTP 2, etc are still active


If you can type at least four paragraphs citing your unbiased sources, I'll consider your facts.. :) I need whole, unadulterated proof with use cases to legit traffic older than HTTP version 2 other than what I mentioned about Raspberry PI OS, old operating systems, Kali et al and maybe some god awful shit smartphone or tablet. My 2 year old $80 Motorola phone doesn't even get blocked. Now that I think of it. Maybe, just maybe a smart TV's browser or game console. But my website's are meant to be surfed and fully utilized with those platforms so it's no loss. My targeted audience wouldn't even use that either. Be different if I was hosting a rotten tomatoes movie critic website or something.

**Comment by mikeruss1** [comment]
there is a correlation as long as you allow Bing and Google through. However I havent found any cases where CIDRAM didnt catch it anyway, and there are some I wouldnt want to block. My Rainmeter plugin uses 1.1 and I noticed this one which seems to be Edge?
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66

so I am not sure it actually achieves anything and it would need careful watching and whitelisting.

**Comment by 737simpilot** [comment]
Hmmm, that's an interesting UA there. I don't think Edge abbreviates like that and I don't ever recall seeing that format. I suppose it's within the realm of possibility of someone's poor attempt at making a fake UA look like edge. Or it's a headless Edge of some type. Though, with headless Chromium/Chrome it mentions that.

So what is this Rainmeter plugin and is it making GET or POST requests to a website or is something else pulling data from it? If the former, then blocking or at least JS/captcha checking would be a moot point since it's is conducting its own web requests withen the protective web property. If something else is pulling requests from it, then your configured WAF could impead its functionality for obvious reasons. In which case you have to do like I described with search engine bots. IP or CIDR whitelisting and hope thst if it has to be whole CIDR whitelisting nothing in that range that's up to no good escapes CIDRAM after the CloudFlare filter so to speak.

Again, and I really can't stress this enough. My observations so have have concluded that many shenanigans emanate frim older HTTP versions and by either JS checking, captcha checking or outright blocks will block a lot of crap. To put a percent on it, probably some 99% of traffic belonging to no good IPs. And again, yes some legit traffic does use older HTTP versions and that can be rectified by IP whitelisting or if necessary CIDR whitelisting. For me personally it's only been for Google el which kinda pisses me of on two points. 1) they should at leat be using an HTTP version to modern spec of 2 or higher like what all modern day browsers use. And 2) The Google or even Microsoft bots don't seem to use consistent UA's. As a matter of fact, Mozilla's implemention of keeping an HSTS list of known HSTS capable websites is flawed like this with not only and old HTTP version, but a hodge podge of IPs from Azure of all places and that CDN has lots of crap traffic. The other is a none standard UA that could be whitelisted and DNS checked for possible UA falsification in case a wiuld be hacker grows a brain. So I'm stuck not allowing Mozilla to check my HSTS capable websites. If I end up getting purged from the list then all well. If you want web Devs to deploy the utmost in security, then do your part in providing GET request consistency in an effort to help said web Devs keep the web property secure. It's kinda like a group effort. What they do now creates a form of tug of war.

I guess it doesn't surprise in the slightest. I used Phoenix, The Mozilla Suite and Firefox for years until they started to Chrome copy to the point of copying extension code with the very hack, insecure Web Extension code over the tried and true XUL code. To top that cluster off, they ousted their CEO for political reasons. So much for the 1st amendment. It's null and void to what amounts to an alliance to border line socialist Nazis who praise book burning and statue destruction. The United States' Silicone Valley bis not made of Silicone but of cockroach vomit.

Harsh? Sometimes the truth needs to be spoken in Thomas Payne like common sense.

Addendum: I typed all this on my marketer's wet dream machine known as a smartphone. So there may be writing mistakes.

**Comment by 737simpilot** [comment]
Yep! The machine made me type like a monkey where the presentation could be charted and given its own datum that would show Phone: Smart. Human: dumb.

Next thing you know us monkey's will fling crap at each other on platforms known as social media and get rewarded with bananas that take the form of a like button or another psychological digital form to help keep a user entangled within a marketer's web to fulfill the bottom line that keeps the share holders happy with dividends.

**Comment by Maikuolan** [comment]
So.. Just thought worth mentioning: I'm still interesting in implementing this, and it's still on the to-do list. Just been a little preoccupied with other things, plus some planning for other future changes to CIDRAM which might potentially affect this idea haven't been quite fully sketched out yet. But anyway, it'll definitely still be happening. :-)

**Comment by mikeruss1** [comment]
rainmeter is a desktop plugin that shows weather, stock market numbers, PC system figures etc. Lots of free choices. I use it to show statistics from my website. So the point is there will be a lot of valid utilities using version 1.

**Comment by 737simpilot** [comment]
So it looks like Edge does abbreviate their name in the UA. I don't recall seeing that happen before. 

https://www.whatismybrowser.com/guides/the-latest-user-agent/edge

**Comment by 737simpilot** [comment]
@Maikuolan No problem.

**Comment by 737simpilot** [comment]
@mikeruss1 https://cyberpcforum.com/viewtopic.php?p=3192#p3192

@Maikuolan If this is implemented, along with the block ability it should have a captcha check as well in its configuration. And I'd have it allow you to pick which versions to block or captcha.

**Comment by Maikuolan** [comment]
Added the HTTP version checker module to the modules list just now. :-)

When you've got a moment, mind checking it out and let me know what you think about it? Cheers.

**Comment by 737simpilot** [comment]
Got a minor issue. For some reason I can't change the settings. If for example I set the Config. to block HTTP version 1 to true, it stays at false. I even went into the config.ini and manually set it and in the frontend it was still set as false. 


I went over all three code updates, the PHP module, yaml and dat file and don't see anything out of place that I know of. Though, I don't know PHP so was just looking for stuff I know that could be out of place like a misplaced ' or ", etc. 

I can save to the config.ini. There doesn't seem to be an issue there. As an example, I can change the Recaptcha settings in the frontend and that sticks in the config.ini, just not any settings for this module. It seemed like a caching issue, and I do omit caching site wide in CloudFlare using a page rule, but just in case, I temporally bypassed CF with my hosts file and I still had the issue. And it certainly wouldn't be a cache issue since I can change the Recaptcha options and they will stick in config.ini. I also was able to save a custom block reason text that is an option at the bottom of this module's Config. settings. SO trhat partr of the module works, just not being able to set true or false.

I don't know if it's something in the PHP or yaml file. 

Question: In the PHP file lines 34 though 36 look interesting. I have no idea what the } does, but shouldn't that be on line 37 to close it all off for lack of the proper term?

I also tested all three older versions prior to the addition of spdy, and they too didn't work for me to save configuration options. 

Check Gitter. I found an old error_log that may or may not be an issue now.

**Comment by Maikuolan** [comment]
I think I've figured out the problem. It seems that the configuration system doesn't play well very non-alphabetic characters in configuration directive names (which, is kind of okay really anyway, since I shouldn't have really been using non-alphabetic characters anyway, per my own code-style guidelines). '^.^

I've renamed all the affected configuration directives so that they comply with the code-style guidelines properly now, so that problem should be resolved now. :-) 

> Check Gitter. I found an old error_log that may or may not be an issue now.

I'll reply to that one there.

**Comment by 737simpilot** [comment]
It's now working. However, another glitch that may be host related or something. 

If I block 1.1 I get blocked. Looking at a HAR file I see I'm using 2.0. So it seems like there's a downgrade or something? How is CIDRAM seeing the HTTP version? 

I block 1.1 in CloudFlare and have had no issue and no one else as well. 

It is interesting though, and I'm not sure if this is part of the logs, but all of my access logs say 1.1 no matter what HTTP version.  It's been like that for years. Maybe it's a host thing? Like something internal? Or a needed server module? I have no idea. All I know is that my connection is 2.0, bypasses CloudFlare's block for 1.1 and CIDRAM is saying I'm using 1.1.

**Comment by Maikuolan** [comment]
I did some googling today, and among other things, I found this:

*Source: https://webmasters.stackexchange.com/questions/130725/http2-is-enabled-and-working-but-php-serverserver-protocol-still-says-ht*

> This has to do with how Cloudflare connects to servers. Although it does serve the client via HTTP2 (or HTTP3), it still connects to the server itself via HTTP1.1.
>
> > Cloudflare only uses HTTP/1.x between the origin web server and Cloudflare.
>
> https://support.cloudflare.com/hc/en-us/articles/200168076-Are-the-HTTP-2-or-SPDY-protocols-supported-between-Cloudflare-and-the-origin-server-#6ncFUWOVRaVtPzYN1euBIC
>
> This particular post helped illuminate the issue for me: https://community.cloudflare.com/t/passing-the-correct-server-protocol-to-the-origin/82386
>
> I wish Cloudflare made it more obvious on their HTTP/2 Network setting that this was the case...

Your websites are behind Cloudflare, right? Might be that that's causing the issue here, maybe?

**Comment by 737simpilot** [comment]
Yeah, that's the exact response I got from my host when I inquired about it. I also noticed with my host however that the connection was still HTTP/1.1 bypassing CloudFlare and all my access logs are showing HTTP/1.1 which has been the case with not only this host, but three previous hosts I used. 

This is a really bummer. It means I can only use this module partially I think, unless ALL requests no matter the HTTP version are sent HTTP/1.1. If a VPS fixes that then maybe I'd be apt for one which was something that's been on the back burner for some time. My Linux terminal skills are subpar so it's not something I wanted to mess around with yet. Even then, there still would be the HTTP/1.1 version coming from the edge. 

I feel like I wasted your time with this idea as I had no idea that this was the case. This module may be beneficial to those that don't use CloudFlare though, but as I said, my shared plan only shows HTTP/1.1. And that's seeing my browser use HTTP/2.0 in the Web Console. So that's why I inquired about it with my host. 

I'm still awaiting my host's response on the HTTP downgrade I'm seeing not using CloudFlare. Yesterday they told me they kicked the ticket up to level III support.

**Comment by Maikuolan** [comment]
> I feel like I wasted your time with this idea as I had no idea that this was the case. This module may be beneficial to those that don't use CloudFlare though, but as I said, my shared plan only shows HTTP/1.1. And that's seeing my browser use HTTP/2.0 in the Web Console. So that's why I inquired about it with my host.

No problem. I'm feeling like this situation is probably subject to specific conditions, like e.g., whether someone is sitting behind a CDN or reverse-proxy like Cloudflare, whether their VPN enforces specific protocol versions, etc and etc.. and if that's the case, then I guess, there's a good chance that it'll probably still be useful for *some* CIDRAM users out there, just not everyone, unfortunately (and that's kind of fine too, since this is a module, rather than a part of the CIDRAM core; features that fit the bill of contributing towards the core goals/intentions/etc of what CIDARM is meant to do, and which should definitely be useful for everyone that uses CIDRAM, e.g., blocking CIDRs, ability to use modules, auxiliary rules, etc, we would expect to belong to the main CIDRAM core, whereas modules generally provide as a means to provide everything else, additionally functionality which may sometimes be absolutely necessary for some specific users, while not being wanted at all by other users, or sometimes highly desired by some users while being actually problematic for others). Anyway, the module exists now, and the work is done, so even if we've found it doesn't quite work exactly how we wanted it to, as long as it does still potentially work for some users and there's no more work to be done with it, I'll keep it up there (no real reason I can think of to get rid of it now, after all).

> I'm still awaiting my host's response on the HTTP downgrade I'm seeing not using CloudFlare. Yesterday they told me they kicked the ticket up to level III support.

Cool cool. I would be interested in knowing their response, since this is a kind of new situation for me as well, and I feel like I might be able to learn something new by knowing their response (like how different host policies and practices might have an effect towards upon implemented HTTP protocol versions, beyond the user's own browser capabilities and the server's own support versions). :-) 

On the flip-side: Even if it turns out that everything gets normalised or downgraded back down to HTTP/1.1 at your host, it might be useful to still keep the module and just block everything older than that, along with some of the weirder options (e.g., HTTP/0.9, IRC, RTA, etc). It's questionable whether such requests would even be accepted by the server in the first place, regardless of whatever CIDRAM does or whether CIDRAM is even installed there, considering the age of some of those protocols, the question of whether the server software would even support them in the first place and so on (I anticipate a number of responses with `426 Upgrade Required` and `400 Bad Request` being returned by the server in many cases). But, since I saw them noted down in the IETF RFCs related to the matter in question and having them supported by the module makes sense within the context of the module, the options for those protocols and protocol versions are provided by the module. It might be completely redundant anyway; not sure. But, it's an idea.

**Comment by 737simpilot** [comment]
Yeah, I'm keeping those rather obscure HTTP versions blocked, and I was thinking the same thing on wheather the host would not even support them from the begin with.

**Comment by 737simpilot** [comment]
I see a chief executive got back to me. Seems like a little fog in the communication. I've tried to elaborate as best I can.  He was thinking of deep packet inspection. 

Can HTTP/1.1 use TLS? I think it would. He made a mention of that.

**Comment by Maikuolan** [comment]
Planned to write a reply just now, but feeling pretty tired from work and not really getting my thoughts together properly. I'll try to reply properly tomorrow.

**Comment by 737simpilot** [comment]
No problem. He got back to me and did acknowledge that there was an issue with the access logs reporting the wrong HTTP version. So he sent a ticket upstream to the software vendor and said this would be fixed in short order and would let me know when that happens.  I think he said it was a software bug server side. 

Still doesn't mean I can use this though I guess seen as how CloudFlare for what ever reason uses HTTP/1.1 for edge to server. That's a real bummer. 

Will keep the defaults turned on though.

**Comment by 737simpilot** [comment]
Okay, this is the message I got back from my host on the access logs showing HTTP/1.1.

"We've heard back from upstream and this is intentional behavior on
their behalf to help reduce some bugs in other software which don't
handle the header cleanly when it returns HTTP/2. We've requested that
this gets fixed and were told it could be added in an upcoming
release.

In the interim you can detect non-HTTP2 requests by checking if the
"X_SPDY" server header exists. 

["X_SPDY"]=> string(5) "HTTP2"

Sorry for any inconvenience this may have caused."

**Comment by Maikuolan** [comment]
Tomorrow -> 10 days later (my bad.. busy with work and all that). '^.^

https://www.techradar.com/uk/news/microsoft-will-finally-retire-aging-tls-10-and-11-protocols

> Can HTTP/1.1 use TLS? I think it would. He made a mention of that.

*Related: https://tools.ietf.org/html/rfc2817*
> 3. Client Requested Upgrade to HTTP over TLS
>
>    When the client sends an HTTP/1.1 request with an Upgrade header
>    field containing the token "TLS/1.0", it is requesting the server to
>    complete the current HTTP/1.1 request after switching to TLS/1.0.

I'm just wondering whether I should update the module again to include TLS/1.x options in there..? I'm not sure though, TBH.

A nice, big, concise list of *"What possible values could populate `$_SERVER['SERVER_PROTOCOL']`?"* would be really nice, and really cool (even if it isn't necessarily comprehensive or up-to-date), but I haven't found anything like that yet, and I'm not really holding my breath for it.

Haven't had time to run any experiments or tests at my end recently, but maybe I'll do some experimenting if there's time and need for it.

> In the interim you can detect non-HTTP2 requests by checking if the
> "X_SPDY" server header exists.
>
> ["X_SPDY"]=> string(5) "HTTP2"

Should be pretty easy to code for that. Reckon I should..?

**Comment by 737simpilot** [comment]
Seems prudent I guess, but since I discovered that an HTTP 2.0 request is not only not carried over from the CloudFlare edge or at my origin due to their server software, I don't think it would work for me. For others it may, principally if they roll VPS or bare metal. But if they do use CloudFlare it'll be fruitless unfortunately. CloudFlare needs to change that so that edge servers still carry the same HTTP request version, though, I can understand why this is happening from a server to server standpoint. But when your firewall is almost deep packet inspection like it's kinda critical.

**Comment by Maikuolan** [comment]
Yeah.. Agreed.

Oh well. Anyway, I've added the mentioned changes, to account for X_SPDY ([`caa0fd7`](https://github.com/CIDRAM/CIDRAM-Extras/commit/caa0fd796ec64cee915357b2b561e31f7cda2b7b)), so, with everything else planned now implemented, and not really anywhere else we can go forward with this, I'll go ahead and close it now. :-)
