### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Function name must be a string

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#197]
```
PHP message: PHP Notice:  Undefined index: in_csv in /cidram/vault/frontend.php on line 1450
PHP message: PHP Fatal error:  Uncaught Error: Function name must be a string in /cidram/vault/frontend.php:1450
```

everything latest. can't open config page.

**Comment by Maikuolan** [comment]
Try running "repair all" via the updates page. It looks like some files might've not updated properly for some reason during a recent update (`in_csv` was changed to `inCsv` in a [recent update](859481ca97cbf67c51d0c6599b3269c2bef2c8de)). Let me know how it goes. :-)

**Comment by harryqt** [comment]
Yup. That worked.
