### ISSUE TITLE
Error with botbrowsers_cidram.inc

### ISSUE THREAD

**Issue by jjrueger** [CIDRAM/CIDRAM#200]
I have been getting the following message in the errorlog since Feb 23:

[2021-02-27T11:10:56-08:00] Error at botbrowsers_cidram.inc:L47 (error code 8): "Trying to access array offset on value of type bool". This was caused by the "botbrowsers_cidram.inc" module.

System information:

    CIDRAM version used: 2.5.0
    PHP version used: 7.4.14
    Operating system used: Linux 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64 #1 SMP Wed May 29 04:37:40 EDT 2019 x86_64

The botbrowsers_cidram.inc appears to be Version BOTB-2019.345.786 dated Dec 24, 2019.

**Comment by jjrueger** [comment]
And now I see that botbrowsers_cidram.inc has actually been replaced by mcm_bobuam.php by MacMathan so I'm not sure how the inc file is being called in CIDRAM.

**Comment by jjrueger** [comment]
Sorry for all the comments ... I now see that these old MacMathan modules are still active in my CIDRAM install ... so I'm assuming that the fix is simply to deactivate and uninstall these three modules: botbrowsers_cidram.inc, botspiders_cidram.inc, and eolbrowsers_cidram.inc (since they have been replaced by BOBUAM).

**Comment by Maikuolan** [comment]
> Sorry for all the comments ... I now see that these old MacMathan modules are still active in my CIDRAM install ... so I'm assuming that the fix is simply to deactivate and uninstall these three modules: botbrowsers_cidram.inc, botspiders_cidram.inc, and eolbrowsers_cidram.inc (since they have been replaced by BOBUAM).

No problem, and yep. :-)
