### ISSUE TITLE
$InstaBan in Auxiliary Rules?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#202]
as you have been doing so much work with Auxiliary rules. is it worth including an $InstaBan capability ?

not important but consistent ?

**Comment by Maikuolan** [comment]
Investigating the possibility now.

(Probably won't appear as a literal "InstaBan" option, but investigating potential equivalents, how we might pull off the same capabilities, etc; Will reply back when I have a clearer idea about it).

**Comment by Maikuolan** [comment]
(No progress yet. Have been caught up with other things. Still on the to-do list though).

**Comment by Maikuolan** [comment]
Trying to figure out the best way to present these new options at the auxiliary rules interface at the moment, what'll look the best, how to best balance usefulness with simplicity, what'll work best for those actually using these new options, etc.. A quick question.

Would you be more comfortable being able to explicitly set specific tracking values for rules (e.g., how long to track an IP violating the rule in question for, how many infractions a violation of the rule in question should count for, etc)? Or would you be more comfortable being able to just select a checkbox or flick a simple switch for it (i.e., no need to explicitly set any values, having CIDRAM instead decide on those values automatically, but by the same virtue, not having fine control over those values)?

**Comment by mikeruss1** [comment]
I reckon keep it simple. If anyone wants more precise control they can use
the custom mods interface.

**Comment by Maikuolan** [comment]
All done ([`019cd6f`](https://github.com/CIDRAM/CIDRAM/commit/019cd6ff64c9c3bfe66da9e9c4905f6ab620fa47) + [`b07d99b`](https://github.com/CIDRAM/CIDRAM/commit/b07d99b54f2f5a12eed04865134955e82e2f8725)).

Marking as implemented and closing. :-)

**Comment by mikeruss1** [comment]
I guess  "Enforce extended IP tracking options" sets the default $instaban rules ?

**Comment by Maikuolan** [comment]
Yep. :-)

**Comment by mikeruss1** [comment]
and confirmed working !
