### ISSUE TITLE
Might be a minor error in the auxiliary rules code

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#210]
Adding a "why reason" reason to the auxiliary rules shows it differently in the Edit Mode. The rule looks good in the yaml file which states:

> Azure:
 Logic: "Any"
 Reason: "403"
 Suppress output template: true
 Don't log:
  If matches:
   WhyReason:
    - "Cloud service ("msaz_cidram.inc-IPv4""

But as you can see here in the two images, there is an abridged format in the Edit Mode versus in the View Mode.

![image](https://imgur.com/cfvvtD7.jpg)

![image](https://imgur.com/J6A1KYQ.jpg)

**Comment by Maikuolan** [comment]
Yep.. That's a bug. :-)

Thanks for spotting and reporting this. I'll take a look at the code later tonight and work on a fix for it.

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by 737simpilot** [comment]
Looks like it's fixed. Thanks.
