### ISSUE TITLE
Custom theme blocking updates

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#212]
I can not update CIDRAM to its latest version; getting the following error:

![msedge_2021-04-13_20-37-30](https://user-images.githubusercontent.com/18257605/114575868-3ac6c800-9c98-11eb-84a7-4580d186a661.png)

It says `theme/cf – Not satisfied.` So how do I satisfy it?

**Comment by Maikuolan** [comment]
This seems to be a bug on my part, with the new dependency system. Working on a fix now and I'll reply again shortly. :+1:

**Comment by Maikuolan** [comment]
Fixed. It should now be possible to update. :-)

**Comment by harryqt** [comment]
Yes, update works now. Thank you.
