### ISSUE TITLE
reCAPTCHA state turned on for some requests when it shouldn't

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#217]
Might have  a bit of an issue here. I see several blocks in the log which are as follows:

ID: 1618957278-291860-4811552670
Date/Time: Tue, 20 Apr 2021 16:21:18 -0600
IP Address: 185.65.134.242
Referrer: https://duckduckgo.com/
Signatures Count: 1
Signatures Reference: 185.65.132.0/22
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE])!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Enabled.

ID: 1618957333-642005-5245791855
Date/Time: Tue, 20 Apr 2021 16:22:13 -0600
IP Address: 185.65.134.242
Referrer: https://mywebsite/
Signatures Count: 2
Signatures Reference: 185.65.132.0/22, functions.php:L1992
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE]), Security!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Disabled.

ID: 1618957343-287211-3808337012
Date/Time: Tue, 20 Apr 2021 16:22:23 -0600
IP Address: 185.65.134.242
Referrer: https://duckduckgo.com/
Signatures Count: 1
Signatures Reference: 185.65.132.0/22
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE])!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Enabled.

ID: 1618957347-674341-2642597024
Date/Time: Tue, 20 Apr 2021 16:22:27 -0600
IP Address: 185.65.134.242
Referrer: https://duckduckgo.com/
Signatures Count: 1
Signatures Reference: 185.65.132.0/22
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE])!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Enabled.

ID: 1618957355-992522-6768251556
Date/Time: Tue, 20 Apr 2021 16:22:35 -0600
IP Address: 185.65.134.242
Referrer: https://mywebsite/
Signatures Count: 2
Signatures Reference: 185.65.132.0/22, functions.php:L1992
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE]), Security!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Disabled.

ID: 1618957359-009874-9147803183
Date/Time: Tue, 20 Apr 2021 16:22:39 -0600
IP Address: 185.65.134.242
Referrer: https://duckduckgo.com/
Signatures Count: 1
Signatures Reference: 185.65.132.0/22
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE])!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Enabled.

ID: 1618957361-108084-8833520376
Date/Time: Tue, 20 Apr 2021 16:22:41 -0600
IP Address: 185.65.134.242
Referrer: https://duckduckgo.com/
Signatures Count: 1
Signatures Reference: 185.65.132.0/22
Why Blocked: Spam risk ("31173 Services AB", L14383:F7, [SE])!
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Reconstructed URI: 
CAPTCHA State: Enabled.

What you'll notice is that if the referrer is from DuckDuckGo the captcha state is on. If the referrer is for the website the captcha state is disabled. The only thing I can think of as to why this is happening is due to my auxiliary rules. But that shouldn't be the case since it's IP to UA specific. My auxiliary rules are the following: 

DuckDuckGo Profile:
 Logic: "Any"
 Profile:
  If matches:
   IPAddr:
    - "20.191.45.212"
    - "23.21.227.69"
    - "40.88.21.235"
    - "50.16.241.113"
    - "50.16.241.114"
    - "50.16.241.117"
    - "50.16.247.234"
    - "52.5.190.19"
    - "52.204.97.54"
    - "54.197.234.188"
    - "54.208.100.253"
    - "54.208.102.37"
    - "107.21.1.8"
DuckDuckGo:
 Method: "WinEx"
 Logic: "Any"
 Whitelist:
  If matches:
   UA:
    - "*DuckDuckGo-*"
   Profile:
    - "DuckDuckGo Profile"

I recently did this due to the false blocks I was getting from DuckDuckGo which is stated in #207 

My reCAPTCHA setup is as follows:

Usermode: 2

Lock IP: True

Lock user: False

Expires in one month, 720 hours.

Signature limit: 1

API: V2

Show cookie warning: False

Show API message: True

**Comment by 737simpilot** [comment]
Oh my God, Caleb, I now know what's going on here. The signature limit is 1 and that's showing as it should. But the sig hit of 2 which I failed to see is why there's not reCAPTCHA offered. I thought they were all a sig hit of 1, but I see this IP hit my auxiliary rule called "security" as well with some requests so that's why a sig match of 2 and thus no reCAPTCHA offered.

**Comment by 737simpilot** [comment]
My security auxiliary rule that I created seems to have did the trick as I intended. It blocks a POST request for certain resources that don't need a POST request and that's why this little "hacker" got blocked. Which is why not only was the IP from a web hoster that tripped a Sig, but on some requests was a POST request for a 2x Sig match. 

Since this IP passed the muster of all my firewall rules in CloudFlare only to get stopped at the CIDRAM level, and since this is nothing but a cloud/web hoster IP, I'll add its ASN/s to the long list of ASNs in CloudFlare as well. LOL

No issue here. Everything worked as intended. Issue can be closed. 

Edit-

On the other hand, should web hosting/cloud IPs have a reCAPTCHA offered? 

Edit 2-

Okay, I see this comment in the file:

 ASN 39351 ("31173 Services AB").
Webhosting and colocation provider, and also a source of spam and other unwanted traffic. Placed into the ISPs file and marked with reCAPTCHA due to the risk of false positives (some companies and networks in Stockholm may use this network). Stop Forum Spam (SFS) listings: 3,966. Updated: 2020.11.09

Edit 3-

Interesting enough, I don't see this IP at SFS, Greynoise, AbuseIPDB or see any open ports checking two sources. Scamalytics gives the IP (ASN?) a score of 13. Those POST requests though are rank BS and that's why I created that auxiliary rule. Never the less, I have no use for this ASN and it's gonna be nuked at the CloudFlare level.

**Comment by Maikuolan** [comment]
> No issue here. Everything worked as intended. Issue can be closed.

Lol, all good. These things happen. ^^

> On the other hand, should web hosting/cloud IPs have a reCAPTCHA offered?

It could be argued that they shouldn't, since a webhost or cloud service shouldn't generally ever be considered as "human", hence no need for a CAPTCHA. However, there are two main problems with not offering one:
1. We might sometimes get it wrong, when we label something as a cloud service (e.g., domestic ISPs which present themselves in a way as to resemble cloud services, or multiplay network offering both cloud connectivity, webhosting, as well as domestic internet connectivity, or ranges might've just been sold by a cloud provider onto a domestic ISP, thus no longer being a cloud range, etc), and there's the risk then, that we may still inadvertently end up denying a human user the opportunity to have access to a CAPTCHA.
2. Inadvertently creating a new "gotcha" in the CIDRAM process. CIDRAM users which look at the available configuration options, and populate them correctly, according to the descriptions of those options, but which aren't aware of certain kinds of traffic being otherwise denied a CAPTCHA outright, may end up having a few *"WTH??"* moments when they notice it, or may end up wasting more time than necessary double-checking everything, thinking they got something in their configuration wrong, even when they haven't. It's easier, I think, to just avoid the potential complications in the first place.

(( It should, however, still be quite easy to deny all cloud services access to CAPTCHAs, per installation, if any particular users want to, by way of creating an auxiliary rule to forcibly disable reCAPTCHA for any requests matching "Cloud" as part of the block reason. ;-) )).

**Comment by 737simpilot** [comment]
> It should, however, still be quite easy to deny all cloud services access to CAPTCHAs, per installation, if any particular users want to, by way of creating an auxiliary rule to forcibly disable reCAPTCHA for any requests matching "Cloud" as part of the block reason.

Ah! I had wondered about that. I did mention a marker idea in #211 so I thought perhaps that may have been the only way. That would make sense to do it via the why reason, I wasn't aware of the option to omit reCAPTCHA  via that method. Or at least I forgot. LOL I tend to just make my rules and go.
