### ISSUE TITLE
(Install + Activate) & (Deactivate + Uninstall) does not work

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#218]
When I tried to use **(Install + Activate)** it only installs but not activating the module.

And for **(Deactivate + Uninstall)** showing:

```
module_abuseipdb.php – An error occurred while attempting to uninstall the component. -0 bytes | 1.311
```

![msedge_2021-04-23_15-24-25](https://user-images.githubusercontent.com/18257605/115854570-03021200-a448-11eb-964d-416800d788a2.png)

**Comment by Maikuolan** [comment]
Replicated + confirmed at my end. Investigating now.

**Comment by Maikuolan** [comment]
Fixed. :-)
