### ISSUE TITLE
Profile doesnt work with negative tests

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#222]
I am trying to limit recaptcha so it only offers it where the reason blocked includes "Cloud service"
so I use this rule which I think should say, if the reason blocked does not include "Cloud service", then do not offer recapcha

If the following conditions are met, profile the request.
Why Blocked ≠ Cloud service*
Other options and special flags:
Forcibly disable reCAPTCHA
Use Windows-style wildcards to test the conditions.
In order to trigger the rule, all conditions must be met.

this does not work, captcha is offered

so I tried this one ...

If the following conditions are met, profile the request.
Why Blocked = Your browser is old and not secure*
Other options and special flags:
Forcibly disable reCAPTCHA
Use Windows-style wildcards to test the conditions.
In order to trigger the rule, all conditions must be met.

this works - recaptcha is not offered

the only difference is the negative test.

**Comment by Maikuolan** [comment]
Going over the code now. Will reply back shortly.

**Comment by Maikuolan** [comment]
Yeah.. Bugged. '^.^

An easy one to fix, at least (one line, already committed at my end). Just so happens that I'm also right in the middle of working on other auxiliary rules stuff at the same time too though, so.. I'll push the changes in ~10 minutes or so, once I've gotten that other stuff committed and ready to be pushed, too.

**Comment by mikeruss1** [comment]
thats what I call service !!

**Comment by Maikuolan** [comment]
Might be a little more than "~10 minutes or so". Something has come up and need to leave the house for a bit. Sorry about that. '^.^

I'll have it sorted out before the end of the night though. I'll reply again a little later. Cheers.

**Comment by mikeruss1** [comment]
NP - no rush thanks

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by Maikuolan** [comment]
When you've got a moment, after updating, let me know how it goes. :-)

**Comment by mikeruss1** [comment]
yep - works now, thanks for the very quick fix!
