### ISSUE TITLE
Stripping out the default "marked for use with..." from the default signature files.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#228]
I'm thinking about stripping out all the existing *"marked for use with..."* (reCAPTCHA/hCAPTCHA) stuff from the default signature files.

*What "stuff" am I talking about, exactly? __This__ stuff, which can currently be found littered throughout all the default signature files:*
```YAML
---
recaptcha:
 enabled: true
hcaptcha:
 enabled: true
```

Since I've been slowly/gradually building/working on implementing some default "profiles" to all the signature sections of the default signature files, I'm not convinced that we really *need* to be marking anything by default anymore, since it's possible for users to leverage profiles via auxiliary rules to specify by themselves exactly which kinds of situations a CAPTCHA should/shouldn't be provided to the end-user.

Since I'm *not* proposing any changes to the signature file syntax/logic, nor proposing to remove *support* for the current existing way of marking signatures for use with reCAPTCHA/hCAPTCHA (i.e., even if what I'm proposing is implemented, it'll still be possible to use the same syntax/logic as is currently possible), what I'm proposing shouldn't pose any backwards-compatibility problems.

Some of the pros of this proposal:
- Currently, that small snippet/excerpt, which is posted above, occurs across all the default signature files, in entirety, 435 times. At 55 bytes per snippet/excerpt, removing it would reduce the total size of all the default signature files by about ~23.36 KBs (which isn't much.. but it's something).
- Those wanting to *not* provide CAPTCHAs by default to *all* end-users, but wanting to still keep CAPTCHAs *enabled* (e.g., to be able to specify by *themselves*, *exactly* when to provide a CAPTCHA to end-user, so that they can provide them in specific situations, but *without* CIDRAM making this decision by itself), may have a slightly easier time of it, since they shouldn't need to explicitly *disable* it anymore for specific situations (CC: @mikeruss1).
- Better, more refined, more precise control for users in regards to which situations CAPTCHAs are/aren't provided to end-users.

Some of the cons of this proposal:
- Since CIDRAM wouldn't be "making this decision by itself" anymore, for those users wanting to provide a CAPTCHA selectively (i.e., `usemode` as `2` or `5`), being able to use auxiliary rules to achieve this would become a *necessity*. That *might* be a problem for those users which choose to keep their front-end disabled, since they'd be depriving themselves of the benefit of the interface provided by the front-end for the purpose of creating/editing auxiliary rules. That might *also* be *especially* a problem for those users which tend to stick with a completely vanilla installation, without bothering to ever enable the front-end, customise anything, install any modules, etc (e.g., CIDRAM users installing/updating CIDRAM via Composer, via the WordPress plugins repository, etc). It might also be a problem for users that tend towards lazier solutions whenever available, since it might mean a *little* more work for them.. though I'm not particularly concerned about that. Though, it should be noted that writing/editing auxiliary rules *without* using the front-end *is* still possible to do, and also still *relatively* easy (i.e., not any harder to do than writing your own custom modules would be). But, since it was designed with keeping in mind those users which don't like messing around with code/markup/etc themselves, and specifically with the idea of being something easily manageable via the front-end, using the front-end would certainly always be easier for it.
- Possibly *slightly* more learning involved for users, since I'd likely need to document somewhere *exactly* what those newly added "default profiles" *are*, so that users will know what to actually type in for conditions when creating auxiliary rules which match against profiles. That shouldn't be at all difficult to do though, since I haven't created too many of them.

Please leave your comments here, or give a thumbs up/down, to let me know whether you like/dislike this proposal, to let me know whether you have any further ideas/thoughts/etc about this.

I plan to propose some other related ideas too, but since they're also separate from this particular idea here, I'll post them as their own, distinct issues.

Cheers.

**Comment by mikeruss1** [comment]
just one thought - the auxiliary rules profile capability is powerful and not overclear. It could do with several examples showing how to achieve various things.

**Comment by Maikuolan** [comment]
I'm going to go ahead and implement this. I'll also get some documentation sorted out for auxiliary rules soon, when there's some time to work on it. :-)

**Comment by Maikuolan** [comment]
Signature file changes implemented. Documentation changes coming soon. :-)

**Comment by Maikuolan** [comment]
*Deferring this issue's remaining tasks to #265.*
