### ISSUE TITLE
[Request] Filter in log viewing by domain/Reconstructed URI

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#232]
Since we use one Cidram instance for most site in the server, could be easy to implement a filter when viewing the logs?

I mean something like using the "Reconstructed URI" ? Filter using that field? 

Because we want to see a per domain report. Manually put something in the search form (ex: "mydomain.com").

cheers

**Comment by Maikuolan** [comment]
I like this idea. :-)

I'll see what I can do about this.

**Comment by eurobank** [comment]
You are one of the most reasonable and friendly developer i have ever seen. Thank you.
