### ISSUE TITLE
Wrong Block? Google bot

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#233]
I see some of these today:

ID: 1624015715-305251-5545100624 »
Date/Time: Fri, 18 Jun 2021 14:28:35 +0300 »
IP Address: 66.249.69.146 »
Hostname: crawl-66-249-69-146.googlebot.com »
Signatures Count: 1 »
Signatures Reference: functions.php:L1577 »
Why Blocked: Fake AdSense! »
User Agent: Mediapartners-Google »
Reconstructed URI: https : // www . website . com/ »

I guess this is totally wrong?

crawl-66-249-69-146.googlebot.com

**Comment by Maikuolan** [comment]
Yep.. Totally wrong. I'll get that sorted out now. Cheers. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by mikeruss1** [comment]
is this the same problem ?
Date/Time: Thu, 17 Jun 2021 10:01:06 +0100 »
IP Address: 66.249.80.217 »
IP Address (Resolved): - »
Hostname: google-proxy-66-249-80-217.google.com »
Query: - »
Referrer: - »
Signatures Count: 1 »
Signatures Reference: mcm_bobuam.php:L103 »
Why Blocked: Suspected bot detected!! »
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/) »
Reconstructed URI: https://www.xxxxxr.co.uk/ »
CAPTCHA State: Disabled. »

**Comment by Maikuolan** [comment]
> is this the same problem ?

Similar, but not exactly.

The original block event was a false positive which caught Google's AdSense checker.

Note the:
```
User Agent: Mediapartners-Google
```
..part.

Yours isn't related to AdSense at all, but seems (AFAICT, and according to a discussion at [SO](https://stackoverflow.com/questions/62891722/https-developers-google-com-web-snippet-is-this-a-crawler-bot)) to be related Google's Android SMS app.

Note the:
```
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)
```
..part.

Though, the URL included in that UA, as well as whatever variants of it that I've tried thus far, seem to all just return a 404. So, not 100% sure about it, nor 100% confident that it isn't just another unwanted spambot or the likes (not sure whether the supposed SMS app actually uses that UA, or still does currently, or whether it might just be being used by other things, or, even if it's legit, whether it's something we need to worry about).

**Comment by eurobank** [comment]
https://www.abuseipdb.com/check/66.249.80.217

**Comment by eurobank** [comment]
Someone says about it "These 'crawlers' are not crawlers but are part of the live website preview used in the Google search engine."

"I had a similar experience as @James and @FFrewin; when testing a new "secret" app/URL I suddenly saw a bunch of traffic from various Google proxies. After some experimentation, it appears that (at least) Chrome on Android uses the these servers as part of their "Data Saver" functionality. The description says: "When Data Saver is turned On, Chrome uses Google servers to speed up and compress page loads". When I turned Data Saver off, the proxy traffic went away.

So these proxies aren't (or at least aren't completely) nefarious. Blocking them might alter or interfere with mobile users' ability to reach your site."


Just someone saying .... maybe they are just scrapers ....

**Comment by 737simpilot** [comment]
Note that `google-proxy-*` is also related to Google translate. 

Since I have a built-in translator using Google on the website already, I block the proxy IP in the auxiliary rules as follows:

>Google Proxy:
 Method: "WinEx"
 Logic: "Any"
 Reason: "403"
 Block:
  If matches:
   Hostname:
    - "google-proxy*"


I also have a sneaky suspicion Google proxy could be used to bypass IP blocking, thus the reason why I block the proxy.

**Comment by mikeruss1** [comment]
there were a bunch of blocks over a very short period, to the IP above, and also  74.125.212.43, also apparently Google. Not seen before or since. Looks fake to me

Fake IP addresses ?
