### ISSUE TITLE
Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots) - Wrong Block? 

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#240]
I see several of these:

ID: 1625057452-374028-0286302508 »
Date/Time: Wed, 30 Jun 2021 15:50:52 +0300 »
IP Address: 54.162.15.145 »
Hostname: ec2-54-162-15-145.compute-1.amazonaws.com »
Signatures Count: 1 »
Signatures Reference: module_badhosts.php:L237 »
Why Blocked: Amazon Web Services! »
User Agent: Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots) »

I can't find any reports for that IP. Could that be a wrong block for some reason?

**Comment by Maikuolan** [comment]
This was blocked due to a signature in the "bad hosts" module blocking requests from AWS. I think, the best course of action here would be for an additional check to be added to that signature to prevent Slack being blocked in the future. I'll get something sorted out now. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)
