### ISSUE TITLE
Updates page error

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#245]
Front end version 2.6.0-DEV+21158235

Warning: substr() expects parameter 1 to be string, array given in /home/xxxxxx/public_html/cidram2/vault/frontend.php on line 1946

the font is bigger on modules list
strange as havent updated the core for a while

**Comment by Maikuolan** [comment]
There aren't any `substr()` calls at or near to line 1946, so I'm guessing this might either be an old, already fixed bug, or something from an older version. Not sure offhandedly whether it still affects the current latest versions.

I can't immediately see any obvious causes for the problem in the code, but let's leave this issue open for a while. I'll reply back here again, as soon as I next update something at the front-end. At that time, when you update, let me know whether the problem appears again. If it doesn't, I guess, it must've already been fixed, or disappeared with a recent update. If it does, then we should hopefully be able to get a clearer idea about the exact cause of the error (affected lines at the current codebase at that time, etc). :-)

**Comment by mikeruss1** [comment]
updated and problem gone away, this was the code ...

                if ((
                    !empty($CIDRAM['Components']['ThisComponent']['Used with']) &&
                    substr($CIDRAM['Components']['ThisComponent']['Used with'], 0, 3) === 'ipv'
                ) || (

**Comment by Maikuolan** [comment]
Ah.. Okay. Now I know what it was. And yep.. Bug. Fixed by 7172f5829c89e15c3a1c9ddac5e4a54032ba4b2d (2021.07.05). :-)

**Comment by mikeruss1** [comment]
just a thought - I update say every 2 months ish, unless there is a pressing reason to do it earlier.
its nice to know whats changed, but the changes page doesnt give the sub version, just the date, so its not obvious.
if its easy could you consider in future adding sub version to each change line?

**Comment by Maikuolan** [comment]
I could do that. :-)
