### ISSUE TITLE
LinkedInBot

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#246]
@Maikuolan Can you please check this block?

Date/Time: Mon, 19 Jul 2021 23:56:48 +0300 »
IP Address: 108.174.5.114 »
Hostname: 108-174-5-114.fwd.linkedin.com »
Query: page=item »
Signatures Count: 1 »
Signatures Reference: module_botua.php:L236 »
Why Blocked: Unauthorised! »
User Agent: LinkedInBot/1.0 (compatible; Mozilla/5.0; Apache-HttpClient +http://www.linkedin.com) »

**Comment by Maikuolan** [comment]
Yep.. Looks legit to me. `Linkedin.com` (cited in both the UA and hostname).. Legit domain for LinkedIn. `108.174.5.114` resolves to `108-174-5-114.fwd.linkedin.com`, which successfully reverses back to `108.174.5.114`. Good enough for me.

Looking at just this specific request in isolation, it would be reasonable to assume that resolving the IP to a hostname and then reversing it back to itself (as is done for a number of the search engines supported by CIDRAM's search engine verification feature) would be a reasonable way to confirm whether a request, supposedly from LinkedIn, is legitimate or not. However, I haven't been able to find any official, authoritative page/tweet/information/memo/whatever from LinkedIn to confirm that. And, based on the information available from [udger](https://udger.com/resources/ua-list/bot-detail?bot=LinkedInBot), it seems that it *might* occasionally *also* appear from AWS (or at least, might've in the past; last detected by them coming from AWS in 2018, so.. a few years back now). So, although we can make *observations* about its behaviour, I'm not entirely sure right now whether we're able to confirm the *intended* behaviour with absolute certainty. That in mind, I haven't updated anything in search engine verification for this just yet (though I might do so at some point in the future if I'm able to find some better information, something official/authoritative, something to convince me about the *intended* behaviour, or along the lines of; so, maybe we'll still be "verifying" LinkedInBot at some point in the future; I haven't seen any actual cases of faked LinkedInBot requests yet though, so it's probably not super urgent just yet, I'd imagine).

Verification aside, for now, I've resolved the false positive through [`8097b79`](https://github.com/CIDRAM/CIDRAM-Extras/commit/8097b7913f523d250d688a294d4bef8b3ddb6fe0). Just pulling out the specific offending part of the specific offending signature, splitting it to its own, separate signature, and checking first for the presence of "linkedinbot" at the beginning of the UA string seems to do the trick.

So, after updating the "Bot UAs" module to the latest version, this false positive shouldn't occur anymore. So, I'll go ahead and marked this as fixed now. But.. I'll try to also find some more official/authoritative information about LinkedInBot a little later too, if I can find the time, to see whether we can go further, confirm anything, etc etc. If anyone else here happens to find something like that in the meantime, feel free to share it here. ;-)

**Comment by eurobank** [comment]
@Maikuolan Since this is the 3rd false block i find, i wonder if the whole logic is wrong. PLEASE do not get me wrong saying this, i only worry about blocking something i shouldn't.

Also i do understand that most webmasters do not check their logs as i do. And that means that CIDRAM must be more bulletproof since the webmasters do not get much involved.

**Comment by Maikuolan** [comment]
> i wonder if the whole logic is wrong.

Do you mean the logic behind just that specific signature, behind that specific module, CIDRAM overall, or something else? Just need to clarify, because I'm not entirely sure otherwise.

> PLEASE do not get me wrong saying this, i only worry about blocking something i shouldn't.

No problem. Seeing as there's always a bit of an ongoing balancing act involved when it comes to things like website security and blocking unwanted traffic, it's normal to be worried about that. Questioning, reassessing, double-checking, reviewing, etc are ways that we hopefully, over time, reduce the likelihood of blocking things that we don't want to block.

> Also i do understand that most webmasters do not check their logs as i do. And that means that CIDRAM must be more bulletproof since the webmasters do not get much involved.

Yep, very true.

**Comment by eurobank** [comment]
> Do you mean the logic behind just that specific signature, behind that specific module, CIDRAM overall, or something else? Just need to clarify, because I'm not entirely sure otherwise.

I wish i could help more on this but i'm just a webmaster working on many sites, Wordpress and others. Not a developer.

So i don't know the existing code "logic" but seeing 3 wrong blocks already, i wonder if some other approach could be better.
