### ISSUE TITLE
Memcached DB

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#250]
thinking of trying the Memcached DB. Obviously if the server restarts I loose the data, would CIDRAM automatically kick off again with an empty cache and the same config?

**Comment by Maikuolan** [comment]
Yes and yes. :-)

A restart would cause the *cache data* to be lost, automatically recreating whatever cache data might be needed upon the subsequent request. However, *configuration data* won't be affected at all, and should be no different, before or after the restart.

**Comment by mikeruss1** [comment]
thank you. Have tested and seems fine. Its done a block and I have looked in memcached and there are several keys generated by CIDRAM and no cache.dat in the Cache area of the frontend. So looks good.

One thought - there is a key "Tracking" - would be worth making more unique to avoid conflict with other site generated keys. Maybe add userID?

**Comment by Maikuolan** [comment]
> One thought - there is a key "Tracking" - would be worth making more unique to avoid conflict with other site generated keys. Maybe add userID?

That's a good point. I'll see what I can do about that in the near future. Thanks for the suggestion. :-)

**Comment by mikeruss1** [comment]
now the cache isnt in the frontend, if I want to delete it on Memcached how do I do it ?

delete the Tracking key?

**Comment by Maikuolan** [comment]
> delete the Tracking key?

Yep, that should do it. Also, sorry for not replying earlier. Not sure whether I just missed this before, or forgot to reply. '^.^ But yeah, just deleting the tracking key should do it.

**Comment by Maikuolan** [comment]
Ability to add prefixes to cache entries for an installation has now been implemented (b5f045203d874d590fc322a7cc55aa556b025985, 55fbe2d074f751e523b2f82275589444e0f21964). It should now be possible for distinct installations at the same server to avoid sharing their caches if need be. :-)
