### ISSUE TITLE
Request: Some kind of Paging when viewing LARGE log files using Fancy

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#252]
I use monthly logs for better statistics. But my monthly logs are large and put major stress to the server when i view them. 

It would be great if some kind of paging or Load More method could be implemented.

**Comment by mikeruss1** [comment]
why not try daily, review when you like, fast retrieval ?

**Comment by eurobank** [comment]
@mikeruss1 How can i have Stats for a month when using daily? In daily even IP Tracking fails to show the Ips, if on a different day.

Anyways, i'm not interested for a workaround, if something can be done in the future then ok. If not also ok by me.

** Even daily for me doesn't work very well since i monitor 7 sites with one CIDRAM. Some days i have thousands of events. **

**Comment by Maikuolan** [comment]
I've had some fresh ideas on how to achieve this recently. I'll experiment a little soon, and let you know what I can come up with. :-)

**Comment by 737simpilot** [comment]
So, caching can use PDO, can the logs? Then from your computer can remote into the database and Bob's your uncle - or aunt. :rofl: 

Edit-

I've been using this site since about circa 2007 and sometimes I find something I need. Here's some freeware. `https://www.snapfiles.com/downloadfind.php?st=database&action=s&ref=2&search=Find+it&lc=1`

Just food for thought.

**Comment by 737simpilot** [comment]
Just had a thought. Interface CIDRAM to fire off an email on certain parameters set via the auxiliary rules to use that for IFTTT. Now when something happens your Philips Hue lights blink in the house. LOL! 

https://en.wikipedia.org/wiki/IFTTT#Overview

Anyway... :rotating_light:

**Comment by Maikuolan** [comment]
> Now when something happens your Philips Hue lights blink in the house.

A pity we can't easily make it fire off in the house of the person sending the offending traffic instead. ¬‿¬

**Comment by Maikuolan** [comment]
> So, caching can use PDO, can the logs? Then from your computer can remote into the database and Bob's your uncle - or aunt. 🤣

In theory, yes. I don't currently have any easy/simple configuration switches, modules, or other code to do it though, and it'd require a bit of work and messing around, so.. I wouldn't really recommend it just yet (other than for those which enjoy additional work). Possibly in the future though.

(The reason it's theoretically possible: All logging functionality in CIDRAM ties closely into CIDRAM's events handler, and the events handler can be used to override any/all logging functionality in CIDRAM with whatever other code you want it to execute, generally, best implemented via custom modules).

**Comment by Maikuolan** [comment]
> to fire off an email on certain parameters set via the auxiliary rules

That's something that'll be possible in the near future. ;-)

**Comment by Maikuolan** [comment]
Work has started. Not finished yet though. I hope to get it finished very soon though.

**Comment by Maikuolan** [comment]
Delayed due to study commitments. Still happening though.

**Comment by Maikuolan** [comment]
Logs pagination has now been implemented. :-)

Let me know if there are any problems or if there's anything else that we need to address with this. AFAICT though, it should all be working correctly now.
