### ISSUE TITLE
pinterestcrawler.com blocked

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#253]
ID: 1627674322-395992-2954507118 »
Date/Time: Fri, 30 Jul 2021 22:45:22 +0300 »
IP Address: 54.236.1.11 »
Hostname: crawl-36ec010b.pinterestcrawler.com »
Signatures Count: 1 »
Signatures Reference: functions.php:L1580 »
Why Blocked: Fake Pinterest! »
User Agent: Mozilla/5.0 (compatible; Pinterestbot/1.0; +http://www.pinterest.com/bot.html) »

https://help.pinterest.com/en/business/article/pinterest-crawler

https://www.abuseipdb.com/check/54.236.1.11?page=2#report

@Maikuolan Can you pls check this? Doesn't seem fake to me.

**Comment by Maikuolan** [comment]
Looks legit.

Unfortunate that their [official, authoritative instructions for verifying Pinterestbot](https://help.pinterest.com/en-gb/business/article/pinterest-crawler) mention to check only again *__pinterest.com__*, with no mention at all about *__pinterestcrawler.com__*:

> ### Verify the Pinterest crawler
>
> 1. Use the host command to run a reverse DNS lookup on the IP address from your logs
> 2. Check the domain name in the response ends with pinterest.com
> 3. Use the host command to run a forward DNS lookup on the response retrieved from step 1
> 4. Check it is the same as the IP address from step 1

However, I've checked whois records for *__pinterestcrawler.com__*, and it appears to be owned by Pinterest (I see no evidence of anyone attempting to pull a fast one on anyone by registering fake domains or anything like that). It's probably just a case of Pinterest deciding to register the new domain for their bot to use, and someone at Pinterest forgetting to update their bot's documentation accordingly.

Anyway, I'll work on a fix for this now.

**Comment by Maikuolan** [comment]
Fixed. :-)
