### ISSUE TITLE
Pagination issue when Sort in descending order

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#255]
I use "Sort in descending order". When i tick pagination the sort is changed to Sort in ascending order.

**Comment by Maikuolan** [comment]
Thanks for pointing this out to me. :-)

I've noticed a few other minor, similar problems, too. I had a try at fixing them just now, but currently, at my machine, it's looking messier now than it'd looked before I'd started. 'x.x

I think, I'll get some sleep for the night and have another try in the morning.

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by eurobank** [comment]
It seems fixed !
