### ISSUE TITLE
Expired but not expired (IP Tracking).

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#258]
Please use this template when reporting bugs, problems, issues, etc.

### CIDRAM version used (if known, please also include the exact commit hash).

The very latest

### Signatures version (if known).

The very latest

### PHP version installed (`<?php echo phpversion(); ?>`).

PHP 7.3.x

---
## Issue
Please describe the problem here.

Shouldn't those have been expired and removed by now?

![Screenshot](https://user-images.githubusercontent.com/4467158/132895243-988ea1db-dfc8-42cd-a104-06fd4a016cf6.png)

**Comment by Maikuolan** [comment]
I think, these have most likely occurred as a result of signatures which invoke the "extended tracking options" feature of the tracking system, which is why they have the extended expiry date.

**Comment by Maikuolan** [comment]
Does seem like quite a large number, though. I wonder if someone has been attempting to attack the sites in question recently or something similar..?

**Comment by eurobank** [comment]
Keep in mind that those are from 7 sites, all in one Cidram installation. 

Also they are actually been "cleaned-up" after a few days.

**Comment by Maikuolan** [comment]
Ah, good point. Should be fine then, I imagine. :-)
