### ISSUE TITLE
More Bingbot false positives...this time due to an auxiliary rule

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#269]
Just recently started on the 12th. I've been getting nothing but Bingbot blocks from multiple Bingbot IPs.

>ID: 1637073446-644952-4931776840
Date/Time: Tue, 16 Nov 2021 07:37:26 -0700
IP Address: 207.46.13.3
Hostname: msnbot-207-46-13-3.search.msn.com
Query: t=167&start=20
Signatures Count: 1
Signatures Reference: functions.php:L2015
Why Blocked: The party you called is not available. Please check the number and try again. Error 102!
User Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
Reconstructed URI: 
CAPTCHA State: Enabled.

Here's the auxiliary rule in question:

```

The party you called is not available. Please check the number and try again. Error 102:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Mark for use with reCAPTCHA: true
 Block:
  If matches:
   Profile:
    - "*Commercial*"

```

The Bingbot bypass is turned on in the Configuration page. Not too sure what my course of action should be. I guess the auxiliary rules "bypass" the bypass?

Sorry about the edits. Trying to get the triple backticks to work right.

**Comment by 737simpilot** [comment]
test my markdown skills


```some code```

**Comment by 737simpilot** [comment]
test my markdown skills...


```The party you called is not available. Please check the number and try again. Error 102:
Method: "WinEx"
Logic: "Any"
Reason: "Use a real connection"
Mark for use with reCAPTCHA: true
Block:
If matches:
Profile:
- "*Commercial*"```

test my markdown skills....

**Comment by Maikuolan** [comment]
No problem. :-)

The reason for this false positive, is that the networks from which Bingbot sends it requests (e.g., Azure), are profiled as "commercial" networks by the signature files.

Try adding a "not equals" condition to that rule: Matching "verified identity" against "Bingbot".

So, after implementing this change, the rule should now look something like this:

```
The party you called is not available. Please check the number and try again. Error 102:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Mark for use with reCAPTCHA: true
 Block:
  If matches:
   Profile:
    - "*Commercial*"
  But not if matches:
   Verified:
    - "Bingbot"
```

Let me know how it goes. :-)

**Comment by 737simpilot** [comment]
Thanks. That makes sense to do then. I see DuckDuckGo is caught in my data hosting profile as well. Is the verified ID for DuckDuckGo simply `DuckDuckGo` ? Where is the list of verified IDs? And are the UAs or what ever verified via hostname resolution or something?

**Comment by Maikuolan** [comment]
> I see DuckDuckGo is caught in my data hosting profile as well. Is the verified ID for DuckDuckGo simply `DuckDuckGo` ?

For DuckDuckGo, the verified ID is `DuckDuckBot` (the name which DDG has chosen for their crawler).

> Where is the list of verified IDs?

Verified ID is populated by search engine and social media verification, upon successful verification. So, the full, complete range of potential verified ID values is the same as the names used for the things which search engine and social media verification supports (as per `verification.yaml`).

> And are the UAs or what ever verified via hostname resolution or something?

For those UAs specifically supported by search engine and social media verification, yes. For any others, nope. Because we're talking about a *verified* ID (as opposed to just an ID), something which isn't supported, or which fails to successfully verify, won't result in the field being populated. :-)

**Comment by 737simpilot** [comment]
Well, I tried but failed.

>ID: 1637231483-119812-4067795180
Date/Time: Thu, 18 Nov 2021 03:31:23 -0700
IP Address: 157.55.39.153
Hostname: msnbot-157-55-39-153.search.msn.com
Query: t=352
Signatures Count: 1
Signatures Reference: functions.php:L2016
Why Blocked: The party you called is not available. Please check the number and try again. Error 102!
User Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
Reconstructed URI: 
CAPTCHA State: Enabled.




```
The party you called is not available. Please check the number and try again. Error 102:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Mark for use with reCAPTCHA: true
 Block:
  If matches:
   Profile:
    - "*Commercial*"
  But not if matches:
   Verified:
    - "Bingbot"

```

**Comment by Maikuolan** [comment]
Hm.. Maybe I got something wrong..? Didn't test it myself, due to having been pretty busy recently. I'll test it out later tonight, to see whether I can figure this out a bit.

**Comment by Maikuolan** [comment]
Ah.. My bad. I figured out why my suggestion isn't working.

One of the bypasses I'd built into the default bypasses in the past, specifically for dealing with Bingbot false positives which were occurring at that time, happens to be setting a flag, which, when set, instructs CIDRAM to skip a small part of the search engine verification process (for just certain specific requests), which happens to also be the part responsible for populating the verified ID field. In other words.. a side-effect of an old fix is screwing with my suggested new fix here a bit. '^.^

I'll play around with it a bit more, to see whether I can either rescue this particular idea, or failing that, find some alternative ideas for resolving this false positive here. I'll reply with the results here (probably tomorrow afternoon at some point, I think; about to head to sleep and another likely long day at work tomorrow).

**Comment by 737simpilot** [comment]
No problem. Look forward to a fix.


![img](https://i.postimg.cc/ZKMd68M9/ezgif-com-gif-maker-13.gif)

**Comment by Maikuolan** [comment]
*Related: #242.*

Seeing as verified ID isn't being populated due to said prior fix.. Going back to what said fix itself is looking for, we should be able to replicate a similar effect for our intended purposes here with this auxiliary rule, I imagine.

Give this a try and let me know how it goes:
```YAML
The party you called is not available. Please check the number and try again. Error 102:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Mark for use with reCAPTCHA: true
 Block:
  If matches:
   Profile:
    - "*Commercial*"
  But not if matches:
   Hostname:
    - "msnbot*.search.msn.com"
   UALC:
    - "*bingpreview*"
    - "*bingbot*"
    - "*msnbot*"
```

(A little more long-winded than our previous attempt, I know. But, it should do the trick, hopefully).

**Comment by 737simpilot** [comment]
Thanks. I'll give this a try now and let you know how it goes.

**Comment by 737simpilot** [comment]
BTW - It doesn't much matter if the rule is long winded or not. My auxiliary YAML file is already 7 K. :laughing:

**Comment by 737simpilot** [comment]
After approximately four days, so far so good with the new rule in place. Thanks.

**Comment by 737simpilot** [comment]
Well, for some reason my VPN IP greylist is getting blocked. And the profile doesn't match either. The block is for commercial, my VPN IP is a data center. 


```

ID: 1638272827-075223-7160310622
Date/Time: Tue, 30 Nov 2021 04:47:07 -0700
IP Address: 173.248.148.82
Signatures Count: 1
Signatures Reference: functions.php:L2016
Why Blocked: The party you called is not available. Please check the number and try again. Error 102!
User Agent: 
Reconstructed URI: 

```


My VPN auxiliary rule:

```

VPN:
 Logic: "Any"
 Greylist:
  If matches:
   IPAddr:
    - "173.248.148.82"

```

I've tried a Bypass as well and this is what I get:


```

ID: 1638272751-128732-8733964875
Date/Time: Tue, 30 Nov 2021 04:45:51 -0700
IP Address: 173.248.148.82
Signatures Count: 2
Signatures Reference: 173.248.128.0/18, functions.php:L2016, functions.php:L2024, functions.php:L2016
Why Blocked: Cloud service ("Handy Networks", L9083:F5, [US]), The party you called is not available. Please check the number and try again. Error 101, VPN, The party you called is not available. Please check the number and try again. Error 102!
User Agent: 
Reconstructed URI: 

```

The Error 101 refers to the data center block.


```
The party you called is not available. Please check the number and try again. Error 101:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Mark for use with reCAPTCHA: true
 Mark for use with HCaptcha: true
 Block:
  If matches:
   Profile:
    - "*Data Center/Web Hosting/Transit*"
```


My current Error 102 looks like this:

```
The party you called is not available. Please check the number and try again. Error 102:
 Method: "WinEx"
 Logic: "Any"
 Reason: "Use a real connection"
 Forcibly disable reCAPTCHA: true
 Forcibly disable HCaptcha: true
 Block:
  If matches:
   Profile:
    - "*Commercial*"
  But not if matches:
   Hostname:
    - "msnbot*.search.msn.com"
   UALC:
    - "*bingpreview*"
    - "*bingbot*"
    - "*msnbot*"
```

**Comment by Maikuolan** [comment]
Which order are the rules being processed in? Does the greylist rule appear
before or after the 101/102 rules?

I'm thinking, if the greylist rule is being processed before the others, it
might still be working properly, but appearing to not be working properly,
since processing continues and the other subsequent rules are then causing
a block event to occur. If that's the case, it might simply be a matter of
rearranging the rules, to ensure that the greylist rule appears and is
being processed after the 101/102 rules, and not before.

(Responding via email, via my phone, while on the road to a job. So, not
able to test anything currently. Should be home again in a few hours
though. Will check in again at that time).

**Comment by 737simpilot** [comment]
Sorry for not getting back right away, been busy. I had wondered about the arrangement in times past, just never thought of it again till you mentioned it. I'll do that now and see what happens.

**Comment by 737simpilot** [comment]
BINGO! That's exactly what it was! Processing the greylisted VPN IP at the very bottom solved the issue. Thanks!


![img](https://i.postimg.cc/9F8MMG1j/ezgif-com-gif-maker-13.gif)

**Comment by Maikuolan** [comment]
No worries. Glad to hear that that solved it. :-)
