### ISSUE TITLE
Puzzled by this Block: 31.13.127.32

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#270]
IP Address: 31.13.127.32 »
Hostname: fwdproxy-cln-032.fbsv.net »
Signatures Count: 1 »
Signatures Reference: functions.php:L1596 »
Why Blocked: Fake Googlebot! »
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) 

This is Facebook Ips

https://www.abuseipdb.com/check/31.13.127.32

https://scamalytics.com/ip/31.13.127.32

and whitelisted at abuseipdb. But there are reports for Spoofing.

**Comment by Maikuolan** [comment]
Not sure why Facebook is pretending to be Googlebot, but that's what seems to be happening there.

**Comment by eurobank** [comment]
Me too.

**Comment by eurobank** [comment]
https://twitter.com/sergebezborodov/status/1305393013682827265

https://news.thewindowsclub.com/is-facebook-impersonating-googles-web-crawler-103057/

**Comment by Maikuolan** [comment]
Interesting article + tweet.

I would agree with some of the speculations and conclusions offered there, too. In particular, this makes a lot of sense IMO, as a likely motive for why Facebook seems to be doing this (albeit, no response from Facebook yet AFAICT, seeing as there's no "follow up" at that article yet):

> We can safely assume that all Facebook is doing here is eavesdropping on websites to figure out the tools and services they may be using.
>
> Once Facebook has this crucial data on websites, they can easily use it to their advantage by helping relevant advertisers boost their retargeting efforts. For example, once Facebook is aware of the SEO tools your website may be using, it can use this data to help competitor tools deliver targeted ads to you.

But yeah. In any case, definitely very unethical practice on Facebook's part, and I think, definitely constitutes as "unwanted traffic" (as per what CIDRAM tries to block), so I think we're good at our end, in terms of us blocking those kinds of requests.

I'll keep an eye on those tweets and that article, for any potential future updates. Will be interesting to see what other's find, any follow-ups, etc.

**Comment by 737simpilot** [comment]
This is just one more reason why I ditched Facebook so long ago. I don't trust that company one bit.

Props to CIDRAM for being able to block this kind of crap.
