### ISSUE TITLE
Hostname: crawl-66-249-66-66.googlebot.com

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#272]
ID: 1639248868-169598-4225248258 »
Date/Time: Sat, 11 Dec 2021 20:54:28 »
IP Address: 91.208.197.96 »
Hostname: crawl-66-249-66-66.googlebot.com »
Signatures Count: 1 »
Signatures Reference: 91.208.197.0/24 »
**Why Blocked: Attacks ("ALEXHOST SRL", L1726:F1, [MD])! »**
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:68.0) Gecko/20100101 Firefox/68.0 »

https://www.abuseipdb.com/check/91.208.197.96

Any explanations to that? I can't find any. How is this possible?

**Comment by eurobank** [comment]
I can't believe it, those guys have spoofed their DNS to return googlebot.

**Comment by Maikuolan** [comment]
> I can't believe it, those guys have spoofed their DNS to return googlebot.

Yep. There's a lot of sneaky stuff out there like that, unfortunately.
