### ISSUE TITLE
Turn logging off

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#273]
Could you consider an aux option to turn logging off. I thought supress output template did that but I think thats just the return to the GET?

not urgent.
thanks

**Comment by mikeruss1** [comment]
realised its in the main selection line

maybe it would be easier if it was an option like tracking off / on? Its normally a selection you want to make after choosing to block a certain type of transaction.

**Comment by Maikuolan** [comment]
> maybe it would be easier if it was an option like tracking off / on?

Do you mean at the auxiliary rules, or at the configuration? Or something else?

**Comment by mikeruss1** [comment]
yes, turn logging off could be an auxiliary option similar to turn tracking off

as it stands it works best with the blocks generated by other CIDRAM functions, if it was moved to be an auxiliary option it would work well with both

**Comment by Maikuolan** [comment]
Sorry for the delay. Have been caught up with other stuff. This should definitely be doable. I'll make a start on this later today. :-)

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by mikeruss1** [comment]
thank you !
