### ISSUE TITLE
First discussion!

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#282]
### Discussed in https://github.com/CIDRAM/CIDRAM/discussions/279

<div type='discussions-op-text'>

<sup>Originally posted by **Maikuolan** January 18, 2022</sup>
Let's test out GitHub's discussions feature, to confirm whether it'll work for our needs at the CIDRAM project. :-)</div>

create new issue

**Comment by Maikuolan** [comment]
Excellent. Seems to be working, :-)
