### ISSUE TITLE
Recaptcha problem

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#287]
This is in an error_log:

```
[2022-02-07T01:32:16-07:00] Error at classes/ReCaptcha.php:L217 (error code 8): "Undefined index: 123.456.789.0". Eep.. Something went wrong during "CAPTCHA".

```

IP is made up. Looks like IP addresses aren't logged with the captcha in the ipbypass.dat file. I use lock to IP.

**Comment by Maikuolan** [comment]
Oops.. Seems to be a bug newly introduced since 5e49678711ac945249403aec2b8351d9152d22bf.

Nice catch, and thanks for reporting this. Working on a fix right now. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)
