### ISSUE TITLE
Shows blocked but i'm not ?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#288]
Strange issue, that i was not aware until now.

It seems that while i see a log that i'm blocked (from TOR browser), i'm not. 

ID: 1645451087-385980-4956083526 »
Date/Time: Mon, 21 Feb 2022 15:44:47 »
IP Address: 91.219.237.21 »
Hostname: 178911033-dedicated.serverastra.com »
Query: post_id=228 »
Referrer: https://www. xxxx. tld /category/blog/ »
Signatures Count: 2 »
Signatures Reference: 91.219.236.0/22, tpbm_cidram.inc:L43 »
Why Blocked: Cloud service ("ServerAstra Kft", L26548:F0, [HU]), TOR Project exit node! »
User Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0 »
Reconstructed URI: https://www.xxxx.tld/wp-admin/admin-ajax.php?post_id=228 »

Any ideas?

Thanks

**Comment by eurobank** [comment]
Ok, it seems that the issue is due to Caching plugins THAT USE mod_rewrite mode. Both Fastest Cache and Litespeed cache do this issue.

While WP Super Cache (in PHP mode and not Advanced) works ok. Same with Comet Cache. PHP mode doesn't seem to cause any issues.

This is strange.

**Comment by Maikuolan** [comment]
Might be a problem similar to #52, maybe?

**Comment by eurobank** [comment]
Could be yeah. Not sure how Endurance cache works, but definitely Caching plugins using mod_rewrite is the cause.

PHP mode caching seems to work just fine. 

Still all those are for Wordpress. Just talking for Wordpress. 

The scary part is that you THINK everything is blocked but it is not. So you are UNAWARE !

**Comment by Maikuolan** [comment]
Yeah. Definitely something to be wary about there. :-/
