### ISSUE TITLE
[v3] Configuration matrixes/tables/etc

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#289]
I'm currently working on v3 (but haven't pushed any commits yet, because it's nowhere near stable enough to even call it beta just yet).

I'm currently exploring various ideas for changes to how the configuration works, and in particular, the idea of implementing configuration matrixes/tables (whatever you want to call it; still an early work in progress, in any case). This is in order to allow us to roll a whole bunch of different existing directives together, thus simplifying some parts of the configuration, as well as in order to provide some ability to configure CIDRAM in ways which aren't currently possible for v2 and earlier (which might also serve as a way to fulfil the requests of some of the currently open issues which have been open for a long time now).

Attached to this issue is a screenshot for that, to serve as a preview (albeit, one which possibly won't look exactly like the final product, given that I'm still working on it, and given that I'm asking here for thoughts/suggestions/etc, which may be taken into account, resulting in whatever changes).

Any thoughts/comments? Is the vertical text too difficult to read, or does it look okay to your eyes? Any ideas on ways to make it less ugly, more readable, more friendly to the eyes, etc? Suggestions? Let me know. :-)

![configPreview](https://user-images.githubusercontent.com/12571108/155720586-cd0aa0be-7ee4-4c64-9172-1dfb61dedceb.png)

(Note: This is really early, and there are things about it which I myself don't entirely like right now, which I'm not quite sure what I want to do about, but I'm stewing on, trying to come up with fresh ideas. So, if you say something bad about it, I won't be offended at all. Slowly improving on it as I can, when I can). :-)

**Comment by mikeruss1** [comment]
vertical doesnt work for me, its unusual and my immediate reaction is to find it difficult to take in, - sorry !

**Comment by Maikuolan** [comment]
All good! And, I've been feeling the same way, actually. Tried the idea out as a way to provide those grid-like checkboxes, but I might just give up on it being perfectly aligned like that and see what else I can do. Put feelers out for ideas, but the vertical is feeling pretty jarring to me, too.

**Comment by Maikuolan** [comment]
Updated preview (ditched the verticals and spaced things out a bit):

![updated](https://user-images.githubusercontent.com/12571108/155837465-8c2bdae2-814c-464e-9f98-02b01874724c.png)

Thoughts?

**Comment by mikeruss1** [comment]
well if it was me I would put the Entry like Script version on the left and tick boxes on the right, and maybe shorten the tick heading to Log entries and Access denied and extend the description at the top with more explanation. But yep I relate to the design OK.

**Comment by Maikuolan** [comment]
Committed and pushed. :-)

(I may still yet rework the aesthetics of it slightly between now and the eventual release, but seeing as the core of this issue has been dealt with now, I'll go ahead and close it).
