### ISSUE TITLE
module_bgpview.php – module_bgpview.yaml – Checksum error! File rejected!

### ISSUE THREAD

**Issue by ArfurDent** [CIDRAM/CIDRAM#292]
module_bgpview.php – module_bgpview.yaml – Checksum error! File rejected!
module_bgpview.php – Failed to install! +7.47 KB | -7.47 KB | 0.850

2022.53.500
Total Size: 8.79 KB
Dependencies:
PHP (>=7) – Satisfied.
CIDRAM Core (>=2.2) – Satisfied.
l10n/en (>=2021.139.519) – Satisfied.

I am unable to install the BGPview module for country blocking. 
The same issue appears on more than one install.

**Comment by Maikuolan** [comment]
I'll look into this now. Cheers.

**Comment by ArfurDent** [comment]
module_bgpview.php – Component successfully installed. +8.89 KB | -7.47 KB | 1.128

Thank you

**Comment by Maikuolan** [comment]
You're welcome. :-)
