### ISSUE TITLE
Tracking IPs - Infractions

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#297]
I have a request, maybe you will find it logical.

An IP gets an infraction and tracking is set for (let's say) a week. I would be usefull to count the duration of the week the moment the LAST infraction time/date. I mean if a tracked IP repeats the infraction again on 5th day, the days are again set to a week. 

Would it be possible in the future to have this change in the way infractions/tracking IPs are working?

**Comment by Maikuolan** [comment]
I'm currently looking at completely changing the way that infractions are counted for v3, so I should be able to look at other changes to infractions for all versions, too.

I think I'll finish working on my current changes first, before looking at other changes, to try to avoid confusing myself too much, but I'll come back to this at that point. :-)

**Comment by 737simpilot** [comment]
v3 looks pretty good thus far. Can't wait to try it.

**Comment by Maikuolan** [comment]
v3 has reached beta now, as of tonight, and that should be the standard default behaviour for IP tracking in v3 now. :-)

**Comment by Maikuolan** [comment]
I think this should be okay now. I'll go ahead and close the issue. :+1:

If anyone notices any problems, let me know.
