### ISSUE TITLE
CIDRs => Subnets (?)

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#30]
I'm wondering whether all instances of "CIDRs" mentioned in the documentation and elsewhere should be changed to "subnets", to reduce any possible ambiguity caused by the way the term is being used currently. What do you reckon?

Currently, it's being used both as the acronym (Classless Inter-Domain Routing), and as a slang/lazy way to refer to subnets expressed using CIDR notation. Main reason for the latter use thereof instead of simply using "subnets" was due to that subnets can be expressed in other ways, and the specific intended meaning was for subnets expressed using CIDR notation, as opposed to other forms of expression, but that said, it's not really a technically accurate or concise way to convey this meaning, and does potentially carry some ambiguity. Wondering whether to just keep things as they are or to change it.

**Comment by dev-101** [comment]
"CIDR notation" is correct term. As you said, subnet is a broader term, as they can be expressed in different ways.

You can mention early in the manual the definition and difference, then state what you mean from that point when you write simply 'CIDR', and leave things as they are.

**Comment by Maikuolan** [comment]
That's true, and good point. Explaining the terminology/usage early in the documentation should resolve the problem and remove ambiguity, too.

**Comment by DanielRuf** [comment]
I agree with @dev-101

**Comment by Maikuolan** [comment]
Cool. In that case, I think we've got a plan (just adding the explanation and leaving it all as is otherwise). :-)

I'll close this issue when the explanation has been committed.

**Comment by Maikuolan** [comment]
Explanation has now been added to the main English README (translations not done yet, but I'll eventually get to those over the next few days). :+1: 

Marking as *Implemented* and closing.
