### ISSUE TITLE
Progress towards v3 beta/stable.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#302]
Posting this issue regarding progress towards v3 beta/stable, to give everyone a clearer idea about exactly where we're at currently, and about what to expect.

Firstly, as a quick review of the terminology used here, insofar as at least how *I* define those terms in the context of CIDRAM and its major version life cycle:
- __Pre-Alpha__: Anything earlier than the "alpha" stage (generally, this would suggest that no code has been written yet, or at least, nothing is available yet, and could be regarded as an "ideas" stage of development). v3 has already moved beyond this stage.
- __Alpha__: Work has began, and at least *some* code has been written, but not to the extent of calling it "beta" just yet (although the distinction between "alpha" and "beta" doesn't depend on the *amount* of work done, but rather on the *implications* of that work insofar as *stability* is concerned). Both "alpha" and "beta" are open to potential backwards-incompatible changes. The difference between "alpha" and "beta" is in the *stability* of the work done thus far. If the work done is still "unstable", I would label it as "alpha" (v3 is currently here).
- __Beta__: Continuing on from there, if the work done is "stable", I would label it as "beta". Generally, it would continue as "beta" until the fist tagged release for the new major version occurs (the "general release"), thus no longer being in "beta" anymore.
- __Mature__: This generally means that the major version has been around for a while, and multiple minor versions/releases have occurred for that major version at the point in question (v1 and v2 are currently here).
- __Stable__: Implies that between individual commits, or between distinct states leading up from one version to the immediate next version, installations aren't expected to totally break, or undergo any major fundamental changes beyond what has already been planned.
- __Unstable__: And conversely.. If specific changes are planned which I absolutely know will break stuff between the states from before to after the changes in question, or if I can't yet rule out potential fundamental changes beyond what has already been planned, I would label it as "unstable". To clarify, "unstable" doesn't necessarily mean that code is broken, or that things don't work; We would try to avoid that as best as possible regardless, and we have tests/workflows/linting/etc to help us to avoid that situation.

Currently, v3 is available in an *alpha* state in the *v3* branch of the main CIDRAM repository (this repository). The available code, as it is currently, for the most part, *does work*. However, as suggested by the above term definitions, there are still some things I plan to do which would cause breaks between the before and after.

The most significant unstable changes I want to implement concern the updater. There are some syntactical changes I want to introduce to the updates metadata, and some significant changes I want to introduce to the way the updater works *under the hood* (although, for the most part, I don't plan to introduce many changes to the UI). I don't want to put a specific schedule to those changes, because I'm not sure exactly how long it'll take to complete those changes (although I hope to have it done sooner rather than later).

The moment I finish implementing all the changes I have planned for the updater is when I currently anticipate v3 transitioning from "alpha" to "beta", at which point, it should be safe to update from v2 to v3 for anyone wanting to give it a go prior to the "general release".

I haven't started any of the changes planned for the updater yet, because there are a few things I need to get done first, before I can start that. The most significant of those things is restructuring the file structure of CIDRAM as a whole, which is something I *have* started already, although haven't had time to finish yet.

Unfortunately, due to work and various other offline commitments, there has been delays, and I haven't progressed anywhere near as quickly as I would've liked, although progress is still happening regularly, and we're still moving forward, albeit being a little slower than I would've liked (which is also why I don't want to put a specific schedule on anything just yet, but yeah.. like I mentioned before, I hope to get everything finished sooner rather than later).

Worth mentioning too, that as part of that restructuring, and due to various technical considerations (I'll go into this in more depth a little later, but it's getting kind of late right now, and I need to finish writing this soon, so that I can get some sleep for the night and be able to get up early in the morning for work), I anticipate bundling all the modules and themes for CIDRAM directly in the main repository, to have them all be installed by default (still installable/uninstallable/updatable via the front-end updater as per usual and per previous major versions). This'll resolve some potential problems I foresee for certain kinds of implementations for v3 in the future, and will also allow me to have specific versions of modules and themes available for specific major versions of CIDRAM, without needing to worry too much about retaining backwards compatibility within current versions of modules and themes across multiple major versions of CIDRAM. Anyway.. I haven't done that yet, so that's something I'll still need to do as part of the restructuring, before I can call that done, and before being able to move onto the updater changes.

There's still be a number of other changes planned for after the changes planned for the updater, but the post-updater planned changes shouldn't affect stability at all, and are a little ways off just yet, so I'll post about those a little later.

**Comment by mikeruss1** [comment]
helpful - thank you.
would be very interesting to see the new features / changes / improvements expected when you are able.

**Comment by Maikuolan** [comment]
Still making progress on this, and still slowly working my way towards beta, but work has been kind of frustrating lately, with long shifts/days and not getting much time off at all, so everything is progressing much, much slower than I'd like.. Kind of feel like I could've already gotten everything finished by now if I had a good, solid week or so of free time to do it all. '-.- </Rant>

> I'll go into this in more depth a little later, but it's getting kind of late right now, and I need to finish writing this soon, so that I can get some sleep for the night and be able to get up early in the morning for work

Anyway, as promised (the details): I'm restructuring the components metadata a bit, to the extent that the old components metadata upstream won't be entirely compatible with v3's updater, so at the very least, I'll need to create a new, separate components metadata upstream for v3. That in mind, I have the leeway to rearrange which components will/won't be bundled with CIDRAM by default for v3. I'm thinking, too, that for those users which don't want to customise anything or don't want to touch the front-end updater at all, it might be nice to bundle in the more essential modules (e.g., the Bot User Agents module, but a few others, too) by default, to provide a stronger, more robust experience for those users with obligatorily vanilla installations (I'm giving a hard glance here to various external update mechanisms which tend to directly overwrite the entire installation without much/any nuance, e.g., WordPress).

There are also some modules that I anticipate becoming totally redundant, useless, and possibly incompatible with v3 (e.g., the Search Engines blocker module, due to implementing stronger controls and customisations for search engine verification for v3), so I'll keep those excluded from the newly to-be-created components metadata upstream, as well as obviously not bundling in those particular affected modules.

But, most significantly: There'll be some changes to how modules work for v3 that'll render it incompatible with a number of existing v1/v2 modules, particularly those which make use of their own L10N data or configuration directives via their own, accompanied YAML data. That in mind, and seeing as I want to continue supporting v1/v2 for a while longer yet (as well as their modules), and don't particularly want to start versioneering/branching the extras repository, the simple solution there would be to bundle those particular affected modules right into v3 from the get-go (thus allowing there to be different versions of the modules for different major version of CIDRAM, which also means I could have changes for a future v4, v5 or whatever else, since they'd all be in their own major version branches, and compatibility wouldn't be as much of an issue then).

For those with their own custom modules though: No need to worry. The more fundamental aspects of how modules work (e.g., the `$Trigger` and `$Bypass` closures, how to structure module signatures, module code, etc) won't change at all. Really, these changes which I intend, should only affect modules tied to a components metadata upstream (i.e., provided to the updates page for other CIDRAM users via a dedicated "remotes" URL, which as far as I'm aware, at this time, nobody other than myself is providing), and modules with attached YAML files for module-specific L10N data or module-specific configuration directives. So, nobody else needs to do anything in that regard. :-)

**Comment by mikeruss1** [comment]
useful update - do we assume v3 is mostly internals then rather than new user features?

**Comment by Maikuolan** [comment]
There'll definitely be new features, but almost all of those new features won't work properly without firstly restructuring all the internals, and those internal changes are definitely the main bulk of the changes I intend. :-)

I'll document and share some of them when I get some time (hopefully soon).

**Comment by Maikuolan** [comment]
Hooks will work a little differently than before, too; Just very slightly more complicated than they were for v2 and earlier (a few lines of code rather than just one), but also far, far more flexible than before, and I plan to make it possible to hide the entire vault completely outside the webroot without any problems (doing so further restricts access to CIDRAM down to specific entrypoints to be determined by the administrator, or whoever installs CIDRAM at the server in question), while having front-end access and such still being readily available in such cases.

**Comment by Maikuolan** [comment]
Hm.. v3 changes are starting to take a direction that I wasn't originally anticipating (not a bad thing, just a case of learning more about the best way to proceed the further along it comes). If I continue along the current trajectory, custom modules *may* need to be *slightly* modified in order to work correctly with v3. Anyway.. Still a ways off yet. I'll make sure that everyone knows what's going on before it exits beta, and what changes will be needed, applicable documentation, instructions, etc.

**Comment by Maikuolan** [comment]
Going to need to keep a few of them non-installed by default due to GDPR and other, similar privacy concerns, but they'll still be installable nonetheless (this'll mean multiple major-version versions of the modules available at the extras repository, but no worries; the updater will know which ones to fetch and install due to the distinct per-major-version metadata).

**Comment by Maikuolan** [comment]
Updater changes have been implemented, but there's a bunch of other stuff that broke as a result of various structural changes I've been making. Need to fix some of it first, before I can call the transition from alpha to beta. The module transitions from v2 to v3 haven't been finished yet either. Beta isn't far away now though. Maybe a day or two, it'll be ready. :-)

**Comment by Maikuolan** [comment]
Delayed again due to other commitments, but should still be soon all the same.

**Comment by Maikuolan** [comment]
Still a heap of work to get done before we can do a stable general release, but it should be at least stable enough now that it doesn't randomly crash, and should be good enough to at least begin early testing (and I'll definitely need some volunteers to do some early testing, I think; there've been so many changes that I have no doubt that there'll be bugs I haven't caught, unexpected edge-case problems popping up and so on, and it'll be good to catch as many as we can before any stable general release happens; testing at your local machine recommended over testing at production environments in case of the more severe unexpected problems, naturally). I haven't touched the installation/usage documentation yet since starting work on v3, and there've been some changes in that regard, so I'll need to update that so that users will at least know what to do to install v3 in the first place, but once that's done, I'll mark v3 as having finally exited alpha and entering beta. :-)

I'll reply back here again once the documentation has been updated accordingly.

**Comment by Maikuolan** [comment]
The documentation has been updated, and basic installation and usage instructions for v3 have been added (albeit not yet translated, because translations take a very long time, and I haven't had enough time to sort that out yet, so all in just English for now).

I haven't yet included any migration guide or related information regarding how to properly migrate v2 modules to the new v3 format without breaking anything; I'll get to that soon. No changes are required for standard signature files or auxiliary rules (nothing about the format for signature files or auxiliary rules has changed since v3; it's just modules that've changed a bit).

The main branch for the main repository here has been retargeted from v2 over to v3 just a moment ago.

Due to bundling most of the modules together with the main package by default as of v3, I'll need to update some of the legal documentation (the stuff in there that warns about sharing IPs with third-parties services, in order to be err on the side of caution regarding GDPR et al; it mentions there that the modules aren't installed by default, so I need to adjust that small part of the text accordingly; haven't gotten around to doing so yet though).

**Comment by mikeruss1** [comment]
so if I download v3 which I guess has the standard sigs, add my custom_mods,php and auxiliary.yaml it should fly? And the calls are in the docs?

**Comment by Maikuolan** [comment]
Regarding having the standard signatures and the calls being in the docs: Yep and yep. :-)

Regarding auxiliary.yaml: Also yep, but will need to rename it to auxiliary.yml for v3 (I've renamed most of the YAML files to have a `yml` extension for v3 in an attempt to bring CIDRAM more in line with what other popular PHP projects are doing at the moment; since most of them seem to be using `yml` for their own YAML files now; though, aside from dropping one letter in the filename, auxiliary rules should work exactly the same for v3 as they did for v2).

Regarding custom_mods.php: You'll need to make some adjustments to how the file is formatted in order for it to work for v3. I haven't documented the necessary changes, but plan to do that pretty soon.

For now, if you have any of these blocks of code in your module anywhere, get rid of them (needed for v2, but not needed anymore for v3, and likely to get in the way and cause problems as of v3 with how v3 operates):

```PHP
/** Prevents execution from outside of CIDRAM. */
if (!defined('CIDRAM') && !defined('CIDRAM-L')) {
    die('[CIDRAM] This should not be accessed directly.');
}
```

```PHP
    /** Inherit trigger closure (see functions.php). */
    $Trigger = $CIDRAM['Trigger'];
```

```PHP
    /** Inherit bypass closure (see functions.php). */
    $Bypass = $CIDRAM['Bypass'];
```

Then, try to do a quick mass *copy/replace all* with your text editor, replacing any instances of this:

```PHP
$Trigger(
```

With this:

```PHP
$this->trigger(
```

And this:

```PHP
$Bypass(
```

With this:

```PHP
$this->bypass(
```

And this:

```PHP
$CIDRAM['BlockInfo']
```

With this:

```PHP
$this->BlockInfo
```

And this:

```PHP
$CIDRAM['ModuleResCache'][$Module] = function () use (&$CIDRAM) {
```

With this:

```PHP
$this->CIDRAM['ModuleResCache'][$Module] = function () {
```

And this:

```PHP
$CIDRAM['ModuleResCache'][$Module]();
```

With this:

```PHP
$this->CIDRAM['ModuleResCache'][$Module]();
```

It's possible that some of those lines of code mightn't exist in your module. If they don't, it's not a problem. Not all modules have or need them. (But any modules which do have them, will need these changes).

After doing that, give the module a try. It *should* then work properly as expected. But, if it doesn't, let me know. (There might be something different about the module in question which needs special attention, or I might've missed something).

**Comment by mikeruss1** [comment]
loaded the front-end - these look like v8 php changes, running 8.1.2, so I guess I havent got my error reporting set like yours?
I have
error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING
I have delayed moving my site to v8 because all this error stuff is boring!!
tried it with 7.4.13 and its fine.

updates - Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in C:\wamp\www\cidram3\vault\CIDRAM\CIDRAM\Core.php on line 406
range tables - Deprecated: Optional parameter $KeyRoot declared before required parameter $Data is implicitly treated as a required parameter in C:\wamp\www\cidram3\vault\Maikuolan\Common\Matrix.php on line 199
Cache - Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in C:\wamp\www\cidram3\vault\CIDRAM\CIDRAM\FrontEndMethods.php on line 741

do you want to setup somewhere else to exchange beta info?

**Comment by mikeruss1** [comment]
ran it through protect, and its not blocking. I have my aux loaded which the front end is seeing OK. Including
User Agent = [^.{0,15}$]

OK tried a different UA block and that worked
looks like the regex isnt available?

checked the log on the successful block and it got caught by botua.php, so Aux might not be working at all?

**Comment by mikeruss1** [comment]
the logfile logfile20220616.log is in the vault but not in the Frontend logs page
IP Tracking - the clipboard is working, wasnt for me in v2 - but no link to the log page

**Comment by mikeruss1** [comment]
once you tell me you reckon its ready for limited production use, I will link it to a single relatively low use page. Thats the only way we are going to get a decent test I suspect. Once thats verified I can gradually increase it.

**Comment by mikeruss1** [comment]
the infractions count is doing something odd, starts with 1, another block goes to 3, next block goes to 7.
I changed the banned count from 10 to 4
changed the error_reporting and its fine. I usually want to detect deprecated because it will need changing soon.

**Comment by Maikuolan** [comment]
Might've made a typo in the way infractions are being calculated (since that's changed since v3). Taking a look at the code now.

**Comment by Maikuolan** [comment]
> checked the log on the successful block and it got caught by botua.php, so Aux might not be working at all?

Found the problem. Since changing where CIDRAM temporarily references block event information, the references to it for processing auxiliary rules have gone out of sync (forgot to update those references). Working on a fix now.

**Comment by mikeruss1** [comment]
just reviewing whats available in Updates, cant see the following ...
Google network, Bobuam, Baidu, HTTP version, Yandex, Baidu, TOR, China

**Comment by mikeruss1** [comment]
just to confirm have installed the front end in production outside the root, PHP 7.4. All working. Just to test it loads OK.

**Comment by Maikuolan** [comment]
> checked the log on the successful block and it got caught by botua.php, so Aux might not be working at all?

> Found the problem. Since changing where CIDRAM temporarily references block event information, the references to it for processing auxiliary rules have gone out of sync (forgot to update those references). Working on a fix now.

And fixed. :-)

> the infractions count is doing something odd, starts with 1, another block goes to 3, next block goes to 7.
> I changed the banned count from 10 to 4

> Might've made a typo in the way infractions are being calculated (since that's changed since v3). Taking a look at the code now.

Haven't progressed any further with that one yet. Will reply again once I do.

> just reviewing whats available in Updates, cant see the following ...

> Baidu ... Yandex

The Baidu and Yandex blocker modules should be redundant now due to the changes introduced to search engine verification since v3. It's possible now to outright block supported engines directly from the core configuration for search engine verification.

(That said, there are a few small bugs in there at the moment that I'm working out, but that shouldn't take long to resolve).

> China

The China and South Korea blocklists (formerly maintained by MacMathan) aren't supported anymore, but they're redundant anyway. Countries can be blocked outright now using the BGPView module instead. :-)

> HTTP version

Temporarily unavailable due to some issues at my end getting it to work as expected with v3. Should become available again soon.

> Google network, Bobuam ... TOR

Those were all maintained by MacMathan before, and had been taken offline a while ago. I'll have a chat with him soon to confirm whether he'd be okay with me forking those modules and importing them directly into the CIDRAM core. I might be able to take them up myself, but I'm not sure yet. I'll get back to you on those.

> just to confirm have installed the front end in production outside the root, PHP 7.4. All working. Just to test it loads OK.

Awesome; Good to hear. :-)

**Comment by Maikuolan** [comment]
> updates - Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in C:\wamp\www\cidram3\vault\CIDRAM\CIDRAM\Core.php on line 406
> range tables - Deprecated: Optional parameter $KeyRoot declared before required parameter $Data is implicitly treated as a required parameter in C:\wamp\www\cidram3\vault\Maikuolan\Common\Matrix.php on line 199
> Cache - Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in C:\wamp\www\cidram3\vault\CIDRAM\CIDRAM\FrontEndMethods.php on line 741

All three of those warnings should be fixed now (latest commits pushed just tonight).

> the logfile logfile20220616.log is in the vault but not in the Frontend logs page
> IP Tracking - the clipboard is working, wasnt for me in v2 - but no link to the log page

Cheers for letting me know. I haven't looked into those yet, but I'll do so shortly.

**Comment by mikeruss1** [comment]
updated - had to update the core and front end individually. Thought it was automatic?
common classes failed
Common Classes Package – Maikuolan/Common/Matrix.php – Checksum error! File rejected!
Common Classes Package – Failed to update! +0 bytes | -0 bytes | 0.058
verifies OK

**Comment by mikeruss1** [comment]
Aux OK - havent checked them all but its certainly doing stuff
php warnings fixed

**Comment by Maikuolan** [comment]
> > > the infractions count is doing something odd, starts with 1, another block goes to 3, next block goes to 7.
> > > I changed the banned count from 10 to 4
> >
> > Might've made a typo in the way infractions are being calculated (since that's changed since v3). Taking a look at the code now.
>
> Haven't progressed any further with that one yet. Will reply again once I do.

Fixed. :-)

**Comment by Maikuolan** [comment]
> updated - had to update the core and front end individually. Thought it was automatic? common classes failed Common Classes Package – Maikuolan/Common/Matrix.php – Checksum error! File rejected! Common Classes Package – Failed to update! +0 bytes | -0 bytes | 0.058 verifies OK

Supposed to be. I'll check it out shortly.

**Comment by mikeruss1** [comment]
The China and South Korea blocklists (formerly maintained by MacMathan) aren't supported anymore, but they're redundant anyway. Countries can be blocked outright now using the BGPView module instead. :-)
---------
is this adding an external lookup - trying to avoid these, my response time is close to Google's warning - dont really want to make it worse if possible

**Comment by Maikuolan** [comment]
> is this adding an external lookup - trying to avoid these, my response time is close to Google's warning - dont really want to make it worse if possible

Yep, it is. And fair call (I feel the same way for the websites that I manage, TBH). I'll investigate to see what else can be done.

**Comment by Maikuolan** [comment]
(I don't think that relying on external lookups would be GDPR-compliant, either. So, could be problematic for EU users if they had to rely on it. Not sure the best alternative solution offhandedly, due to heavy maintainability cost for manually pushing entire countries' worth of CIDRs to standard signature files. Might need to find a way to outsource this somehow, in a way that can be reimported back to CIDRAM to avoid the external lookups while also still avoiding the maintainability cost.. if that's possible).

**Comment by mikeruss1** [comment]
MacMathan may have had some sources?

**Comment by mikeruss1** [comment]
updating the core now also updates the front end. Common classes still failing though.

**Comment by mikeruss1** [comment]
havent done any testing for a while, are fixes still outstanding?

**Comment by Maikuolan** [comment]
Yep. :-)

Had been planning to push a number of commits tonight actually, but had to go shopping with a family member, time was wasted, and didn't get around to finishing the commits I was planning to push. Might still get it done before the end of the night.

Super close to dropping the alpha label in favour of beta though.

**Comment by mikeruss1** [comment]
Common Classes Package – Maikuolan/Common/Matrix.php – Checksum error! File rejected!
Common Classes Package – Failed to update! +0 bytes | -0 bytes | 0.208
IPv4 – Successfully deactivated.
IPv4 – signatures/ipv4.dat – Checksum error! File rejected!
IPv4 – Failed to update! +0 bytes | -0 bytes | 0.227
IPv4 – Successfully activated.
IPv4-ISPs – Successfully deactivated.
IPv4-ISPs – signatures/ipv4_isps.dat – Checksum error! File rejected!
IPv4-ISPs – Failed to update! +0 bytes | -0 bytes | 0.223
IPv4-ISPs – Successfully activated.
IPv6 – Successfully deactivated.
IPv6 – signatures/ipv6.dat – Checksum error! File rejected!
IPv6 – Failed to update! +0 bytes | -0 bytes | 0.223
IPv6 – Successfully activated.
IPv6-ISPs – Successfully deactivated.
IPv6-ISPs – signatures/ipv6_isps.dat – Checksum error! File rejected!
IPv6-ISPs – Failed to update! +0 bytes | -0 bytes | 0.213
IPv6-ISPs – Successfully activated.
Bypasses – Successfully deactivated.
Bypasses – imports/bypasses.yml – Checksum error! File rejected!
Bypasses – Failed to update! +0 bytes | -0 bytes | 0.530
Bypasses – Successfully activated.

also noticed the update signatures only option is gone?

item in tracking from a week or so ago, expiry has been reset to 6 days in the future,  tracktime is one week

**Comment by Maikuolan** [comment]
Yeah.. I think some changes I'd implemented to CIDRAM's internal file pathing is running afoul of the directory traversal protections I'd built into the updater in the past. Working on a fix now.

**Comment by mikeruss1** [comment]
signature only option is back, but still getting checksum error
is the code in commonclasses cos I cant update that either?

**Comment by Maikuolan** [comment]
> signature only option is back, but still getting checksum error is the code in commonclasses cos I cant update that either?

I don't think there's anything wrong with the common classes code, but I'll take a closer look at it in the morning. Probably due for another release there soon anyway, I think.

**Comment by Maikuolan** [comment]
(Taking a while due to needing to translate some new L10N data. Next commits will be up as soon as I'm done with this new L10N data).

**Comment by mikeruss1** [comment]
still problems with updates ... same with common classes

IPv4 – Successfully deactivated.
IPv4 – signatures/ipv4.dat – Checksum error! File rejected!
IPv4 – Failed to update! +0 bytes | -0 bytes | 0.220
IPv4 – Successfully activated.
IPv4-ISPs – Successfully deactivated.
IPv4-ISPs – signatures/ipv4_isps.dat – Checksum error! File rejected!
IPv4-ISPs – Failed to update! +0 bytes | -0 bytes | 0.210
IPv4-ISPs – Successfully activated.
IPv6 – Successfully deactivated.
IPv6 – signatures/ipv6.dat – Checksum error! File rejected!
IPv6 – Failed to update! +0 bytes | -0 bytes | 0.212
IPv6 – Successfully activated.
IPv6-ISPs – Successfully deactivated.
IPv6-ISPs – signatures/ipv6_isps.dat – Checksum error! File rejected!
IPv6-ISPs – Failed to update! +0 bytes | -0 bytes | 0.261
IPv6-ISPs – Successfully activated.
Bypasses – Successfully deactivated.
Bypasses – imports/bypasses.yml – Checksum error! File rejected!
Bypasses – Failed to update! +0 bytes | -0 bytes | 0.427
Bypasses – Successfully activated.

**Comment by Maikuolan** [comment]
Common classes package issues should be resolved now (tested a copy of my own). If it still doesn't update properly from today, the cause might be something lingering in there from an old commit from before the changes to the updater were finished (speculating). In such a case, a fresh install might be needed. But anyway.. Failures should be resolved now. :-)

Currently, the "track time" mechanism for IP tracking in v3 is bugged (i.e., the ability to enforce extended tracking times). I hope to fix that shortly, and as soon as that's done, I'll go ahead and tag v3 as beta proper (no longer alpha).

Still plenty that needs to be done before general release of course, but nothing that needs to happen in an alpha state.

**Comment by Maikuolan** [comment]
And done. :-)

https://github.com/CIDRAM/CIDRAM/releases/tag/v3.0.0-beta1
