### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#305]
I guess this is not normal?

27.76.246.139
	Banned – 4,000
	Wed, 10 May 2023 12:50:27
(11 months from now)

**Comment by 737simpilot** [comment]
A ban like that means it was probably doing so really bad things. It's CIDRAM's way of blocking it out right really quick with the 4,000 hit count. 

I think the serial log will shed light as to why it was banned. You should also be able to go into the Tracking section of the CIDRAM UI and at the top right chose the drop down to show the why reason.


Edit-

My research shows the IP address has remote desktop open to the world and looks to be compromised.

**Comment by eurobank** [comment]
Yes, i was referring to the 11 months from now ... why 11 months, the tracking is for 7 days.

**Comment by mikeruss1** [comment]
I think its an Instaban, my custom_mods.php has some default code which bans a particular event for a year with a trackcount of 1000. Something to do with an empty hostname

**Comment by eurobank** [comment]
oh, i didn't know that. Then it is ok.

**Comment by Maikuolan** [comment]
> My research shows the IP address has remote desktop open to the world and looks to be compromised.

Thanks for the heads up. :+1:

A month late now, I know, but I'll add that range to the default signature files for the next signatures update. :-)

**Comment by Maikuolan** [comment]
And yes, this is normal. (For now, at least). Possibly might change for v3 though, due to reworking IP tracking for v3. Anyway, I'll post about that later in some other issues. For now, I'll close this as resolved. :-)
