### ISSUE TITLE
Infractions

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#307]
infractions allowed is set at 4 .. this was logged ...

```
ID: 1652485226-795574-1381418135
Date/Time: Sat, 14 May 2022 00:40:26 +0100
IP Address: 86.187.225.20
IP Address (Resolved): -
Hostname: host86-187-225-20.range86-187.btcentralplus.com
Query: -
Referrer: https://www.xxx.co.uk/bb/qe_class.php
Signatures Count: 1
Signatures Reference: mcm_bobuam.php:L121
Why Blocked: Your browser is old and not secure. Please update. (F)!
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Rv:50.0) Gecko/20100101 Firefox/50.0
Reconstructed URI: https://wwwxxx.co.uk/bb/qe_class.php
CAPTCHA State: Enabled.
```

the following 3 all got logged and blocked OK
the fifth also got logged and blocked - I would expect this to just get a 403 with no log ?
the sixth got a 200 ! - have checked the log and see no difference, same IP and UA
the 7th got a correct straight 403 with no log

the only thing I see is the middle 3 all came within the same second, so maybe the infractions count isnt getting updated. The number of blocks in the tracking count is 4, so CIDRAM thinks it has done the right thing. Even though the log has 5 blocks. But the 6th one getting a 200 is also very odd?

**Comment by mikeruss1** [comment]
I could change things around a bit ... I have my own rate limiting code which happens after the CIDRAM call. I could move it to before which would reduce the likelihood of this happening, assuming that a peak of GETS over a short time is the problem?
It would also make sense as my code is very brief, and would save unnecessary calls of CIDRAM.

**Comment by Maikuolan** [comment]
Not sure what's going on there TBH.

Infractions will be calculated a little differently in v3 than they were in <=v2 though, so maybe that'll help out a bit once it reaches beta in the near future.

I'll investigate a bit further into this issue when I've got a moment though.

**Comment by mikeruss1** [comment]
its certainly odd - found another instance where there were 4 instances over a a few seconds, in tracking it is reporting banned with 3 infractions. The site log gives 4 x 403, CIDRAM log gives 3 blocks. The maximum number of infractions is set at 4. All the site logs look like they received an error report rather than a straight 403 with no bytes sent. Will look out for similar events, see if there is a pattern.

**Comment by Maikuolan** [comment]
v3 has reached beta now. If possible, when you've got a moment, let me know whether the problem persists for v3 or whether it seems to have disappeared. Cheers. :-)

**Comment by mikeruss1** [comment]
the issue needs traffic volume to find, unlikely to trip in beta I suspect? Needs a lot of variety and short term peaks maybe?

**Comment by Maikuolan** [comment]
True, that makes sense. I guess, we can just keep this issue on hold for now. :-)

**Comment by Maikuolan** [comment]
*Closing as fixed.*
