### ISSUE TITLE
Changed IP Tracking number and now white page of death

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#309]
I changed the default IP tracking from 10 to something else, tried to save and got a blank page. After that nothing works, i can't see anything.

Any ideas?

Thanks

**Comment by eurobank** [comment]
Ok it seems what CIDRAM doesn't like me to change the infraction # for some reason. 

Restored the yesterday's backup and tried again, same issue. I tried to MANUALLY edit the .ini, and ... still the same issue.

What worked (and the developer will understand what it means), i restored my backup, CLEARED ALL CACHES, and then i was able to change and save what ever i wanted.

**Comment by Maikuolan** [comment]
I haven't yet been able to replicate the problem at my end. Currently still investigating.

**Comment by eurobank** [comment]
Try to set it to 50 and after a while to change it.

**Comment by eurobank** [comment]
seems fixed or no happening again.
