### ISSUE TITLE
What to enter in config.ini ipaddr variable for Cloudflare?

### ISSUE THREAD

**Issue by slrslr** [CIDRAM/CIDRAM#31]
Hello, in /vault/config.ini is variable "ipaddr":
ipaddr='REMOTE_ADDR'

and i have my site behind Cloudflare. Please what to enter into this variable?
It is not described in the config.ini

Is it: HTTP_CF_CONNECTING_IP
?

**Comment by DanielRuf** [comment]
> Is it: HTTP_CF_CONNECTING_IP

Right
