### ISSUE TITLE
Amazonbot

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#317]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot

officially a search engine which can be DNS traced ... https://developer.amazon.com/support/amazonbot

the ones I got were from standard AWS

**Comment by Maikuolan** [comment]
Nice find! Cheers. :-)

I've added in the new verification data tonight at my end locally, but I haven't been able to find any actual real IPs used by Amazonbot yet, which I'll need to test against the new verification data to make sure it's working properly. I tried a handful of arbitrary AWS ranges, but none of the ones I tried seem to resolve back to `*.crawl.amazonbot.amazon` (the hostname that Amazonbot requests are supposed to resolve back to).

Do you still have those records handy by any chance, to let me know which specific IPs you'd encountered from Amazonbot? Cheers.

**Comment by mikeruss1** [comment]
most were AWS - the only amazonbot one I can find was 3.224.220.101

**Comment by Maikuolan** [comment]
> most were AWS - the only amazonbot one I can find was 3.224.220.101

Cheers. Testing now. :+1:

**Comment by Maikuolan** [comment]
Nice.. It works. 💯
