### ISSUE TITLE
[REQUEST] Enable - Disable Aux rules  

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#318]
It would be VERY usefull to be able to disable/enable one-per-one the aux rules. Sometimes you need to disable one the them for a while and you must delete it and (when finished testing) create it again.

thanks

**Comment by Maikuolan** [comment]
Good idea. :-)

I'll try to implement something for that soon.

**Comment by Maikuolan** [comment]
Done. :-)
