### ISSUE TITLE
Blank page after upgrading

### ISSUE THREAD

**Issue by gizmecano** [CIDRAM/CIDRAM#324]
I recently experienced a case quite similar to #309 (_white page of death_), but after trying to update CIDRAM version 1.21.0 to the [stable version 1.22.0](https://github.com/CIDRAM/CIDRAM/releases/tag/v1.22.0). 

Luckily I succeeded to reinstall my previous setup using my version control copy, but I now have some hesitation to try again.

Moreover, the updates page `cidram/loader.php?cidram-page=updates` does not allow to select a particular version (stable for example) but seems to directly display the latest version published (`1.22.1-DEV+22186000` at the time of writing).

**Comment by Maikuolan** [comment]
I'll look into this more closely tonight.

**Comment by Maikuolan** [comment]
(Haven't replicated the problem yet, but also haven't yet dug as deeply as I'd like. Bit of a busy week with numerous things to get done. Will reply back when I'm able to get a bit more done on this issue).

**Comment by gizmecano** [comment]
> (...) Will reply back when I'm able to get a bit more done on this issue.

You don't need to apologize: I know what open source development entails... 😉

**Comment by gizmecano** [comment]
Right now, I'm wondering if this issue could be caused by incompatibility between different versions of the modules currently enabled on the installation. Guess I'll have to do careful step-by-step updates in the near future.

**Comment by Maikuolan** [comment]
> Right now, I'm wondering if this issue could be caused by incompatibility between different versions of the modules currently enabled on the installation. Guess I'll have to do careful step-by-step updates in the near future.

After reading your reply, I had the thought to double-check backwards-compatibility between the modules and the various PHP versions they're meant to be compatible with, and.. I think I've found the problem. Looking into a possible fix now. I'll reply back shortly. Cheers.

**Comment by Maikuolan** [comment]
Okay.. The backwards-compatibility issue should be fixed now. :-)

**Comment by gizmecano** [comment]
First of all, I wanted to thank you for your particularly responsive support over the past few days.

👍

However, as we are now close to the middle of summer here, I don't have enough availability to proceed more right now: I will carry out scrupulous updates and exhaustive verifications during the second half of next month and, depending on potential feedback from impacted visitors, I will close the open issues accordingly.

**Comment by Maikuolan** [comment]
Sounds good, and no rush. :+1:

**Comment by gizmecano** [comment]
I have just updated to the new version 1.22.1, along with all active components installed step by step.

A priori, everything seems working well and the issue concerning  the blank page after upgrading did not happen again.

As a result, I'm closing this issue which seems to have been resolved by the changes made in the module file.

Thanks.

**Comment by Maikuolan** [comment]
Glad to hear that all is well now. :-)

**Comment by DoctorDred** [comment]
Hello, unfortunately today after update I have blank pages on:
Accounts
Auxiliary Rules
Cache Data
Configuration
File Manager
Signature File Fixer
IP Testing
IP Tracking
Range Tables
Rate Limiting
Sections List
Statistics
Updates
Backup
Logs
Range

Home page is working.

![Screenshot_20231225-123705_Chrome~2](https://github.com/CIDRAM/CIDRAM/assets/137677019/dd0c49bd-de89-43f0-8bfd-3761f1a04778)
![Screenshot_20231225-123710_Chrome~2](https://github.com/CIDRAM/CIDRAM/assets/137677019/f40166b4-4505-4dc1-bc98-afae438cc6a2)

**Comment by Maikuolan** [comment]
Hi @DoctorDred,

May I confirm, within the file structure for your installation (typically under the `vault` directory), whether there exists any `pages` directory? If so, does it contain any files, or is it empty?

**Comment by DoctorDred** [comment]
> Hi @Maikuolan,
> 
There is catalog l10n and inside core, frontend folders, in those are plenty of .yml files .
![Screenshot_2023-12-27-09-56-23-732_com android chrome~2](https://github.com/CIDRAM/CIDRAM/assets/137677019/40bb9492-e5b4-4a45-9127-ae88a60c0098)
