### ISSUE TITLE
Question: Display some anon Public Stats

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#325]
We monitor now 6 websites with one CIDRAM instance. We have some 1000-2000 logs daily. I would like if possible to share some stats, anonymized (domains, hide some digits from IPs or whatever) publicly.

Any ideas how to do that?

Thanks

**Comment by Maikuolan** [comment]
How to do it right now? I'm not sure. I don't think it's possible with the current features and functionality available to CIDRAM. It sounds like a great idea though. I'll investigate what changes are needed to make this possible. :-)

**Comment by eurobank** [comment]
I'm trying to find some Wordpres plugin that could read and maybe filter and display some text file, but i haven't found any.

Just an idea.
