### ISSUE TITLE
Some (visual?) in latest version

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#326]
Trying to edit something in file manager:
![2022-07-14 00_08_51-CIDRAM – File Manager – ipv4_custom dat — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/178836602-9777ea33-6628-4f44-8b48-f2a18f7fbb2d.png)

**Comment by Maikuolan** [comment]
Thanks for spotting this. Should be fixed now. :-)
