### ISSUE TITLE
Bus factor, third-party components, and future major version upgrades (e.g., v4).

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#329]
### Bus factor, third-party components, and future major version upgrades (e.g., v4).

[Wikipedia](https://en.wikipedia.org/wiki/Bus_factor) describes "bus factor" as:
> The bus factor is a measurement of the [risk](https://en.wikipedia.org/wiki/Risk) resulting from information and capabilities not being shared among team members, derived from the phrase "in case they get hit by a bus". It is also known as the bus problem, lottery factor, truck factor,[[1]](https://en.wikipedia.org/wiki/Bus_factor#cite_note-1) beer truck factor, bus/truck number, or lorry factor.

Mind you, I don't plan to go anywhere, nor to run in front of any vehicles in the foreseeable future, but I mention about "bus factor", because it has relevance to the issue at hand.

Anyone want to start producing their own third-party components for distribution among other CIDRAM users? Anyone have some useful modules or blocklists they've created, which they want to share publicly with others (similar to how MacMathan provided his own blocklists and modules to CIDRAM users via the updates page in the past)? That's also relevant to the issue at hand.

The method we'll eventually be using to safely upgrade from v3 to v4 in the future (mind you, that's a fair while into the future I imagine, seeing as v3 has only just now hit beta), is also relevant to the issue at hand.

The issue at hand: As of v3, the URLs for the components metadata upstream isn't hardcoded into the metadata files themselves anymore. For v2 and earlier, metadata files held a "remote" entry, which pointed to the updater where it can find the latest versions of that metadata, in order to be able to determine when components could be updated, which new components were available, etc. But, as of v3, the URLs for the components metadata upstream is no longer determined by a "remotes" *entry*, but instead by a "remotes" *configuration directive* (i.e., the source is now configurable). For v2 and earlier, there were also multiple such files, to separate themes from modules, modules from signature files and so on. As of v3, there's no longer multiple such files, there instead being only one such file: The "installed.yml" file, to indicate which components are currently installed, their versions, and the metadata associated with those installed versions (but nothing more).

![remotes](https://user-images.githubusercontent.com/12571108/179155360-ba9e71d1-7384-457b-9111-9b46da3f35f7.png)

Making this change to the way the updater works, and to how the updater determines which URLs to use to fetch the components metadata upstream, means that anyone wanting to have their own third-party components become available for other CIDRAM users to install/activate/update/etc via the updater, no longer needs to go through me, or through the main repository here at GitHub for that matter, in order to do so. All they'd need to do is properly manage their own upstream metadata file somewhere, and then have any interested users add the public URL to that file to their remotes directive. :-)

(Permission is also not necessary to do this, and anyone is welcome to do this. However, if wanting to do this, be aware that I'm not responsible for providing support for third-party components which I have no control over, so if wanting to provide support to users along with your own provided components, you'll need to take care of that yourself).

It also means that, should CIDRAM ever become a victim to its "bus factor", as long as another user is willing to take over and pick up the slack somewhere at some point, seamlessly switching over their updated version of CIDRAM, or to an updated repository location for future updates, should be as simple as updating the content of the remotes directive so as to point to the new URLs.

It also means that when future major version upgrades become available, as long as those future major version upgrades are compatible with the updater, it should be possible to upgrade to the new major versions by simply updating the URLs at the remotes directive so as to point to the branch containing the new major version (though unfortunately, that won't be a possible strategy for upgrading to v3 from an earlier major version, seeing as that directive was only introduced to CIDRAM since v3 anyway, and v2's updater is not compatible with v3 components metadata, meaning a fresh installation will be necessary to upgrade to v3 from v2 or earlier).

**Comment by mikeruss1** [comment]
how do we limit the potential security issues, it might be an open door to put code onto servers?

**Comment by Maikuolan** [comment]
If URLs from untrusted sources are added to the remotes directive, that would, in deed, be a security risk, because if those URLs point to metadata files which contain malicious instructions, or provide components containing malicious code, and the user then decides to install one of those components which contain malicious code, that would result in that malicious code ending up on the server in question. However, the remotes directive is never updated automatically, and URLs can only end up there if they've been added by the user (at least, from CIDRAM's perspective), and such potentially malicious metadata files won't ever be processed unless they can be found by the updater in the first place, and can't be found unless they've been added to the remotes directive.

CIDRAM does already implement some basic countermeasures against dangerous code being *accidentally* introduced via the updater (e.g., the built-in sanity checks, the way it rejects instructions to traverse files outside the vault when updating, and rejects files which don't conform to some basic expectations regarding magic number, checksums, etc), but those countermeasures won't hold up in the slightest against something being *intentionally* introduced to the updater from the upstream by the user's invitation (whether knowingly or otherwise), given that most countermeasures, once properly understood, could be worked around by someone sufficiently motivated.

Therefore, I would *strongly* recommend to add URLs to the remotes directive, *only* if the person providing that URL is trusted, the components they're providing are trusted, and if it's possible to vet both the person and their components against such potential security issues. (Let's say, for example, if someone accuses me of directly including something malicious at the main repository here. To defend myself against that accusation, because everything is open, I can literally just ask them to point out where said malicious thing is, and when they can't do that, I can can tell them, it's probably because it isn't there. On the other hand, an upstream which isn't open can't be easily checked like that. Similarly, even if it's open, but the platform hosting it isn't trustworthy, or could be easily compromised or manipulated, there would be a degree of risk there).

In other words.. Although I definitely think this feature is the best way to go moving forward, and definitely encourage those interested in sharing their components to make use of it, I would simultaneously discourage abusing the feature, and advise taking a level of caution for situations where, in the future, someone says, *"Check out this amazing cool stuff I've written! Here's the URL for the updater! Go use it now!"* Particularly if it's someone random or unknown, a user you've never heard of before, know nothing about, or.. someone you do know, but know has done questionable things in the past, isn't entirely trustworthy, etc. Better yet: In this context, assume everyone is untrustworthy, until you know or have been shown otherwise.

In short: The strongest safeguard against said security issues would be to approach using said feature always in consideration of the degrees of trust (or lack thereof) between all parties involved (e.g., between the person controlling the upstream and the person controlling the installation at the downstream).

**Comment by Maikuolan** [comment]
The other thing it could be potentially useful for, I forgot to mention earlier: If someone runs multiple different installations at multiple different servers, and wants to be able to replicate their custom modules or signature files across all installations, across all servers, but doesn't want to have to upload everything to all of them all the time to keep it all synced up, they could just update a single upstream with their latest changes, link it to all installations, and then all they'd need to do is run the usual update process from the updater at each installation. That last step could also be dropped in some cases by utilising Cronable or similar. :-)

(A less useful point for normal circumstances though, where users are operating just one or two installations).

**Comment by mikeruss1** [comment]
I have to say it concerns me, at installation I would have no control of the code included at that point, or how it might be changed at some point in the future. The remote itself could be broken into and corrupted by an unknown 3rd party. 

I really think we should see if these risks can be limited. Denying external references would help, maybe accreditation also?

**Comment by Maikuolan** [comment]
> Denying external references would help, maybe accreditation also?

That could definitely help. Though, seeing as nobody has chosen to make use of this feature just yet, aside from CIDRAM's own repositories, there wouldn't be anything *to* accredit for the moment, at least. Might nonetheless still be worth considering such a mechanism though, and should be doable, I imagine. (Though, it might be a good idea too, to make such a feature optional, something that could be enabled/disabled, otherwise we might, in theory, still eventually run up against the problem of enforced centralisation via accreditation for in the event that the project gets continued elsewhere, maybe due to bus factor, or due to something unexpected happening at GitHub, or whatever else).

Important to remember as well though that any measure implemented is only reliable up until the point that the server becomes compromised, and at that point, nothing there can really be trusted anymore. E.g., if the thing doing the corrupting is something else at the server, unrelated to CIDRAM entirely, say.. if the server had already been backdoored, shelled, had FTP passwords stolen, etc, prior to CIDRAM being installed in the first place, or by some unrelated means (maybe a vulnerable CMS used at the same website, or maybe as a result of the guy which maintains the hardware being a little dodgy or something; who knows; any hypothetical will do), and the attacker then decides to take advantage of that, at that point, control has already been lost, and if someone can corrupt the configuration file, they could corrupt whatever data source is used for accreditation too, or if they aren't concerned about being subtle or about being caught, they might opt instead to just delete everything from the server outright.

In the case of stuff being deleted outright.. not much we can do there aside from ensuring that the server doesn't become compromised in the first place, and ensuring that we maintain regular backups of everything, so that we're able to restore it all in the event that it becomes compromised and/or deleted.

In the case of an attacker trying to be more subtle though (e.g., not deleting everything, but instead hiding shells and backdoors around the place, maybe compromising a configuration file or two here and there to provide a means to regain access in case aforementioned shells and backdoors become discovered and consequently removed).. The reason I mention above about any measures only being reliable up until the point that the server becomes compromised, is to suggest we need to be careful about such measures providing a false sense of security for in the event of such more subtle approaches by attackers.

What if, for example, an attacker figures out how the accreditation mechanism works and changes it as so that their own source is treated as accredited when it shouldn't be? Or more simply, just disables the mechanism entirely? If they have control, they could choose to do that in order to enforce a more "subtle" attack. Of course, that's not to suggest there's anything wrong with the idea of accreditation or of blocking external references. Those are both still good ideas. But, literally every possible idea/solution/etc would suffer from that problem. To abate that problem, we just need to make sure nothing is compromised in the first place, thus retaining control.

I think, preventing the "false sense of security" problem *entirely* is probably impossible, seeing as everyone will feel and interpret things however they want to feel or interpret them, and it isn't always easy to judge *exactly* where the line should be between the two extremes of telling someone, "you're not being conscious enough about your security and the potential risks of X/Y/Z, and you should be doing A/B/C", versus "you're being overly conscious and paranoid about the security of X/Y/Z, and you don't need to be doing A/B/C". But, while we're thinking about implementing something to improve the security for remotes and such, it might be worth doing something to help avoid a false sense of security too.

Maybe I should have it that the remotes are actually visibly stated in plain-text at the updates page? (Although they're already visible and configurable at the configuration page, but it's not like anyone wants to need to constantly check against the configuration page before updating anything every time an update is available, which would be a bit annoying to deal with after a while). Even if the remotes are changed by a third-party, as long as you can see what they are, and remember what they *should* be at any given time, then by comparing what you see against what you know, it should become known at that point whether something has been changed. That *might* help a bit. (Though, even that is no exception to my earlier comment about every idea/solution being subject to the earlier mentioned problem, seeing as an attacker, if they have control, could just change whatever mechanism displays that text, to always display the original text, without needing to pull anything from the configuration, while still changing the configuration itself). Anyway.. it's an idea.

Open to hear other thoughts and ideas too.
