### ISSUE TITLE
Front end scroll bar

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#335]
I know this is very very minor !
v 2.9.1
if you log in, open Page Tracking, then logs, then back arrow in the browser, the tracking page doesnt have a scrollbar

some sequences seem to retain the scroll bar
using Chrome, works OK in Firefox

**Comment by Maikuolan** [comment]
I'll take a look at that soon. :-)

**Comment by Maikuolan** [comment]
I wonder whether it might be worth defining scrollbars explicitly into the CSS, to tell the browser which pages should have scrollbars, instead of allowing the browser to determine it automatically (as is currently the case)?

**Comment by mikeruss1** [comment]
Generally I specify scroll bars or not explicitly. It's a while but I thought it was in the js. I think back arrow refreshes the page from the cache, so it's all very odd.

**Comment by mikeruss1** [comment]
Research shows various issues with chrome and scrollbars, suggest forget it?

**Comment by Maikuolan** [comment]
Yeah.. I think I'll leave this as a "Won't Fix", seeing as the problem seems to be more a browser issue than a CIDRAM issue.
