### ISSUE TITLE
DuckDuckbot

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#336]
getting a lot of these ... as you see there is a quote around the UA which is probably causing the problem. The IP is on the valid list. Have written to them but got nothing back. Maybe we should let it through?

ID: 1660640076-210337-0796181815 »
Date/Time: Tue, 16 Aug 2022 09:54:36 +0100 »
IP Address: 40.76.162.191 »
IP Address (Resolved): - »
Hostname: 40.76.162.191 »
Query: - »
Referrer: - »
Signatures Count: 1 »
Signatures Reference: mcm_bobuam.php:L111 »
Why Blocked: Suspected bot detected!! »
User Agent: 'DuckDuckBot-Https/1.1; (+https://duckduckgo.com/duckduckbot)' »
Reconstructed URI: https://www.xxx.uk/ »
CAPTCHA State: Disabled. »

**Comment by Maikuolan** [comment]
Yeah.. Looks like a false positive to me. Might need to write an auxiliary rule to bypass it though, seeing as BOBUAM isn't being updated anymore.

**Comment by Maikuolan** [comment]
(At least, for now. I still need to message MacMathan about his thoughts regarding the v3 migration, but haven't had time to sort that out yet due to being preoccupied. My bad. I'll message him soon).

**Comment by Maikuolan** [comment]
v3-compatible BOBUAM version committed, and the particular false positive mentioned at this issue has been fixed. :-)
