### ISSUE TITLE
Telegram Crawler wrong block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#341]
ID: 1664551134-150296-2045904264 »

Date/Time: Fri, 30 Sep 2022 18:18:54 »

IP Address: 149.154.161.212 »

Hostname: crawler.telegram.org »

Signatures Count: 1 »

Signatures Reference: functions.php:L1026 »

Why Blocked: Fake Twitterbot! »

User Agent: TelegramBot (like TwitterBot) »

**Comment by Maikuolan** [comment]
Thanks for spotting and reporting this. :-)

Working on a fix now.

**Comment by Maikuolan** [comment]
Done. :-)

(I do wonder though whether it might be worth including verification for TelegramBot, too? Currently, CIDRAM doesn't verify requests from Telegram. Not sure how much value there'd be, seeing as I've never seen a fake TelegramBot request before anyway, but it shouldn't be too difficult to implement, either).

**Comment by eurobank** [comment]
I didn't even know there was a Telegram bot :)
