### ISSUE TITLE
Google Bot Blocked !

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#342]
This is NOT any nested attack but a legit url of mine.

ID: 1664597686-282044-4920179765 »
Date/Time: Sat, 01 Oct 2022 07:14:46 »
IP Address: 66.249.69.253 »
Hostname: crawl-66-249-69-253.googlebot.com »
Query: page=search&sCategory=%2525ce%252595%2525cf%252581%2525ce%2525b3%2525ce%2525b1%2525cf%252583%2525ce%2525af%2525ce%2525b1-%2525cf%252583%2525cf%252584%2525ce%2525bf-%2525ce%2525a3%2525cf%252580%2525ce%2525af%2525cf%252584%2525ce%2525b9&sOrder=dt_pub_date&iOrderType=desc »
Signatures Count: 1 »
Signatures Reference: module_extras.php:L132 »
Why Blocked: Nesting attack! »
User Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »
Reconstructed URI: https: // www . mysite . com/index.php?page=search&sCategory=%2525ce%252595%2525cf%252581%2525ce%2525b3%2525ce%2525b1%2525cf%252583%2525ce%2525af%2525ce%2525b1-%2525cf%252583%2525cf%252584%2525ce%2525bf-%2525ce%2525a3%2525cf%252580%2525ce%2525af%2525cf%252584%2525ce%2525b9&sOrder=dt_pub_date&iOrderType=desc »

**Comment by Maikuolan** [comment]
Should be fixed now. :-)

**Comment by eurobank** [comment]
Microsoft Bot also Blocked, same reason

ID: 1664699499-897643-8847568393 »
Date/Time: Sun, 02 Oct 2022 11:31:39 »
IP Address: 157.55.39.130 »
Hostname: msnbot-157-55-39-130.search.msn.com »
Query: page=search&sCategory=%2525ce%252595%2525ce%2525be%2525ce%2525bf%2525cf%252580%2525ce%2525bb%2525ce%2525b9%2525cf%252583%2525ce%2525bc%2525cf%25258c%2525cf%252582-%2525ce%252595%2525cf%252580%2525ce%2525b9%2525cf%252587%2525ce%2525b5%2525ce%2525b9%2525cf&sOrder=dt_pub_date&iOrderType=desc&sShowAs=gallery »
Signatures Count: 1 »
Signatures Reference: module_extras.php:L132 »
Why Blocked: Nesting attack! »
User Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) »
Reconstructed URI: https : // xxxxxx /index.php?page=search&sCategory=%2525ce%252595%2525ce%2525be%2525ce%2525bf%2525cf%252580%2525ce%2525bb%2525ce%2525b9%2525cf%252583%2525ce%2525bc%2525cf%25258c%2525cf%252582-%2525ce%252595%2525cf%252580%2525ce%2525b9%2525cf%252587%2525ce%2525b5%2525ce%2525b9%2525cf&sOrder=dt_pub_date&iOrderType=desc&sShowAs=gallery »
