### ISSUE TITLE
Wrong Block / Query command injection Injection

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#343]
This is not a "Query command injection" but a TAG about bcrypt().

ID: 1664981197-700052-8347520528 »
Date/Time: Wed, 05 Oct 2022 17:46:37 »
IP Address: 65.21.180.65 »
Hostname: hz-1.links.ls.007ac9.net »
Query: wpfin=tag&wpfs=bcrypt() »
..
Signatures Count: 1 »
Signatures Reference: module_extras.php:L97 »
Why Blocked: Query command injection! »
User Agent: Mozilla/5.0 (compatible; SeekportBot; +https://bot.seekport.com) »
Reconstructed URI: https: // zzzzzzzzzzzzzzz /forums/?wpfin=tag&wpfs=bcrypt() »

**Comment by Maikuolan** [comment]
Cheers. I think, I'll remove the offending signature entirely. It's an old signature from 2016, which I guess, at the time, seemed like a good idea to include, but TBH, looks way too risky and not beneficial enough for my liking now in 2022.

**Comment by Maikuolan** [comment]
Done. :-)
