### ISSUE TITLE
Request - Auto Refresh viewing log files when updated

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#350]
Hi,

I was using a (bad) firefox addon to Refresh every 60 seconds the page viewing a log. Now i have added manually a refresh meta in one CIDRAM html file (something log.html) and also works ok.

I would like to ask if possible to make CIDRAM, when viewing the CURRENT log file, to automatically refresh ONLY when a new record is added in the log.

Why?

I manage 5 sites, with one CIDRAM instance and it is very usefull to see what is wrong immediately and act accordingly.

Please consider it ....

Thank you !

**Comment by Maikuolan** [comment]
*Related: #271.*

**Comment by Maikuolan** [comment]
I'll investigate whether this is doable soon. :-)
