### ISSUE TITLE
AbuseIPDB

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#351]
I had today several Contact form spam from

https://www.abuseipdb.com/check/216.131.111.156

and that is strange. My IPDB settings:

abuseipdb➡max_age_in_days: 365
abuseipdb➡minimum_confidence_score: 10
abuseipdb➡minimum_total_reports: 1
Requests for sensitive pages only 

What do you think?

**Comment by Maikuolan** [comment]
The IP address in question has a confidence score of 33% at the moment, so the minimum confidence score is not the problem. It has reports as recent as today, going back as far as a few months ago, so the maximum age in days is not the problem. And, at least 80+ reports currently exist, so the minimum total reports is not the problem, either.

Maybe the lookup wasn't triggering correctly? Are there any records in CIDRAM's log files for that particular IP address, or does it seem that CIDRAM has never been blocking it at all?

**Comment by Maikuolan** [comment]
Something is definitely not right there. I just checked, and CIDRAM's default signature files already block that particular IP address too, so it definitely shouldn't be able to get through and spam like that.

![Strong](https://user-images.githubusercontent.com/12571108/200272743-9e098420-96b9-4def-a2bd-01ed8921e301.png)

**Comment by eurobank** [comment]
I don't use any of those signatures. I only use Aux Rules, TOR block, AbuseIPDB and custom ip4.

**Comment by Maikuolan** [comment]
Hm, okay. I guess, the lookup must be not triggering properly then (unless it's something else, but I can't think of any other possibilities offhandedly).

Could you share here what the "final part" of the URL looks like for the contact pages where this happened (excluding the query and excluding any other sensitive details)?

E.g., for this particular issue at the issue tracker, which has the complete URL of `https://github.com/CIDRAM/CIDRAM/issues/351`, the "final part" would be `/351`.

**Comment by eurobank** [comment]
It is the domain (slash) /contact

**Comment by Maikuolan** [comment]
Yep.. Wasn't triggering properly. I've adjusted the detection for "sensitive pages" slightly, which should fix the problem. Let me know how it goes. :-)
