### ISSUE TITLE
Query command injection - Wrong Block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#354]
In Wordpress, happens to me as admin:

Query: context=edit&include%5B0%5D=13976&_locale=user

/wp-admin/post.php?post=137&action=edit

Query command injection!

/wp-json/wp/v2/blocks?context=edit&include%5B0%5D=13976&_locale=user

Signatures Reference: extras.php:L96

**Comment by eurobank** [comment]
Maybe the Optional security extras module should be updated a little bit :)

**Comment by Maikuolan** [comment]
Just pushed some commits which *should* fix it, but keep an eye on it and let me know if it continues to play up. :-)

**Comment by eurobank** [comment]
I will keep an eye open of cource, still an update must be available first :)

**Comment by eurobank** [comment]
Seems fixed. 

Thanks !
