### ISSUE TITLE
POST BBCESC/BBCEX/EX! wrong block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#355]
Again issues from the extras module. I will have to disable it, i'm afraid.

This is usage from our WP Forums and one logged user (verified).

/wp-admin/admin-ajax.php?lang=en&page_id=1232&wpforo_boardid=0 

Signatures Reference: extras.php:L244

Why Blocked: POST BBCESC/BBCEX/EX!

**Comment by Maikuolan** [comment]
Understandable, and sorry for the trouble.

In any case, I've removed the problematic signature entirely as of now.

**Comment by eurobank** [comment]
No problem. Really.

But i have to carefully examine all the logs (5 sites) to see if anything is wrong. And i have found so many wrong blocks in the extras. And it is so bad to block something 100% legit and worst of all **not to know**.
