### ISSUE TITLE
AbuseIPDB wrong block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#360]
Hi,

It seems that the login/register check of CIDRAM, is considering several parts of url as login/register pages and potentially blocks them.

And example below. 

I think the best way to do that is to look NOT the whole URL for words like login or register, but the right / END of the URL. Maybe also AFTER the last slash?

Script Version: CIDRAM v3.0.0 »
Date/Time: Fri, 25 Nov 2022 19:05:18 +0200 »

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 »
Signatures Count: 1 »
Signatures Reference: abuseipdb.php:L138 »
Why Blocked: AbuseIPDB Lookup! »
Reconstructed URI: https : // www. website . com /wp-content/plugins/**user-registration**/assets/css/dashboard.css »
Infractions: 1 »

**Comment by eurobank** [comment]
An other idea is to let us put multiple urls we use for login and register pages.

For example for me it is

/wp-login.php
/wp-login.php?action=register
/wp-login.php?action=lostpassword

--

/user/login
/user/register
/user/recover

**Comment by Maikuolan** [comment]
> An other idea is to let us put multiple urls we use for login and register pages.

That could work. I'll give that a try. :-)

**Comment by Maikuolan** [comment]
Added a new configuration directive just now (`general➡sensitive`). Let me know what you think. :-)

**Comment by Maikuolan** [comment]
The way I've coded the new directive, you could enter in paths like these literally, as they are, in order to match from the left:

```
/wp-login.php
/wp-login.php?action=register
/wp-login.php?action=lostpassword
/user/login
/user/register
/user/recover
```

Or, if you wanted, purely as an example, to match any files named as "sensitive.php" from the right, ignoring the left (to catch it via regular expression):

```
~sensitive\.php$~i
```

Or anything else to catch from anywhere in the path.

**Comment by eurobank** [comment]
I will have to test this and update here.

**Comment by eurobank** [comment]
where is that new directive? Not in AbuseIPDB?

**Comment by eurobank** [comment]
(general➡sensitive) ??? I can't find it.

**Comment by eurobank** [comment]
Seems to work fine, i will keep an eye open ....
