### ISSUE TITLE
Wrong Petal bot block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#363]
ID: 1670583950-676699-3629994988 »
Script version: CIDRAM v3.0.0 »
Date/Time: Fri, 09 Dec 2022 13:05:50 +0200 »
IP address: 114.119.148.138 »

User agent: Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot) »

**Hostname: ecs-114-119-148-138.compute.hwclouds-dns.com** »

For me the hostname shows: 

**petalbot-114-119-148-138.petalsearch.com** 

and not the above hostname. strange isn't it?

**Comment by Maikuolan** [comment]
That's definitely very odd.

Testing it at my end, the correct hostname is produced, and the IP address not blocked:

![petal1](https://user-images.githubusercontent.com/12571108/206693173-36d01396-fd96-4b51-ad7e-dbdaa72c65dd.png)
![petal2](https://user-images.githubusercontent.com/12571108/206693179-2227baec-006a-4097-922d-dba8ec564a3b.png)

Performing an nslookup manually from my machine also produced the same, correct hostname (`petalbot-114-119-148-138.petalsearch.com`).

Seeing that incorrect hostname shown (`ecs-114-119-148-138.compute.hwclouds-dns.com`), my guess is that the DNS provider used for resolving hostnames temporarily had the wrong information, which was later subsequently updated to the correct information, or something went wrong during routing.

**Comment by eurobank** [comment]
Those old dns replies come from 1.1.1.1 and 1.0.0.0 dns i use, from cloudflare. 

Apparently cached old entries.

**Comment by eurobank** [comment]
After switching to google dns, still i see the same issue. So it is not a DNS issue but a petal bot issue. Or maybe they do it on purpose, who knows.


D: 1670663804-099381-7876986341 »
Script version: CIDRAM v3.0.0 »
Date/Time: Sat, 10 Dec 2022 11:16:44 +0200 »
IP address: 114.119.135.37 »

User agent: Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot) »

Why blocked: Fake PetalBot»

Infractions: 6 »
Request method: GET »
Hostname: ecs-114-119-135-37.compute.hwclouds-dns.com »

**Comment by eurobank** [comment]
The only "bad" thing is that my automated reports to AbuseIPDB are wrong and they are a LOT.
