### ISSUE TITLE
Logged out of frontend after a while

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#365]
When in front end admin, after a while i'm logged out, for some reason.

How can i debug this?

Thanks

**Comment by eurobank** [comment]
When logged out, the Logs settings (formatting, paginate, sorting, remember) go back to defaults. And also statistics are zeroed, and IP tracking also zeroed.

**Comment by eurobank** [comment]
If it is of any help, this seems to happen when under heavy traffic or attack of some kind. 

For example right now, it happens while i get an "attack" of a heavy russian IP content scraping. On a calm period of time, it doesn't seem to happen.

**Comment by eurobank** [comment]
After mitigating the scrapers attack, the issue has been stoped (or limited, i don't know). It hasn't happened for 2 hours now.

So this is happening when traffic is high, like a flood attack. That attack i faced, was from a cable connection from Russia.

In the past i have complained that my stats are cleared randomly. Apparently it is not that random but the issue is connected to THIS issue. Something happens and all is lost/zeroed. My session, the settings of the log viewing, the stats.

**Comment by eurobank** [comment]
How can i debug this, since right now i CAN during this "attack". Otherwise it will be hard to simulate an attack. I can deblock the IP and debug this for a while.

How can i see what is wrong, is there a debug mode or something?

**Comment by eurobank** [comment]
UPDATE: After i enabled MemcacheD (1 hour ago), the issue is gone, after removing all IP blocks from Cpanel and leaving CIDRAM custom.ip4 to block the ip range. We have logged around 5000 blocks during one our from that Russian IP and everything is ok. 

That is GREAT !!


![2022-12-14 20_40_49-CIDRAM – Logs — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/207686173-431a47e0-2661-4d08-aa5e-e5ef979a10fb.png)

**Comment by mikeruss1** [comment]
in my experience CIDRAM is unstable under heavy traffic without memcache

**Comment by Maikuolan** [comment]
If cache data is being dumped for some reason (e.g., the utility used for caching being overloaded due to ongoing attacks), that would explain what's causing logouts to occur, due to that the CIDRAM front-end stores session information in the cache (and if the cache data as a whole is being dumped, that would include the stored session information, thus effectively ending the session, causing any logged in accounts to be logged out).

I think, most of these problems (e.g., being logged out, tracking not always working, etc) seem to all stem from the problems encountered with caching, and if these caching problems can be resolved, all these other problems should disappear.

**Comment by eurobank** [comment]
Using memcached for 2 days now, my session seems to be ok, no log outs. 

If tracking is working , i dunno, since the tracking page is empty. Maybe tracking works but the information is missing.

**Comment by Maikuolan** [comment]
I have some ideas about why tracking might be not working properly, but I'll need to test those ideas to confirm. I'll reply back a bit later.

**Comment by mikeruss1** [comment]
my guess would be that running without memcache under heavy load the cache gets reset.

running with memcache I thing tracking info is being written but not retrieved. Not sure about the stats variable I couldnt find it, whats it called ?

**Comment by eurobank** [comment]
@mikeruss1 Well "heavy load" is for me and CIDRAM around 200 visits per minute .....

**Comment by eurobank** [comment]
@Maikuolan Trying also to manually add an IP to tracking, it doesn't work. Nothing is added.

**Comment by mikeruss1** [comment]
That figures with my experience, before I switched to using memcached with v2 there would be a good chance of clearing cidram cache with 3 or 4 transactions a second.cheers.... MikeOn 17 Dec 2022 19:50, eurobank ***@***.***> wrote:
@mikeruss1 Well "heavy load" is for me and CIDRAM around 200 visits per minute .....

**Comment by eurobank** [comment]
Even with Memcached i still find myself occassionaly logged out of CIDRAM, without any reason.

**Comment by mikeruss1** [comment]
I think you switched to v3, memcache isn't working properly?

**Comment by eurobank** [comment]
Yes v3 and memcache activated. Previously under load of traffic i was logged out very very often. Now it happens once every few days. Not that important, still i wanted to let you all know.

**Comment by 737simpilot** [comment]
Behold the power of memcached.

Question: Why are you staying logged in anyway? You should (like everything, really) log in then when done log out. I do this for security reasons.

**Comment by Maikuolan** [comment]
BTW.. Got some reasonably recent ideas on how to fix the problems with Memcached. Just haven't had time the past few days to work any of those ideas due to being preoccupied by other things (unexpected offline commitments, mostly), but intend to work them shortly.

**Comment by eurobank** [comment]
> Behold the power of memcached.
> 
> Question: Why are you staying logged in anyway? You should (like everything, really) log in then when done log out. I do this for security reasons.

I have added manually an auto-refresh to the log page and i'm always logged in (almost always). I monitor 5 different sites. 

Security reasons i believe do not exist with v3 since it is located outside of the websites root and in there is NO access. And we run a very very secure server, with Imunify360 server-wide, and a firewall in each and every site.

**Comment by eurobank** [comment]
Keep also in mind that when i find my self logged out, the settings also in view log are reset to default.

**Comment by eurobank** [comment]
This logout doesn't seem to happen when using Redis or PDO. Apparently is it some issue when flat files are used.

**Comment by Maikuolan** [comment]
*Marking as "Won't Fix".*
