### ISSUE TITLE
PHP Warning:  Use of undefined constant ob_get_level

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#370]
PHP Warning:  Use of undefined constant ob_get_level - assumed 'ob_get_level' (this will throw an Error in a future version of PHP) in /home/pathofcidramhere/vault/CIDRAM/CIDRAM/Protect.php on line 424

**Comment by eurobank** [comment]
This notice appears only a specific date and not after. It can be some update after that that fixed it?

**Comment by Maikuolan** [comment]
Small typo in some other recently pushed code. Should be fixed now. :-)
