### ISSUE TITLE
Http version

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#377]
if there are no plans to migrate HTTP version blocker to v3, how about exposing $_SERVER['SERVER_PROTOCOL'] in Aux Rules ?

**Comment by Maikuolan** [comment]
Working on the module now. :-)

**Comment by Maikuolan** [comment]
Module has been implemented. Might see to doing something for auxiliary rules too anyway, seeing as it's something which could be potentially leveraged there maybe.

**Comment by mikeruss1** [comment]
There may be other items in $SERVER worth including?

**Comment by Maikuolan** [comment]
Probably. I'll need to take another closer look at it all again, I think.

**Comment by Maikuolan** [comment]
> Might see to doing something for auxiliary rules too anyway, seeing as it's something which could be potentially leveraged there maybe.

And done. :-)

> There may be other items in $SERVER worth including?

I've taken another quick look through what's available at the moment, and I don't really see anything which stands out as being likely to be particularly useful. I think I'll just leave it at that for now, and if, in the future, someone particularly wants support for some other specific server variable, they can just request for it to be added, and I'll deal with it at that time. :-)

**Comment by mikeruss1** [comment]
Good, thanks. I did read that items starting with http_ are sourced from the headers and can't be trusted.

**Comment by Maikuolan** [comment]
Yeah.
