### ISSUE TITLE
Redis support - WP_REDIS_DATABASE

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#380]
Hi,

Is CIDRAM with Redis, using WP_REDIS_DATABASE settings at all ? 

I ask that because we can use the same instance of Redis for multiple sites in the same hosting space, if WP_REDIS_DATABASE is set for each different domain/site.

**Comment by Maikuolan** [comment]
Nope. CIDRAM doesn't touch WP_REDIS_DATABASE at all.

Something worth investigating maybe?

**Comment by eurobank** [comment]
Well it depends on the difficulty factor. If it is something easy, then yes. If it requires a lot of changes maybe later at some point.

Let's first fix some urgent issues.....
