### ISSUE TITLE
[Absurd] Request - View or Log ALL Reconstructed URI in realtime

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#385]
This is crazy request, i know, feel free to ignore :)

I would very much help me (or maybe others) to only view ALL hits (not the blocked only) in the form of "IP" & "Reconstructed URIs". 

In some log (but only the IPs & Reconstructed URIs). Or just in realtime as they happen, somehow.

Why? Because it is very easy to block something you need and also it is easy to not know what you must block.

**Comment by mikeruss1** [comment]
apache log? - you can define log format in httpd.conf. 

cpanel - visitors gives you something close

**Comment by eurobank** [comment]
Hi,
No, not anything like that. Have you ever used Wordpress Wordfence? Something like the live traffic feature. But a lot simpler.

Anyways, i get that it is not for CIDRAM to support this.

**Comment by mikeruss1** [comment]
Sorry never been near wordpress. If you have access to the logs happy to write some PHP to do what you want? It sounds easy enough

**Comment by eurobank** [comment]
Actually no.

What i would do if i could write code is, have an option for CIDRAM to log everything (blocked/unblocked) and then an option in the log viewing for a custom view format. That would do.

That way i could view all the traffic and understand what i need to block or not.

**Comment by Maikuolan** [comment]
Possibly might be able to come up with something. Leave it with me for a bit and I'll reply back later.
