### ISSUE TITLE
Paging Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#386]
It seems that paging is not working right and you don't know where you are exactly (almost always 100/xxx)

See the video:

https://drive.google.com/file/d/1494HDRzZDty0fKQogH72jNPtRZyYz5U1/view?usp=sharing

**Comment by eurobank** [comment]
@Maikuolan Could you please check this when you have some time? I think it is a small easy-2-fix bug :)

**Comment by Maikuolan** [comment]
Will do. :-)

**Comment by Maikuolan** [comment]
Well.. In the process of trying to resolve this particular issue, I've found several other, additional problems which need dealing with, so.. slowly getting there, but taking a little longer than anticipated. Will report progress here as it happens.

**Comment by Maikuolan** [comment]
I've implemented some changes now which should hopefully make it easier to know where abouts you are while using pagination, and it should now specify the actual range of entries covered by any given page.

Unfortunately, for reasons I haven't quite yet been able to figure out, the way it calculates that range spazzes out a bit sometimes when filtering by specific search terms, but seems to work properly without any problems AFAICT when *not* filtering by specific search terms (i.e., when just looking at the logs normally). I'll get that fixed if I'm able to figure out what's going on at some point.

Aside from that, there were a number of problems I found which I was able to fix (details noted in the changelogs and in the commit descriptions). If you spot anything else though, please let me know (it's always possible I might've missed a problem or two).
