### ISSUE TITLE
[V3] Tracking - Expiry - No data available?

### ISSUE THREAD

**Issue by tnovak007** [CIDRAM/CIDRAM#390]
Hi!

Sorry to bother again. But I probably found another bug, but this time only minor.

On IP Tracking page the Expiry column shows only "No data available" instead of the expiry time.
I see expiry time in db (I'm using PDO) so I think it's only some parsing glitch...

Thank you.

EDIT:
I think the first condition here is causing the problem:
```
                    /** When the entry expires. */
----->         if (!is_int($ThisTrackingArray['Time']) || $ThisTrackingArray['Time'] < 1) {
                        $ThisTracking['Expiry'] = $this->L10N->getString('label_no_data_available');
                    } else {
                        $ThisTracking['Expiry'] = $this->timeFormat(
                            $ThisTrackingArray['Time'],
                            $this->Configuration['general']['time_format']
                        ) . '<br />(' . $this->relativeTime($ThisTrackingArray['Time']) . ')';
                    }
```

**Comment by Maikuolan** [comment]
Good spotting. I'll take a look at this later today. :-)

**Comment by Maikuolan** [comment]
Changes pushed. Let me how how it goes. :-)

**Comment by tnovak007** [comment]
Hi!

Thank you! It's working now!
