### ISSUE TITLE
SeznamBot blocked

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#394]
I think SeznamBot must be allowed and not blocked. Why block it? It doesn't hurt anyone .... And also respects robots.txt

IP address: 77.75.79.31 »
User agent: Mozilla/5.0 (compatible; SeznamBot/4.0-RC1; +http://napoveda.seznam.cz/seznambot-intro/) »
Signatures count: 1 »
Signatures reference: badhosts.php:L81 »
Why blocked: SEO/Bothost/Scraper/Spamhost! »
Verified identity: SeznamBot »
Request method: GET »
Hostname: fulltextrobot-fresh-77-75-79-31.seznam.cz »

**Comment by Maikuolan** [comment]
Whoops.. Yeah.. That one shouldn't be being blocked. Looks like an old hangover from some super old changes from some years back which didn't get removed before when they should've been removed. I'll get that sorted out now. Cheers. :-)

**Comment by Maikuolan** [comment]
Done. :-)
