### ISSUE TITLE
AUX Rules issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#395]
This

https://www.abuseipdb.com/check/194.163.131.103

![Screenshot(3)](https://user-images.githubusercontent.com/4467158/215258257-c35d222e-c3ad-4ea7-8413-3dc4484411a1.png)

passed and filled us with spam via contact and comment. But it shouldn't:

![Screenshot(3)](https://user-images.githubusercontent.com/4467158/215258189-15040f80-4891-40c7-a551-82ecdc6890bf.png)

And other Aux Rules seem also not to be respected.

**Comment by Maikuolan** [comment]
Was wondering whether CIDRAM might be interpreting a different hostname for that particular IP address than what AbuseIPDB shows, but I tested that out, and I don't think it's that. At my end, at least, CIDRAM seems to be showing the correct hostname.

![Untitled](https://user-images.githubusercontent.com/12571108/215274718-e180d980-8c27-4215-9930-bcba40ff8b8f.png)

Will test other ideas and post results as I progress.

**Comment by Maikuolan** [comment]
Hmm.. Replicated the rule exactly at my end, scripted in the IP address in question to fake it, and sent a request to my own dev copy, and it seemed to block correctly.

Not sure what's going on there exactly.

**Comment by eurobank** [comment]
@Maikuolan Sometimes it works, some doesn't :) Usually it does, luck us.

**Comment by eurobank** [comment]
I'm closing this since it could be related to a fixed issue with aux rules. I will keep an eye open.
