### ISSUE TITLE
Project Honeypot Module incorrectly (inadvertently) block Search Engines 

### ISSUE THREAD

**Issue by tnovak007** [CIDRAM/CIDRAM#396]
Hi!

I tried to use Project Honeypot Module but found some problem (or at least missing option for unwanted behavior).

When I enabled it, it soon blocked some traffic:
![image](https://user-images.githubusercontent.com/44246865/215362063-fb3794ad-a0d9-4c3b-9e9e-4bfd9d1c6626.png)

When I looked in the cache it had Threat score over minimum_threat_score (10), so OK:
![image](https://user-images.githubusercontent.com/44246865/215361681-8e901247-27fb-4d3e-8021-23240ae88a17.png)

But as described here "Type of visitor" 0 means "Search Engine":
[Http:BL API Specification](https://www.projecthoneypot.org/httpbl_api.php)

And I don't want to block Search Engines.
![image](https://user-images.githubusercontent.com/44246865/215363225-709a53a0-b2ce-4d3b-b8ba-9f8aaa3db6b8.png)

But I didn't find any option to select types of visitors to block.

The module script saves the type but block trigger doesn't do any check of the type:
```
    /** Block the request if the IP is listed by Project Honeypot. */
    $this->trigger(
        (
            $this->CIDRAM['Project Honeypot-' . $this->BlockInfo['IPAddr']]['Threat score'] >= $this->Configuration['projecthoneypot']['minimum_threat_score'] &&
            $this->CIDRAM['Project Honeypot-' . $this->BlockInfo['IPAddr']]['Days since last activity'] <= $this->Configuration['projecthoneypot']['max_age_in_days']
        ),
```
So I "fixed" it like this (I hope it will do what I want now)...
```
    /** Block the request if the IP is listed by Project Honeypot. */
    $this->trigger(
        (
            $this->CIDRAM['Project Honeypot-' . $this->BlockInfo['IPAddr']]['Threat score'] >= $this->Configuration['projecthoneypot']['minimum_threat_score'] &&
            $this->CIDRAM['Project Honeypot-' . $this->BlockInfo['IPAddr']]['Days since last activity'] <= $this->Configuration['projecthoneypot']['max_age_in_days'] &&
            $this->CIDRAM['Project Honeypot-' . $this->BlockInfo['IPAddr']]['Type of visitor'] > 0
        ),
```
But might I ask you: Is it possible to make some option for it so I wouldn't have to do this?

Thank you!

**Comment by Maikuolan** [comment]
Good spotting. I'll get something sorted out for this soon. :-)

**Comment by Maikuolan** [comment]
A new configuration directive has been added for controlling whether to block or profile based on the type of visitor as determined by Project Honeypot. :-)

![tov](https://user-images.githubusercontent.com/12571108/216315857-47fc0059-226b-48f6-9f57-d04fb40429e8.png)

**Comment by tnovak007** [comment]
Thank you very much! Even better solution than I thought :-)
