### ISSUE TITLE
Question for proxies block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#397]
Any ideas how i could implement this with Aux rules?

`# block proxy servers from site access
RewriteEngine on

RewriteCond %{HTTP:VIA}                 !^$ [OR]
RewriteCond %{HTTP:FORWARDED}           !^$ [OR]
RewriteCond %{HTTP:USERAGENT_VIA}       !^$ [OR]
RewriteCond %{HTTP:X_FORWARDED_FOR}     !^$ [OR]
RewriteCond %{HTTP:PROXY_CONNECTION}    !^$ [OR]
RewriteCond %{HTTP:XPROXY_CONNECTION}   !^$ [OR]
RewriteCond %{HTTP:HTTP_PC_REMOTE_ADDR} !^$ [OR]
RewriteCond %{HTTP:HTTP_CLIENT_IP}      !^$
RewriteRule ^(.*)$ - [F]`

**Comment by Maikuolan** [comment]
I don't think it would be possible to replicate that with auxiliary rules. Something like that might be better replicated as a module, I think.

**Comment by Maikuolan** [comment]
I haven't tested it yet, but something like this should work:

```PHP
<?php
if (!isset($this->CIDRAM['ModuleResCache'])) {
    $this->CIDRAM['ModuleResCache'] = [];
}

$this->CIDRAM['ModuleResCache'][$Module] = function () {
    $this->trigger(
        (
            (isset($_SERVER['HTTP_VIA']) && strlen($_SERVER['HTTP_VIA'])) ||
            (isset($_SERVER['HTTP_FORWARDED']) && strlen($_SERVER['HTTP_FORWARDED'])) ||
            (isset($_SERVER['HTTP_USERAGENT_VIA']) && strlen($_SERVER['HTTP_USERAGENT_VIA'])) ||
            (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && strlen($_SERVER['HTTP_X_FORWARDED_FOR'])) ||
            (isset($_SERVER['HTTP_PROXY_CONNECTION']) && strlen($_SERVER['HTTP_PROXY_CONNECTION'])) ||
            (isset($_SERVER['HTTP_XPROXY_CONNECTION']) && strlen($_SERVER['HTTP_XPROXY_CONNECTION'])) ||
            (isset($_SERVER['HTTP_HTTP_PC_REMOTE_ADDR']) && strlen($_SERVER['HTTP_HTTP_PC_REMOTE_ADDR'])) ||
            (isset($_SERVER['HTTP_HTTP_CLIENT_IP']) && strlen($_SERVER['HTTP_HTTP_CLIENT_IP']))
        ),
        $this->L10N->getString('Short_Proxy') . '(' . $Module . ')',
        'Connecting to this website with proxies is not permitted.'
    );
};

$this->CIDRAM['ModuleResCache'][$Module]();
```
