### ISSUE TITLE
v3 - part of Google cloud not blocked

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#398]
this is blocked in v2 but not v3
107.178.231.247
107.178.232.181

**Comment by Maikuolan** [comment]
Should be fixed with the next signatures update. :-)

(Committed, but haven't pushed yet due to sorting a few other things out at the moment).

I'll reply back here once pushed.

**Comment by Maikuolan** [comment]
And done. :-)
