### ISSUE TITLE
Requests for Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#403]
** FEEL FREE TO IGNORE **

1. When you disable a rule, automatically move the rule at the bottom.
2. Make the description of actions shorter. For example "Disable this rule" can be "Disable". "Move to the bottom" can shorter also. Because even in a 1080p 27 monitor, they are very long.
3. Make an option to totally disable the Aux Rules. Not each one of them but totally the whole Aux Rules. And totally REenable them.

**Comment by eurobank** [comment]
@Maikuolan Is there a way to disable ALL aux rules at once? I have some 30-35 and it is getting hard to manage and test.

**Comment by Maikuolan** [comment]
> 3. Make an option to totally disable the Aux Rules. Not each one of them but totally the whole Aux Rules. And totally REenable them.

Done. :-)

**Comment by Maikuolan** [comment]
> Make the description of actions shorter. For example "Disable this rule" can be "Disable".

Also now done. :-)

Issue is now pretty old and already closed anyway, so I think I'll leave it at that and go ahead and mark this as implemented.
