### ISSUE TITLE
Aux Rule for empty user agents?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#411]
Trying a rule with "^$" and other also variations (^-?$) and i fail?

Any ideas?

**Comment by Maikuolan** [comment]
Missing the pattern boundary. :-)

If you try something like `/^$/` or `~^$~` or such, it should start working. :-)

**Comment by eurobank** [comment]
Well all the above don't work, but i will find an other way to do it.

**Comment by mikeruss1** [comment]
in case it helps, this is the aux rule to block a UA of less than 15 characters

User agent = [^.{0,15}$]
