### ISSUE TITLE
How to access FrontEnd in WordPress

### ISSUE THREAD

**Issue by alamrekane1** [CIDRAM/CIDRAM#419]
I installed CIDRAM for WordPress through plugins and I can't access the loader.php file via the following path:
https://***.com/wp-content/plugins/cidram/vault/loader.php
It shows me: [CIDRAM] This should not be accessed directly.
Can you explain to me how to access FrontEnd in version 3?

**Comment by Maikuolan** [comment]
I'm working towards properly integrating the CIDRAM Front-End with the WordPress Dashboard at the moment, and as of the next upcoming release (v3.1.0), it should all be accessible with a simple click, without the same hoops and hurdles that previous versions had. I anticipate it being ready within a day or so. :-)

**Comment by Maikuolan** [comment]
*Related: #135.*

**Comment by alamrekane1** [comment]
Amazing waiting for update
Thank you

**Comment by Maikuolan** [comment]
CIDRAM v3.1.0 has been released. :-)
