### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#421]
this is what you get if you paste a URL into Whatsapp

User agent: WhatsApp/2.23.3.77 A 
Signatures count: 1 
Signatures reference: bobuam.php:L102 Why blocked: Suspected bot or scraper probe!

the URL is the user so no way to verify. 

some other ones I got recently look suspicious and have earlier versions so might be worth checking this UA specifically.

**Comment by Maikuolan** [comment]
Fixed. :-)
