### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#422]
maybe add Snapchat to services to be verified, they use link cards like Whatsapp, They use Amazon network.

User agent: Snap URL Preview Service; bot; snapchat; https://developers.snap.com/robots
 Signatures count: 2 
Signatures reference: 34.240.0.0/12, bobuam.php:L124 
Why blocked: Cloud service ("Amazon.com, Inc", L10226:F1, [EU]), Suspected bot or scraper probe!

**Comment by Maikuolan** [comment]
Good idea. :+1:

I'll work on this today.

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by mikeruss1** [comment]
and works - blocks negatives anyway - thanks!
