### ISSUE TITLE
Infractions / Block issues

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#425]
28 of Feb this was blocked due to an aux rule (infractions 1):

ID: 1677587637-017113-5955758142 »
Date/Time: Tue, 28 Feb 2023 14:33:57 +0200 »
IP address: 5.161.102.38 »
User agent: Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2121 »
Why blocked: Hetzner! »
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: static.38.102.161.5.clients.your-server.de

Today 1 of March it reached 20 infractions:

ID: 1677655573-071663-2592284133 »
Date/Time: Wed, 01 Mar 2023 09:26:13 +0200 »
IP address: 5.161.102.38 »
User agent: Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36 »
Signatures count: 2 »
Signatures reference: Core.php:L2121 »
Why blocked: Banned, Hetzner! »
Infractions: 20 »
Country code lookup: XX »
Request method: GET »
Hostname: static.38.102.161.5.clients.your-server.de »

and then again today all was cleared and infractions started from zero:

ID: 1677655575-180601-4701233415 »
Date/Time: Wed, 01 Mar 2023 09:26:15 +0200 »
IP address: 5.161.102.38 »
User agent: Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2121 »
Why blocked: Hetzner! »
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: static.38.102.161.5.clients.your-server.de »

**Comment by eurobank** [comment]
Note that the infractions duration/tracktime is set to 7 days.

**Comment by Maikuolan** [comment]
Sorry for the delay. Haven't had time to look into this properly yet due to being preoccupied the past few days, but I'll aim to look into this properly hopefully later today.
