### ISSUE TITLE
Opera ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#427]
I think this is Opera Blink ?

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0 (Edition Yx 05)
Signatures count: 1 
Signatures reference: botua.php:L126 
Why blocked: Spam UA!

**Comment by Maikuolan** [comment]
Looks legit.

I think the "Edition Yx" bit refers to a version of Opera specifically catering towards Russian users, but I'm not 100% sure (not many results at Google, but I found that some of said results are some Russian-language pages at the official Opera website which try to automatically download what I'm assuming is the Opera installer).

The rest of the user agent, at least, correctly matches the format specified at __[Dev.Opera](https://dev.opera.com/blog/opera-user-agent-strings-opera-15-and-beyond/)__.

Taking a look at the affected module now.

**Comment by Maikuolan** [comment]
Treating it as a false positive for now. If it turns out to be wrong, that it wasn't Opera but something else, I can just revert later, I guess. For now though, fixed. :-)
