### ISSUE TITLE
ipv4_custom.dat issues

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#435]
I have some CIDRs in ipv4_custom.dat that are not blocked for that reason. They are blocked for some other aux rules reason. This is how i found the issue. So, some are blocked and some not, impossible to track what and when.

**Comment by Maikuolan** [comment]
Just to be sure: Is the custom signatures file listed at the configuration? (`components➡ipv4`).

**Comment by eurobank** [comment]
Here is a small sample:

In my custom dat 4
`
185.51.134.0/24 Deny Global_CIDRs`

and here is the block:

ID: 1678285937-209390-9566276815 »
Date/Time: Wed, 08 Mar 2023 16:32:17 +0200 »
IP address: 185.51.134.77 »
User agent: - »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: reconstructed URLs! »
Reconstructed URI: /bak/config.js »
Infractions: 1 »
Country code lookup: GR »
Request method: HEAD »
Hostname: - »

The IP is blocked for url aux rule and not because.

**Comment by eurobank** [comment]
Ok, it seems copy paste CIDRs was the issue, 1 extra space between the CIDR and the Deny was the issue!. I will keep an eye and update if still there is an issue.

**Comment by Maikuolan** [comment]
Also, under `signatures➡shorthand`, is the checkbox for "block other" selected?

![shorthand](https://user-images.githubusercontent.com/12571108/223744528-d039f7a7-bc3a-4a59-af1e-fa6b0a146997.png)

If that checkbox isn't selected, that could be preventing the signature in question from being triggered properly. (It should normally already be checked by default, but worth double-checking it, just in case).

**Comment by Maikuolan** [comment]
> Ok, it seems copy paste CIDRs was the issue, 1 extra space between the CIDR and the Deny was the issue!. I will keep an eye and update if still there is an issue.

Ah, okay. Glad to hear you've figured it out. '^.^

**Comment by Maikuolan** [comment]
Hm.. Seems that the signature file fixer isn't currently capable of detecting extraneous spaces. I might need to do something about that, considering that hitting the spacebar an extra time sounds like a pretty easy mistake to make, but not so easy to spot when eyeballing for the cause behind related problems.

**Comment by eurobank** [comment]
Today is the perfect day to test CIDRAM. 

Someone is targeting one of my sites for hours, with some 10-15 probes per minute for sys/php/zip/back/js etc files. From all over the world.

So i'm able to really test what is going on.

**Comment by Maikuolan** [comment]
Signature file fixer patch pushed. :-)
