### ISSUE TITLE
Infractions issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#436]
Something is wrong in the count of infractions? All of them have EXACTLY the same time and different ID, but there are 3 and shows 2 for the 3rd time. Also Tracking shows 2 infractions.

I'm using PDO/PHP 7.4

ID: 1678663800-695863-5876307802 »
Date/Time: Mon, 13 Mar 2023 01:30:00 +0200 »
IP address: 218.90.200.133 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: ASN China! »
**Infractions: 2 »**
Country code lookup: CN »
Request method: GET »
Hostname: - »

ID: 1678663800-699604-5880047935 »
Date/Time: Mon, 13 Mar 2023 01:30:00 +0200 »
IP address: 218.90.200.133 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Why blocked: ASN China! »
Infractions: 2 »
Country code lookup: CN »
Request method: GET »
Hostname: - »

ID: 1678663800-692488-5872942225 »
Date/Time: Mon, 13 Mar 2023 01:30:00 +0200 »
IP address: 218.90.200.133 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 »
Signatures count: 1 »
Signatures reference: Core.php:L2132 »
Infractions: 1 »
Country code lookup: CN »
Request method: GET »
Hostname: - »

**Comment by eurobank** [comment]
Ok, more data. The 3 "visits" blocked, were

1st block for SITE A -> 1 infractions
2nd block for SITE B -> 2 infractions
3rd block for SITE B -> 2 infractions

So 2 and 3 were for the same site. Does that make sense? Is that normal?

**Comment by Maikuolan** [comment]
> All of them have EXACTLY the same time and different ID

Theoretically possible. If a particularly aggressive bot/scraper/whatever was to flood all three websites (plus whichever other sites were being targeted by the bot in question) all at exactly the same time, and the infrastructure at both ends (i.e., the internet connection behind the websites, plus the internet connection behind the bot) was sufficiently fast to have all said requests be sent and received within the same one second time period (plus assuming both ends are able to handle and process multiple connections at the same time), we definitely *could* see all of these blocked requests having the exact same, identical date/time logged. I've seen it happen before, but rarely. Generally, I'd say it's unlikely to happen, and in much the same way as DDoS attacks, although we might describe it as "possible", we probably wouldn't describe it as "normal".

**Comment by Maikuolan** [comment]
That said.. Even if it's possible to have multiple requests be sent, received, and processed all within the same one second period, it's *far less* likely to happen all within the same one *microsecond* period. The first of three segments of the ID assigned to block events is based upon the specific microsecond at which the block event occurred (according to the server where CIDRAM is installed). A microsecond being one millionth of a second (or 0.000001 seconds), the chances of *that* particular value repeating among different block events, although not totally zero, is about as close to zero as we could possibly get, but I notice it has been repeated between the three block events cited above:

![Untitled](https://user-images.githubusercontent.com/12571108/224606179-c8fcb511-1d41-4d9c-9d55-48a23eb49c86.png)

**Comment by Maikuolan** [comment]
Do you have access to the Apache access logs at the websites in question? And how easy/difficult is it for you to be able to access/review said logs? I'm wondering whether it would be possible to verify whether multiple requests were received all at the same time across multiple websites like that by checking whether there are entries in the Apache access logs for that particular IP address corresponding to that exact date/time, and if so, how many of such entries there are. That way, at least, we'll know whether it's a matter of CIDRAM logging data incorrectly, whether something else, or whether perhaps there's nothing wrong at all (although I agree that these logged block events do look a little weird).

**Comment by eurobank** [comment]
@Maikuolan Just checked the logs and there is only ONE log for EACH of the two sites (there are two sites not three as you write). 

That means two visits total and not three as we see in CIDRAM log.
