### ISSUE TITLE
How to clear a BAN?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#439]
**REDIS**

I have tried to clear this ban and failed. I even Clear all the cache and cleared all tracking.

ID: 1678889182-666396-0197395040 »
Date/Time: Wed, 15 Mar 2023 16:06:22 +0200 »
IP address: 81.209.177.145 »
User agent: netEstate NE Crawler (+http : // www . website - datenbank . de/) »
Signatures count: 2 »
Signatures reference: auxiliary.yml:User agents_1 »
Why blocked: Banned, User agents_1! »
Infractions: 139 »
Country code lookup: XX »
Request method: GET »
Hostname: bardolino.netestate.de »

So how to clear a ban?

**Comment by Maikuolan** [comment]
If you've already tried clearing all tracking, and have also already tried clearing all from the cache page, and yet the IP address still remains banned, it sounds like there might be some kind of bug in the mechanisms for clearing all from the cache or clearing all tracking when using Redis. I'll look into this a little closer later tonight. (Just my gut speaking there, and there are a few other, albeit very unlikely possibilities I can think of offhandedly, but in any case, doing either of those two things, clearing all from the cache page, or clearing all tracking, should definitely result in the IP address being unbanned).
