### ISSUE TITLE
[BUG] ipaddr not updating from front-end and incorrect data shown

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#44]
@Maikuolan Found another bug.
I set `HTTP_CF_CONNECTING_IP` in `ipaddr` in the **config.ini** but in the front-end general->ipaddr: still shows `REMOTE_ADDR`
Also,
Updating` general->ipaddr:` from the front-end **does not work.**

![screenshot_10](https://user-images.githubusercontent.com/18257605/33141241-8ee42814-cfd8-11e7-9f3f-779950f15ba1.png)
![screenshot_11](https://user-images.githubusercontent.com/18257605/33141242-8f34afdc-cfd8-11e7-8dcd-fc5bc00b0c23.png)

**Comment by Maikuolan** [comment]
Thanks for reporting this. :+1: 

Confirmed; Marking as *Bug*.

The value seems to update correctly when the corresponding `$_SERVER` variable exists, but *doesn't* update correctly when the corresponding variable doesn't exist. It also seems to ignore the assigned value if the corresponding variable doesn't exist.

The assigned value for `ipaddr` being internally replaced by `REMOTE_ADDR` when the corresponding variable doesn't exist is expected, but it is *not* expected for it to extend to the configuration page itself, and it *should* be possible to assign any desired value to this configuration directive regardless. Investigating the cause of the bug now.

**Comment by Maikuolan** [comment]
Committed a fix just now; Should be working correctly now. :-)

**Comment by harryqt** [comment]
Yup. Updating from the front-end working now. 👍
