### ISSUE TITLE
Easy and Quick Way to lock your self out :)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#442]
Just write an Aux Rule, ASN condition and put letters with the number (example AS82938).

:)

**Comment by Maikuolan** [comment]
I'll do something about that now.

**Comment by eurobank** [comment]
and ... hehehe ... how we get IN?

**Comment by eurobank** [comment]
... and from what i see EVERY IP is blocked. Hidden feature. Easter egg :)

;)

**Comment by eurobank** [comment]
I'm in, after ftp editing the file ......

**Comment by Maikuolan** [comment]
BTW.. If anyone is curious about *how* this weird bug came about.. It's an unanticipated side effect of the fix I'd recently implemented for #429 to deal with type casting/coercion problems. Specifically, this here:

https://github.com/CIDRAM/CIDRAM/blob/da73544f3220b6925bb3fad098f1825f84f40b60/vault/CIDRAM/CIDRAM/Core.php#L2047-L2050

A simple demonstration of the problem at command line:

![int](https://user-images.githubusercontent.com/12571108/226112891-d4b0b948-2914-4467-bfea-cdd5f9edaccd.png)

Anyway, I've already got an idea in mind for how I'll deal with this. Won't be long.

**Comment by Maikuolan** [comment]
Should be good now. :-)

**Comment by eurobank** [comment]
I try to update but i get an empty page.

**Comment by eurobank** [comment]
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /home/PATH/vault/CIDRAM/CIDRAM/Updater.php on line 399

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Maikuolan\Common\Operation::ifCompare() must be of the type string, array given, called in /home/PATH/vault/CIDRAM/CIDRAM/Updater.php on line 413 and defined in /home/PATH/vault/Maikuolan/Common/Operation.php:253

**Comment by Maikuolan** [comment]
I'll take a look at that now.

**Comment by Maikuolan** [comment]
Fixed.

**Comment by eurobank** [comment]
nope. exactly same error. (php 7.4.1)

**Comment by eurobank** [comment]
Not sure if something changed but 1 minute ago i was able to update.
