### ISSUE TITLE
IP Test Page

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#447]
couple of small bugs

with a long line the blocking column can run off the end of the page as in ...
Yes – No access from China ("CN_cidram.inc-IPv4", L1735:F0), Cloud service ("Alibaba Advertising", L13545:F1, )++<Commercial>++

if you tick the modules you also get ...
Error – modules/extras.php (1)

**Comment by Maikuolan** [comment]
We've got linting for all PHP files at this repository [built into the repository's workflows](https://github.com/CIDRAM/CIDRAM/blob/v3/.github/workflows/v3.yml), to lint all PHP files at every commit, so, if there were any major syntax errors, or anything capable of causing linting to fail, we'd be seeing a red cross ❌ next to the offending commits at the commit history, instead the green tick ✔️ currently seen at the most recent latest commits. So, at the very least, if there's an error in the extras module, it isn't a linting error.

If it's not a linting error, if there's error, I'd assume there's most likely either something wrong with the data being fed to the module (e.g., the module expects data of a particular type, and the data fed to it is of a different type), something wrong with the downstream copy of the file (e.g., something corrupted the file), or something wrong somewhere else, either with the PHP version or something else running alongside CIDRAM (the probability of that being very low, but not absolutely zero, and as I don't know for sure what's causing the error, I mention the immediate possibilities that come to mind).

I'm not seeing the error replicated at my end.

We might need to have PHP to give us an exact error message for us to be able to get a better idea about exactly what's going on there.

Any chance you could turn on error logging at your CIDRAM installation and then artificially trigger a block event? (E.g., you could create a PHP file with a fake IP address set, set as something blocked by CIDRAM, call CIDRAM at that same PHP file, then request it). We should then see whatever the error is logged, hopefully.

**Comment by mikeruss1** [comment]
you realise I am talking about the IP Test page in the front end?

**Comment by mikeruss1** [comment]
![Clipboard02](https://user-images.githubusercontent.com/26255535/228860175-6daeee5a-0931-48c4-983e-8084caa13b0e.jpg)

**Comment by mikeruss1** [comment]
![Clipboard01](https://user-images.githubusercontent.com/26255535/228860353-e9ca7498-1089-4dae-848b-d48c7b3b231b.jpg)

**Comment by Maikuolan** [comment]
Text overflow issue should be fixed now. :-)

Still no idea about the extras module error though.

**Comment by mikeruss1** [comment]
overflow gone
extras issue gone !!

**Comment by Maikuolan** [comment]
Awesome. :-)
