### ISSUE TITLE
Wrong Log with Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#452]
The Log:

ID: 1680888697-846422-5973271007 »
Date/Time: Fri, 07 Apr 2023 20:31:37 +0300 »
IP address: 23.229.113.138 »

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 »
Signatures count: 2 »
Signatures reference: auxiliary.yml:ASN - Colocrossing »
Why blocked: Banned, ASN - Colocrossing! »

Infractions: 9 »
Country code lookup: US »
Request method: GET »
Hostname: xen1.la.servermania.com »

So that "Signatures reference: auxiliary.yml:ASN - Colocrossing" is somehow wrong, there is an other aux rule for B2 / Servermania.

![Screenshot](https://user-images.githubusercontent.com/4467158/230664916-f8a35318-1a88-4187-8039-cf5ee8780f2f.png)

**Comment by Maikuolan** [comment]
I don't think the log is wrong. The problem, I think, is that ServerMania doesn't seem to have their own, dedicated ASN.

Looking at the results page at [IP-API](https://ip-api.com/#23.229.113.138), we see ColoCrossing listed as the ISP and ASN which owns that IP address' range, but ServerMania as the name of the organisation which owns that IP address' range.

![Untitled](https://user-images.githubusercontent.com/12571108/230700633-5c1f0793-1635-4fe1-a887-cb91c6840fd9.png)

Searching "ServerMania" at [BGP.HE.NET](https://bgp.he.net/search?search%5Bsearch%5D=ServerMania&commit=Search), I see 10 different CIDRs, but no ASNs in the returned results, so at the very least, if ServerMania owns an ASN somewhere, they're calling it something else.

![Untitled2](https://user-images.githubusercontent.com/12571108/230700681-fea0ebce-509c-47df-a1b6-f98e91be33ae.png)

Checking those CIDRs against CIDRAM's default signature files, all of them are already currently being blocked, but not all under the same ASNs (most under "24 SHELLS", some under "ColoCrossing", and one of them under "B2 Net Solutions"). So, based on that information, I *suspect* that "ServerMania" is likely a company which likely either doesn't want to have an ASN of their own, or can't afford it, and instead just leases servers/infrastructure/etc from other providers.
