### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#455]
Hi,
I have suggested CIDRAM to 2 webmasters (wordpress) and both came back to me asking for installation questions. Most people will not use github to ask questions or report issues. They didn't use the WP plugin, just the generic installation.

And to be honest the installation guide is very confusing and possibly alienate people. 

For example Installing Manually is not clear at all. 

```
<?php
require_once '/path/to/the/vault/directory/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();

```
or

```
Example:

auto_prepend_file = "/path/to/your/entrypoint.php"

Or this in the .htaccess file:

php_value auto_prepend_file "/path/to/your/entrypoint.php"

```
Just read that part yourself. We are not developers, we are webmasters :)

**Comment by Maikuolan** [comment]
Anyone willing to try their hand at modifying some of the documentation? I think this is something I might need a little help with.

(No code knowledge required. In fact, less knowledge might even be preferable in some ways, due to the benefit of alternative perspective).

**Comment by eurobank** [comment]
I can only (try to) write an **example** for manual generic installation, for you to review.

**Comment by Maikuolan** [comment]
Sounds good. :-)
