### ISSUE TITLE
Suggestion - Crowdsec

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#456]
Could you please consider in the future to check Crowdsec network for CIDRAM?

Thanks

**Comment by eurobank** [comment]
Any thoughts on this?

**Comment by eurobank** [comment]
> Are you also looking to add network intelligence to your security software? We're helping integrate signal sharing and the creation of tailored blocklists thanks to our open-source PHP SDK doing the heavy lifting to interact with our Central API (CAPI)
> 
> As we are driving an effort to integrate signal sharing and blocklist acquisition on multiple CMS and e-commerce platforms, we're also improving everybody's reactivity against attacks.
> 
> You can find out about PHP SDK integration here (JS and Python SDK to come in 2023 depending on community requests): https://github.com/crowdsecurity/php-capi-client to easily create and send signals and https://github.com/crowdsecurity/php-remediation-engine built on top of it to ease the community blocklist management.

**Comment by Maikuolan** [comment]
Thanks for the links. :+1: Currently looking into this, still trying to find my way around it all. Haven't yet reached the point of being ready to test anything yet. I'll reply back later when I've looked a bit more into this.

**Comment by eurobank** [comment]
Thank is excellent news. Apart from the fact that it could be a CIDRAM module, do you like that service? 

Do you think it is any good? Promising? Mature or not?

**Comment by Maikuolan** [comment]
The *concept* sounds really promising to me. Whether it's truly any good though would depend on how well they pull it off, and on how they go about doing so, which right now, I'm not knowledgeable about. I'll need to experiment with it a little, and to try learning a little more about it, I think, before making any judgment about it.

**Comment by Maikuolan** [comment]
Their documentation, and instructions on how to use their service (at least, from what I've read from it so far) seems to assume some degree of prior knowledge about the service already, as it uses some terminology (e.g., "watchers", "signals", "bouncers", "scenarios", etc), which, in the contexts where that terminology appears, I'm not immediately familiar with the intended meaning. I haven't read through everything yet, but I'm hoping to find some definitions and further explanations further into it. That, or I'll just need to fiddle around a bit until I figure it out.

**Comment by eurobank** [comment]
@Maikuolan if it is of any help, there is one "use" of Crowdsec api that i know and use, for Wordpress as a feature of a security/firewall plugin, named **The Shield**.

**Comment by eurobank** [comment]
In case you do not use much Wordpress:

The Shield works with Crowdsec like this:

1. At some CRON it creates a TOKEN for the site with an expiration time
2. At some CRON it gets around 7000 IPs from Crowdsec, locally :)
3. Those IPs are limited because of the "free" The Shield versions (i call that Cripleware). For the Pro, you get more IPs i guess or even realtime checks.
4. The checks are not done in realtime with Crowdsec but from local banned IPs. 

I hope i gave you an idea. Probably The Shield is not doing a full api implementation (like you do for example with AbuseIPDB and you cache it) but preferes to get the IPs locally first every week or so.

**Comment by mikeruss1** [comment]
my suggestion would be the website needs improving, have had 2 attempts and still find it confusing. Too many technical terms, not enough simple explanations.

**Comment by eurobank** [comment]
The funny thing is, i found some other Wordpress and Joomla supporting Crowdsec BUT you need to have Crowsec installed already in the server. And that is out of question for 99% of webmasters.
