### ISSUE TITLE
Rate Limiting Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#459]
In one site, when Rate Limited is active, we can't login. 

Trying to login, we get "probaby invalid request". No other info is available or error in logs.

**Comment by Maikuolan** [comment]
> we get "probaby invalid request".

Is that within CIDRAM's own logs, within server access logs, or somewhere else?

**Comment by eurobank** [comment]
No, it is in the login form of the site. Trying to login.

**Comment by eurobank** [comment]
The part of the script that produces that is:

```PHP
/**
 * Check if CSRF token is valid, die in other case
 *
 * @since 3.1
 */
function osc_csrf_check($enabled = true) {
  // update 420
  if(!$enabled) {
    return true;
  }
  
  $error  = false;
  $str_error  = '';
  
  if(Params::getParam('octoken') == '') {
    **$str_error = _m('Probable invalid request.') ;**
    $error = true;
  } else {
    $token = Params::getParam('octoken');
    if (!osc_csrfguard_validate_token($token)) {
      $str_error = _m('Invalid CSRF/Security token.');
      $error = true;
    }
  }
  ```

**Comment by Maikuolan** [comment]
I'll need to dig through the Osclass code for a bit to try to figure out what's happening there exactly. Right now, I'm not entirely sure.

**Comment by eurobank** [comment]
Wordpress on the other hand doesn't seem to have any issues.

I understand this is not something totally related to CIDRAM, so i can't ask you to do that.

(how did you guessed Osclass :)  )

**Comment by Maikuolan** [comment]
> (how did you guessed Osclass :) )

Googled parts of the attached code, some of the results linked back to some GitHub repositories, which on closer investigation, had some other code which identified Osclass as the source, checked the repository for Osclass, and found the original code there. ;-)

**Comment by eurobank** [comment]
There are several releases of Osclass, after Osclass . org terminated his business.

What we use right now is from osclasspoint.com

**Comment by eurobank** [comment]
@Maikuolan Did you ever checked this more?
