### ISSUE TITLE
Aux Rules - Hostnames - lower/capital letters

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#460]
Can the aux rules hostnames check ignore the case "lower/capital" of  letters?

I mean if the hostname is "Onion" and the aux rule is to check for "onion" .....

**Comment by Maikuolan** [comment]
There isn't a specific option for that (direct-string comparison and Windows-style wildcards are both case-sensitive), but the simplest way to do that, as it stands at the moment, would probably be to match using regular expression and add the "case-insensitive" flag to the end of the expression, like so:

```
~onion~i
```

**Comment by eurobank** [comment]
Right! I didn't knew that. Thank you !

Must i read something, somewhere? Any suggested reading?

**Comment by mikeruss1** [comment]
https://www.regular-expressions.info/tutorialcnt.html

though it hasnt done me any good!
