### ISSUE TITLE
Failed to activate Frontend/en

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#462]
Just updated CIDRAM via the frontend like I normally do and saw this in the attached screenshot. Everything seems to work fine, but wanted to bring this to your attention just in case. 

CIDRAM version 3.2.0

![img](https://i.postimg.cc/jqFzQbwL/1.jpg)

**Comment by Maikuolan** [comment]
The failure itself isn't a problem, as an L10N component could be said to be "activated" by the act of selecting the corresponding language via the configuration page. Given that the updates page isn't responsible for setting CIDRAM's language, it's natural that any attempt by the updates page to activate an L10N component would fail. That said though, it *is* weird that it would even *try* to do so in the first place. Not sure why it would do that. I'll take a look into that a little later today.

**Comment by 737simpilot** [comment]
Thought it was something like that. I can tell you that for I don't know how long now, the en file was always "updated." 

Maybe it has something to do with me stripping out the other language files?

**Comment by Maikuolan** [comment]
Fixed. :-)
