### ISSUE TITLE
Sort in descending order

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#463]
When checking Sort in descending order, the Log list left sidebar is also sorted that way.

Can that be avoided or fixed (if you think it is in error)?

**Comment by mikeruss1** [comment]
this was my request - generally when I look at logs I want the most recent, so requested the list in descending order

**Comment by eurobank** [comment]
@mikeruss1 I don't speak for the Logs. I speak for the logs LIST at the left sidebar.

**Comment by mikeruss1** [comment]
yes, me too

**Comment by eurobank** [comment]
ok, then you like it like that?

![Screenshot(1)](https://user-images.githubusercontent.com/4467158/235663004-a77ad08a-1ea5-4d09-9409-11738b04e11f.png)

**Comment by mikeruss1** [comment]
no, my log list is in descending sequence, as is the log itself

**Comment by mikeruss1** [comment]
![image](https://user-images.githubusercontent.com/26255535/235670998-3e19ceb3-7ed2-4762-8166-a13c9df493d2.png)

**Comment by mikeruss1** [comment]
check your config - my log file setting is logfile{yyyy}{mm}{dd}.log

**Comment by eurobank** [comment]
Mine also is in descenting mode. Take a closer look.

**Comment by eurobank** [comment]
> check your config - my log file setting is logfile{yyyy}{mm}{dd}.log

Nothing wrong with it:

{dd}-{mm}-{yyyy}.log

**Comment by mikeruss1** [comment]
I suspect CIDRAM is sorting using the file name - if thats correct yours is sorting in dd mm sequence?

**Comment by Maikuolan** [comment]
Not quite sure just yet how to approach this. I'll think on it a bit and reply back later.

**Comment by Maikuolan** [comment]
I have an idea about how I might be able to fix this, but it'll be a little tricky to backport, so.. might need to be a v3-only fix, I think. Anyway, I'll try out my idea shortly.

**Comment by Maikuolan** [comment]
I've pushed some changes to the log sorting strategy just now, which should fix the problem. Let me know if further changes are needed. :-)

**Comment by Maikuolan** [comment]
Scratch that.. Changes are bugged. Logs not loading properly when selected, and duplicate time/date placeholders produce errors.

Need to get some sleep for the night but I'll continue working on this in the morning.

**Comment by Maikuolan** [comment]
Bugs fixed.

Let me know how it goes. :-)

**Comment by eurobank** [comment]
It goes very well, thank you
