### ISSUE TITLE
Expand IP Test page usefulness

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#464]
it would be useful to be able to expand the IP Test page facility a bit

would it be possible to confirm what would be the status of each of the output functions as per the Aux rules, ie status code(200, 403), IP tracking, logging, recaptcha, output to user, extended tracking?

the issue is at the moment its impossible to test as you cant simulate a GET from any IP apart from your own

**Comment by Maikuolan** [comment]
Working on this now.

**Comment by Maikuolan** [comment]
Try it now, and let me know what you think. :-)

**Comment by mikeruss1** [comment]
its doing stuff which is working as far as it goes
but it doesnt seem to be picking up blocks related to the UA
this might be caused by an error I have had for a while, if I turn on execute modules I get ...
Blocked: Error – modules/extras.php (1)
instead of the Cloud service line, but the rest of the report is OK, but lacks errors related to the UA
so if I give it a bad UA and a good IP - it passes it, even though I get Blocked: Error – modules/extras.php (1)
give it bad IP I get the Blocked report, plus all the Cloud info
if you can fix this I can give it a more thorough test

**Comment by mikeruss1** [comment]
![image](https://user-images.githubusercontent.com/26255535/236879281-39aa4ccb-f0b7-47fc-bb93-85c7ae9223a4.png)

**Comment by mikeruss1** [comment]
is there a plan to progress this one?

**Comment by Maikuolan** [comment]
Would like to go further with this, but not quite sure exactly how to right now. Leaving it open for now in case I come up with any fresh ideas.

**Comment by mikeruss1** [comment]
tks for update, its a nice to have I think

there are various aux rules I have that are impossible to test and the form offers UA input. If its not possible maybe best to rework the page a little?

**Comment by Maikuolan** [comment]
Added a focal switch for user agent testing.

**Comment by mikeruss1** [comment]
works now, good stuff - what does the focal switch do, I guess if the UA is turned off it doesnt validate it?
user agent turned on with a blank UA - Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in C:\wamp\www\cidram4\vault\CIDRAM\CIDRAM\FrontEnd.php on line 3995

the extras error has gone !!

**Comment by Maikuolan** [comment]
> what does the focal switch do

The focal switch allows you to adjust the interface based on which is more important: Testing IP addresses, or testing user agents. (You can, of course, just the same as before, test both together without any problem).

When the focus is on IP addresses, the input for IP addresses supports multiple lines, but the input for user agents supports only single lines. When the focus is on user agents, the input for IP addresses supports only single lines, but the input for user agents supports multiple lines. Basically, if you wanted to test a range of different IP addresses at once, you would focus on IP addresses, whereas if you wanted to test a range of different user agents at once, you would focus on user agents. (If testing just one thing at a time, whether it be a single IP address or a single user agent, the difference isn't so meaningful).

> I guess if the UA is turned off it doesnt validate it?

That *should* be the case, but I'll check on that error you've cited just now, in case I've coded somewhere wrong somewhere. '^^

> the extras error has gone !!

Great to hear. :-)

**Comment by Maikuolan** [comment]
> Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in C:\wamp\www\cidram4\vault\CIDRAM\CIDRAM\FrontEnd.php on line 3995

Fixed. :-)

**Comment by mikeruss1** [comment]
confirmed fixed - thanks !
