### ISSUE TITLE
Future Suggestion for Country block for sensitive pages

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#467]
Could we have in the future an option to block a country (with one of those two modules we have now) only if sensitive pages are accessed.

We already have that for abuseipdb.

**Comment by Maikuolan** [comment]
Sounds like a good idea. :+1:

**Comment by Maikuolan** [comment]
Working on this now.

**Comment by Maikuolan** [comment]
I've added "lookup strategy" configuration directives for both modules just now, for turning lookups on/off in entirety for both modules. Wondering whether I should take things further though; maybe add some other options for finer-tuning or something; not sure. Keeping this issue open for now.

**Comment by eurobank** [comment]
Thank you, i think this is a great feature.
