### ISSUE TITLE
Aux Rules - ASN

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#479]
Look at this log:

IP address: 45.8.17.54
Signatures reference: 45.8.17.0/24, auxiliary.yml:ASN - Leaseweb »
Why blocked: Cloud service ("CloudSRV Limited", L21537:F0, ), ASN - Leaseweb! 

----------------

But the ASN of Leaseweb are:

`ASN lookup = /^(396362|60781|396190|15003|395954|30633|205544)$/
ASN lookup = /^(394380|19148|7203|27411|393886|133752|8753|59253)$/`

and the ASN of 45.8.17.54 is AS62240 - Clouvider 

and my rule is:

ASN lookup = 62240

So something is wrong in all that.

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/8f1f4750-daaa-4caa-a848-e5c8ff6f4b0c)

**Comment by eurobank** [comment]
Ok, i see that this is an error probably of IP-API since in the cache i see:


![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/dee6e33e-a325-4d7d-acf5-04a59f7ac150)

**Comment by eurobank** [comment]
BUT IPAPI online shows otherwise:

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/920c25ed-380c-4cc3-859f-9a81b01b0599)

**Comment by Maikuolan** [comment]
Still showing AS60781 at the API demo page though.

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/c22a1940-479c-4d99-b5f7-59a9286dbf61)

I wonder whether maybe they're using different databases between the API demo page and their other lookup page? Not sure, but weird, in any case.

**Comment by Maikuolan** [comment]
BGPView's lookup page is correctly showing AS62240.

![bgpview](https://github.com/CIDRAM/CIDRAM/assets/12571108/a1948e3a-484c-49d2-a17e-5aebc5b76d41)

(Though it's unfortunate that for some IP addresses, some ASNs, it still seems to arbitrarily not work at all, showing nothing at all for those affected. Seems nothing is 100% reliable, at least, as it is right now).

**Comment by eurobank** [comment]
Yeap. Well since this is not a Cidram issue, there is nothing we can do about it ;)
