### ISSUE TITLE
Query command injection using Matomo

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#481]
I started using Matomo for analytics and other than one of my auxiliary rules tripping the firewall and having fixed that I have had no issues until today. I see in the CIDRAM logs that a user was _seemly_ blocked when they made a post which was an eBay link. I say seemly because I never saw that happen before with eBay links being posted prior. Also, the user was able to post the links. It was a one time infraction though so not permabanned via my CIDRAM rules. Still, the link was able to be posted.  The request method is POST and signature reference is extras.php:L167.  The reconstructed URI is:  `https://my_website(dot)com/cyclops/matomo.php?link= a very long obfuscated eBay link.`

It seems Matomo was responsible and how its interacting with CIDRAM. This is the first time I started using Matomo and it's been great, but it operates _kinda_like CIDRAM with a sort of hook via the overall_header_head_append. It looks like this:

> 
> <script>
>   var _paq = window._paq = window._paq || [];
>   /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
>   _paq.push(['trackPageView']);
>   _paq.push(['enableLinkTracking']);
>   (function() {
>     var u="https://my_website(dot)com/cyclops/";
>     _paq.push(['setTrackerUrl', u+'matomo.php']);
>     _paq.push(['setSiteId', '2']);
>     var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
>     g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
>   })();
> </script>
> <noscript><p><img src="https://my_website(dot)com/cyclops/matomo.php?idsite=2&amp;rec=1" style="border:0;" alt="" /></p></noscript>
> 
> 

I guess the remedy here is to somehow whitelist Matomo.php?

**Comment by Maikuolan** [comment]
Any chance you could share the query part of the blocked request (i.e., the `?link=` and onward)?

**Comment by 737simpilot** [comment]
Sure. This is query link =


> https%3A%2F%2Fwww.ebay.com%2Fitm%2F385769066725%3Fhash%3Ditem4dfcc00a9f%3Ag%3AdOIAAOSwTF1ktHJM%26amdata%3Denc%3AAQAIAAAA0A6d5Q46%2FWeFI%2BFFwAEi4icGyTxG5%2F2EoUMQxKg3I9T7F4Buffhj%2Foo3CaIPq7YYhbMJ2r8TN0JqV1WSdsfzDmKNnN8DrESx45f0PQ8UbPnwg1lbBNv49yIxFkJaE%2FMiQN5vF3dMThVPZFdUKWoHSlrHdcKx2y0Tz2J2x9KUnDuLyOR7nokvsOJFmMbexc3OI30ge83wBkqVHuOA0KltYqMkAsmOO%2BtyLEvrlenVmFUjiubDoarAIohhb4E%2BB1eO7WXPRp%2FGxTpriNaXk7q3igQ%3D%7Ctkp%3ABk9SR9SgvaOsYg&idsite=1&rec=1&r=128334&h=22&m=6&s=4&url=https%3A%2F%2Fmywebsite.net%2Fviewtopic.php%3Ff%3D10%26t%3D443%26p%3D4615%23p4615&urlref=https%3A%2F%2Fmywebsite.net%2Fposting.php%3Fmode%3Dreply%26f%3D10%26t%3D443&_id=e012b8d815ff0df5&_idn=0&send_image=0&_refts=0&cookie=1&res=412x915&pf_net=0&pf_srv=2047&pf_tfr=89&pf_dm1=223&pf_dm2=198&pf_onl=4&pv_id=1rRu7R&uadata=%7B%22brands%22%3A%5B%7B%22brand%22%3A%22Not.A%2FBrand%22%2C%22version%22%3A%228%22%7D%2C%7B%22brand%22%3A%22Chromium%22%2C%22version%22%3A%22114%22%7D%2C%7B%22brand%22%3A%22Google%20Chrome%22%2C%22version%22%3A%22114%22%7D%5D%2C%22platform%22%3A%22Android%22%7D

**Comment by 737simpilot** [comment]
Github put a space after `https%3A` and I don't know why.

**Comment by 737simpilot** [comment]
This is the reconstructed URI:


> https://website.com/cyclops/matomo.php?link=https%3A%2F%2Fwww.ebay.com%2Fitm%2F385769066725%3Fhash%3Ditem4dfcc00a9f%3Ag%3AdOIAAOSwTF1ktHJM%26amdata%3Denc%3AAQAIAAAA0A6d5Q46%2FWeFI%2BFFwAEi4icGyTxG5%2F2EoUMQxKg3I9T7F4Buffhj%2Foo3CaIPq7YYhbMJ2r8TN0JqV1WSdsfzDmKNnN8DrESx45f0PQ8UbPnwg1lbBNv49yIxFkJaE%2FMiQN5vF3dMThVPZFdUKWoHSlrHdcKx2y0Tz2J2x9KUnDuLyOR7nokvsOJFmMbexc3OI30ge83wBkqVHuOA0KltYqMkAsmOO%2BtyLEvrlenVmFUjiubDoarAIohhb4E%2BB1eO7WXPRp%2FGxTpriNaXk7q3igQ%3D%7Ctkp%3ABk9SR9SgvaOsYg&idsite=1&rec=1&r=128334&h=22&m=6&s=4&url=https%3A%2F%2Fmywebsite.net%2Fviewtopic.php%3Ff%3D10%26t%3D443%26p%3D4615%23p4615&urlref=https%3A%2F%2Fmywebsite.net%2Fposting.php%3Fmode%3Dreply%26f%3D10%26t%3D443&_id=e012b8d815ff0df5&_idn=0&send_image=0&_refts=0&cookie=1&res=412x915&pf_net=0&pf_srv=2047&pf_tfr=89&pf_dm1=223&pf_dm2=198&pf_onl=4&pv_id=1rRu7R&uadata=%7B%22brands%22%3A%5B%7B%22brand%22%3A%22Not.A%2FBrand%22%2C%22version%22%3A%228%22%7D%2C%7B%22brand%22%3A%22Chromium%22%2C%22version%22%3A%22114%22%7D%2C%7B%22brand%22%3A%22Google%20Chrome%22%2C%22version%22%3A%22114%22%7D%5D%2C%22platform%22%3A%22Android%22%7D

**Comment by 737simpilot** [comment]
The block quote didn't work. I'll try again. 

Edit- Github is being a massive POS right now with trying to add block quotes. It shouldn't parse like that.... you'd think...

**Comment by Maikuolan** [comment]
Good enough; Figured out which part is causing the problem. :+1:

Replying as I go, so haven't yet thought up an appropriate solution.

Anyhow, the part in the query where we have `%3D%7Ctkp%3A`, decodes internally as `=|tkp:`, and the `=|` part is triggering against this expression in the extras module: `/(?:["\'];|[;=]\|)/`; The signature in question identifying it as a "Query command injection".

The reason for checking for that particular character combination in the query is due to a number of attacks in the past making use of pipes within query parameters to attempt to inject commands into vulnerable webapps, CMS, forum systems, etc.

Given that you're not personally using one of the affected systems where that kind of attack could actually do something, typically, in such cases, I'd suggest simply bypassing the signature responsible for the false positive by checking against the block reason or similar, but the problem with that, as things are right now, is that there are at least 6 different signatures which cite the exact same block reason, some of which block a lot of other stuff we want to be blocking, so simply bypassing on the block reason would end up bypassing all those others signatures, too.

Do the affected requests *always* originate from `matomo.php`? If the entry point is always that exact same file, I could always just add a check for that file to the affected signature. That should effectively bypass Matomo from the module's side of things, without necessarily compromising anything for any vulnerable systems (given said vulnerable systems are not Matomo, and will generally have other, different entry points).

**Comment by 737simpilot** [comment]
> Do the affected requests always originate from matomo.php? If the entry point is always that exact same file, I could always just add a check for that file to the affected signature. That should effectively bypass Matomo from the module's side of things, without necessarily compromising anything for any vulnerable systems (given said vulnerable systems are not Matomo, and will generally have other, different entry points).

I do believe so. Though, this is the first time it's happened. This user has made other posts with eBay links before and I have not seen a block like this. It seems reasonable to conclude this block comes from matomo.php. And I also say that because I have an auxiliary rule that blocks ALL POST requests accept for POST requests I know need it. Yes, this is with phpBB and I've had that POST request rule in place now for at least 4 years I think and have had no real issues unless I goof on something. In this case when I installed Matomo it was making POST requests for GET requests on the website I think it was and I had to whitelist the directory to Matomo in my POST request auxiliary rule otherwise users were getting flat out blocked from the website. That URL I whitelisted looks like this: `https://my_website(dot)com/cyclops/matomo.php*` Well, here's the entire rule: 

> Security:
>  Method: "WinEx"
>  Logic: "Any"
>  Reason: "403"
>  Suppress output template: true
>  Block:
>   If matches:
>    Request_Method:
>     - "POST"
>   But not if matches:
>    rURI:


So it's reasonable to conclude whitelisting matomo.php would fix the issue. Then again, if a pipe or whatever query command injection were used to somehow hack Matomo then we have a problem. I guess it's a catch-22. 


I did see that `| tkp:` part after I URL decoded everything in CyberChef and wondered about it.  Do you happen to know what it is or is used for?

I find it very interesting that it is now I see this block since this never occurred before with previous eBay link posts. Maybe the user's Chrome browser did something to the link? 

And many thanks to the quick catch on that. 👍

**Comment by Maikuolan** [comment]
> I did see that `| tkp:` part after I URL decoded everything in CyberChef and wondered about it.  Do you happen to know what it is or is used for?

Honestly, no idea. I'd probably need to either contact the people at Matomo, or do some research of my own, to figure that out.

**Comment by 737simpilot** [comment]
Is there something I can add to the auxiliary rules until this is fixed? Because someone else just got the same block. It's the same `|tkp:`

**Comment by 737simpilot** [comment]
Found the issue. https://developer.ebay.com/api-docs/buy/static/ref-epn-link.html


That giant link and whatnot is part of eBay's EPN service. When one of my users posted an eBay link it just so happened to have that crap and it looks like Matomo was resolving the posted link and thus CIDRAM saw it and blocked it. 

So there's no whitelisting needed or anything and I've instructed my users to just post the simple link absent of all the tracking crap with the normal long eBay link one may copy from their address bar.

**Comment by Maikuolan** [comment]
Awesome. And nice sleuthing work there. :-) :+1:

**Comment by 737simpilot** [comment]
Well, ran into this issue again. 

Query:

`https%3A%2F%2Fwww.someweblink.com%2Fphoto%2F1987531746%2F%3Fpgid%3D%26gid%3D7807748%26page%3D1%26idx%3D24&idsite=1&rec=1&r=055797&h=15&m=38&s=19&url=https%3A%2F%2Fmywebsite.com%2Fviewtopic.php%3Ff%3D30%26t%3D708%26sid%3Dbfe88b5d1ec01d1af051076b9a08d22f&urlref=https%3A%2F%2Fmywebsite.com%2Fviewtopic.php%3Ff%3D30%26t%3D708&_id=5f3222e3bd7e1505&_idn=0&send_image=0&_refts=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1680x1050&pv_id=f47Vn7&uadata=%7B%7D
`

URL:

`https://mywebsite.com/cyclops/matomo.php?link=https%3A%2F%2Fwww.someweblink.com%2Fphoto%2F1285875689%2F%3Fpgid%3D%26gid%3D7918059%26page%3D0%26idx%3D12&idsite=1&rec=1&r=339866&h=15&m=34&s=48&url=https%3A%2F%2mywebsite.com%2Fviewtopic.php%3Ff%3D30%26t%3D706&urlref=https%3A%2F%2Fmywebsite.com%2Fviewforum.php%3Ff%3D30&_id=5f3222e3bd7e1505&_idn=0&send_image=0&_refts=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1680x1050&pv_id=BJuvgD&uadata=%7B%7D`


It stems from line 280 in the extras module. 

My band-aid for now is to just whitelist the URL: `https://mywebsite.com/cyclops/matomo.php?*` But I'm afraid that may introduce a security vulnerability since Matomo is like a middle man and if there is a real SQL injection it may get whitelisted. Is there a way to do this properly without making the extras module think there's an SQL injection due to Matomo and how it works?

Matomo is a privacy friendly alternative to Google Analytics.

**Comment by Maikuolan** [comment]
I've slightly adjusted the signature in question so that the particular link in question shouldn't be being blocked anymore. :-)

Given the nature of how Matomo works though, it wouldn't surprise me if we discover more issues like these in the future. All we can do is keep an eye on it and keep working on those issues when they crop up, I think.

**Comment by 737simpilot** [comment]
Thanks, Caleb. I'll test now and see if anything shows up in the log. Ideally, whitelisting Matomo would work, but due to the way Matomo works in how it seems like a man in the middle between all queries, if I whitelist Matomo then I'm sure an SQL attack could be leveraged against my website with relative ease. 

I guess it's good that I'm discovering this now that I deployed Matomo for my own analytics purposes, because others may use Matomo as well with CIDRAM and it's best we iron out the kinks as best we can as I come across them. 

I really like Matomo. It first gets me away from Google (a company I really don't care too much for lol), and I like Matomo's capabilities and interface. Matomo also offers my users a lot more privacy. Especially if it's a GDPR policy I need to follow. In theory I don't have to follow GDPR since I live in the U.S. and the origin (keyword there) server is located in the U.S. But never the less, Matomo offers a GDPR solution to analytics. So if anyone is reading this and would like a nice alternative to Google analytics, Matomo offers that. I run it server side with PDO. (I think it's PDO...)

**Comment by 737simpilot** [comment]
Forgot to update this. Just to report that the new code change works. I think I'll keep this open if there's another issue that pops up.
