### ISSUE TITLE
Issue with Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#484]
An IP is attacking me today and it is not blocked, while the ASN is blocked in aux rules.

![Screenshot (2)](https://github.com/CIDRAM/CIDRAM/assets/4467158/9261a830-3ceb-49ba-bc27-c441158c788f)

Checking the IP with Test IP, i get na error?

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/527fad62-72af-4f9b-967b-b942cf29c937)

Any ideas?

**Comment by eurobank** [comment]
ok, this seems again an ASN issue, a different ASN is reported by other service. Not a CIRDAM issue

**Comment by eurobank** [comment]
but still this

Blocked: Error – auxiliary.yml (1)

appears in all IPs i test. Why?

**Comment by eurobank** [comment]
And still not blocked while it should

![Screenshot (3)](https://github.com/CIDRAM/CIDRAM/assets/4467158/c6bf405c-61ed-4c30-bc01-7354b69f288f)

**Comment by eurobank** [comment]
It is blocked due to a different aux rule, empty agent.

![2023-07-29 11_57_26-CIDRAM – Logs — Mozilla Firefox](https://github.com/CIDRAM/CIDRAM/assets/4467158/f795625b-4d58-4458-947e-2ceb5e9ff0b5)

**Comment by Maikuolan** [comment]
Does your CIDRAM installation by any chance have error logging enabled (`logging➡error_log`)?

If not, no problem; It should still be possible to figure out what's going on here either way. But, if so, I'd be curious to see whether anything has been logged there which mentions auxiliary rules at all.

Because the IP test is raising an error warning for auxiliary rules, it's possible that more information might be being logged at the error logs whenever a real request is encountered where that rule is triggered.

**Comment by eurobank** [comment]
My error log doesn't exist, while enabled. Apparently no errors?

**Comment by eurobank** [comment]
Today, checking the same IP, doesn't produce any error:

`Blocked: Yes – ASN - Fibergrid
Tracking: Yes
Banned: No
Status code: 403 Forbidden`

**Comment by eurobank** [comment]
I think what happens is some malformed entry of mine (mistake) and regex fails.

I found an extra space inside some ( ) and also a double )) in a regex and fixed it.

Could that be it or some other i haven't found?

**Comment by Maikuolan** [comment]
Could be that. A broken regex could definitely both prevent the rule from executing properly and cause it to error out at the IP test page. Though, I would've also expected a broken regex to generate some kind of loggable error, so if that's the case, it's a little odd that nothing was logged while enabled.

If it seems to be working properly again now, and there's nothing logged, I'm not sure offhandedly what else we could do here. Should be all good now, I guess? Though, if the problem reappears, or if you spot anything else, let me know and we can try to dig further into it.
