### ISSUE TITLE
Again Issue with Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#485]
The issue was with IP 27.124.45.54 AS64050. It was blocked and banned due to agent regex:

ID: 1690700964-594354-1427787414 »
Date/Time: Sun, 30 Jul 2023 10:09:24 +0300 »
IP address: 27.124.45.54
User agent: python-requests/2.24.0 »
Signatures reference: auxiliary.yml:User Agents Regex 1 »
Why blocked: Banned, User Agents Regex 1! »
Reconstructed URI: xxxxxxxxxxxxxxxxxxxxxx/admin888.php »
Infractions: 67 »
Country code lookup: HK »
Request method: GET »
Hostname: - »

**But the ASN should have been blocked also and DIDN'T.**

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/b81aecd5-44ea-4513-8ad5-1eefb89b57ff)

Checking the IP with IP TEST i get

Blocked: Yes – ASN - VPNs & Attacks
Tracking: Yes
Banned: Yes
Status code: 503 Service Unavailable

--

So why that didn't work? Any ideas?

**Comment by eurobank** [comment]
I also see the in the cache of IP-API the IP cidr exists and correctly has the ASN. So it is not an ip-api lookup issue.

**Comment by Maikuolan** [comment]
Got caught up doing other stuff yesterday and today, so haven't had a chance to look into this yet. I'll look into it in the morning.

**Comment by Maikuolan** [comment]
Definitely should've blocked. Not yet sure why it didn't. Still looking into this.
