### ISSUE TITLE
No Automatic Report to IPDB?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#489]
Hi,

This

ID: 1691141834-064150-3616702456 »
Date/Time: Fri, 04 Aug 2023 12:37:14 +0300 »
IP address: 182.177.163.14 »
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko »
Signatures reference: extras.php:L236 »
Why blocked: POST RFI! »
Reconstructed URI: https : // zzzzzzzzzzzzzzz / xmlrpc.php »
Infractions: 1 »
Country code lookup: XX »
Request method: POST »
Hostname: - »

should or shouldn't be auto-reported to IPDB?

**Comment by Maikuolan** [comment]
> should or shouldn't be auto-reported to IPDB?

I agree, it should be being reported. Anyway, fixed now. :-)
