### ISSUE TITLE
BingPreview being blocked

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#49]
```
ID: 113
Script Version: CIDRAM v1.3.0
Date/Time: Mon, 25 Dec 2017 13:37:14 +0530
IP Address: 65.55.210.175
Signatures Count: 1
Signatures Reference: 65.55.208.0/21
Why Blocked: Cloud service ("Azure", L18153:F0)!
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534+ (KHTML, like Gecko) BingPreview/1.0b
```

More Information is [here](https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0).

The IP is actually from Microsoft bingbot

**Feature Request:**

-  option/button to clear **logs file** just like statics?

**Comment by DanielRuf** [comment]
Well, it is Azure / cloud hosting. There could be anything.

Not sure if Microsoft has specific IPs for BingPreview. We can not rely on useragent strings.

You can whitelist the IP or IP ranges.

**Comment by harryqt** [comment]
@DanielRuf we can do, hostname lookup. ;)

**Comment by DanielRuf** [comment]
The hostname is msnbot-65-55-210-175.search.msn.com which is a normal searchbot hostname. Not directly connected to BingPreview.

https://bgp.he.net/ip/65.55.210.175

**Comment by DanielRuf** [comment]
You can just allow msnbot hostnames. There are no more reliable ways imho.

**Comment by harryqt** [comment]
I already allowing **BingPreview** user-agent, but I know it's not a good idea, let's see what @Maikuolan thoughts in this.

**Comment by Maikuolan** [comment]
All above points are valid, which.. makes it somewhat complicated (relative to verifying things like Googlebot, for example, which tends to keep predictably to specific ranges and doesn't interlace with Google's own cloud service, unlike Bingbot/MSNbot, which is sometimes seen across various different ASNs, and interlaces regularly with the Azure cloud service). Becomes trickier too, with certain specific hosting providers where hostname lookups frequently fail, or block lookups entirely.

Currently experimenting with code to try to figure out the best way to approach this. Thanks for reporting this, and I'll reply again as soon as I've got something workable.

**Comment by Maikuolan** [comment]
> **Feature Request:**
>
> -  option/button to clear **logs file** just like statics?

Simplest solution here (re: clearing logfiles) would be to just delete or rename the actual logfiles in question, which'd essentially achieve the same result. If you search for the name of the logfile via the File Manager and use the option there to delete it, it'll disappear, and a fresh logfile will be created anew the next time something gets blocked. :-)

**Comment by Maikuolan** [comment]
Latest commit should fix the problem, for now. Kind of still want to improve on this at some point though, because although the fix should work, it isn't quite as clean or elegant or as I'd like, and I feel that there's room for improvement, but for now, at least, if the problem is fixed, improvements can be made in the future whenever, and there's time to figure it all out. Anyhow.. As usual, please report if problems continue. :-)
