### ISSUE TITLE
Pinterest ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#492]
not sure whats going on here ?

ID: 1691426873-061528-3737475599
Date/Time: Mon, 07 Aug 2023 17:47:53 +0100
IP address: 54.236.1.11
Query: -
User agent: Mozilla/5.0 (compatible; Pinterestbot/1.0; +http://www.pinterest.com/bot.html)
Signatures count: 1
Signatures reference: bobuam.php:L95
Why blocked: Suspected bot or scraper probe!
Reconstructed URI: https://www.xxx/yyy.php
Infractions: 0
Verified identity: Pinterest
Request method: GET
Protocol: HTTP/1.1
Hostname: crawl-54-236-1-11.pinterest.com
CAPTCHA state: Enabled.

its verified as Pinterest, Infractions is 0, yet its delivering a 403?

**Comment by Maikuolan** [comment]
Looks like BOBUAM is blocking Pinterest. I'll fix that now.

**Comment by Maikuolan** [comment]
Done. :-)
