### ISSUE TITLE
Bingbot being blocked ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#495]
ID: 1691961793-538912-4214869363
 Date/Time: Sun, 13 Aug 2023 22:23:13 +0100 
IP address: 52.167.144.122 
Query: - 
User agent: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36 
Signatures count: 1 
Signatures reference: extras.php:L112 
Why blocked: Probing for webshells/backdoors! 
Reconstructed URI: https://www.xxx/warloss_233italy.php 
Infractions: 1 
Request method: GET 
Protocol: HTTP/1.1 
Hostname: msnbot-52-167-144-122.search.msn.com 
CAPTCHA state: Disabled.

this looks like a valid Bingbot from a known Bingbot IP address that I get lots of requests from. Related to the recent extras update? Lots of similar requests accepted, maybe the unusual URL - which is valid?

never seen this extras block before and dont see any probing?

**Comment by Maikuolan** [comment]
> Related to the recent extras update? Lots of similar requests accepted, maybe the unusual URL - which is valid?

Yep and yep. False positive. Should be fixed now. :-)
