### ISSUE TITLE
Found why we are rate limited in lookups

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#496]
Every time i see  a Rate Limited from IP-API (but i guess from others also), the same thing happend according to the log. 

Massive Simultanous visits and the Country Code Lookup is ALWAYS:xx.

So apparently CIDRAM tries to Lookup massively at the same time and gets rate limited.

Here is an example, this IP did 43 hits within a few seconds.

---

ID: 1691961805-234302-5600396798 »
Date/Time: Mon, 14 Aug 2023 00:23:25 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 33 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961804-867953-5234049920 »
Date/Time: Mon, 14 Aug 2023 00:23:24 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 32 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961804-826245-5192337023 »
Date/Time: Mon, 14 Aug 2023 00:23:24 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 31 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961801-174220-1540322925 »
Date/Time: Mon, 14 Aug 2023 00:23:21 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 30 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961800-111682-0477775985 »
Date/Time: Mon, 14 Aug 2023 00:23:20 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 29 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961800-099838-0465932670 »
Date/Time: Mon, 14 Aug 2023 00:23:20 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Hostnames Regex 1! »

Infractions: 28 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961797-296085-7662178650 »
Date/Time: Mon, 14 Aug 2023 00:23:17 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: extras.php:L74, auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Probing for unsecured backup files not allowed, Hostnames Regex 1! »

Infractions: 27 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961797-228849-7594941764 »
Date/Time: Mon, 14 Aug 2023 00:23:17 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: extras.php:L74, auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Probing for unsecured backup files not allowed, Hostnames Regex 1! »

Infractions: 25 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

ID: 1691961797-189891-7555983108 »
Date/Time: Mon, 14 Aug 2023 00:23:17 +0300 »
IP address: 172.232.36.101 »
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 »
Signatures reference: extras.php:L74, auxiliary.yml:Hostnames Regex 1 »
Why blocked: Banned, Probing for unsecured backup files not allowed, Hostnames Regex 1! »

Infractions: 23 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-232-36-101.ip.linodeusercontent.com »

--

So can CIDRAM somehow limit or avoid this? I mean doing simultaneous lookups at the very same time?

**Comment by Maikuolan** [comment]
It's due to race conditions between multiple PHP processes at the same environment. Not sure whether I can really do much about that, other than maybe playing with file locks or something. I'll ask around to see whether anyone I know has any ideas.

**Comment by eurobank** [comment]
https://www.php.net/manual/en/intro.sem.php  ?
