### ISSUE TITLE
AbuseIPDB Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#497]
It seems what while the log says the IP is blocked due to AbuseIPDB, it is not. I see the IPs in the live traffic of the Wordpress site.

This happens only with AbuseIPDB, all other blocked IPs (from aux rules for example) do block the IP.

Any ideas? I use AbuseIPDB sensitive only pages (login/register/passwords).

**Comment by Maikuolan** [comment]
Not sure offhandedly. I'll look into it though.

**Comment by Maikuolan** [comment]
Could it be that the AbuseIPDB module is blocking *some* requests from the IP address, while *other* requests are successfully getting through (i.e., some pages at the WordPress website aren't being fully covered by CIDRAM, but trigger the mechanism in WordPress for monitoring live traffic, causing the IP address to appear in both CIDRAM's logs as well as WordPress' live traffic)? Just speculating.
