### ISSUE TITLE
Reported but not logged

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#498]
Recently had the CIDRAM installation at one of the websites that I help manage report my own IP address to AbuseIPDB, citing in the report that a hack attempt was detected. I assumed, some kind of false positive caused by a signature in the extras module (given that it cites "hack attempt" as a reason for a number of its signatures), but despite having all forms of logging enabled, there's zero block events in any of the logs for my own IP address, and I also never saw any access denied page. I've already removed the report at AbuseIPDB (easy enough to do, given it was reported by one of my own API keys). Given the lack of any available log information though, it's tricky to diagnose which signature might be falsing, if any at all, or whether there might be something else going on.

I've manually gone through my entire browsing history for the website in question covering the past few days, running those queries against the IP test page to see whether it triggers anything, but nothing got triggered, so no luck there. The block event appears to be non-reproducible. So, I have no idea.

Just creating this issue to ask, if anyone else encounters a similar problem (i.e., having your own IP address being mistakenly reported citing a "hack attempt"), if you happen to have any log information available, or happen to actually see an access denied page, providing some kind of clue, please consider sharing the information, to help me isolate what could be causing the problem.

If not, then.. fingers crossed, some kind of freak, isolated event, unlikely to ever reoccur. Not fun not knowing though, and naturally, it's preferable for software and code in general to behave in predictable ways.

**Comment by mikeruss1** [comment]
are you sure it originates from CIDRAM, its not some code from the website itself, or a hosting service option?

**Comment by Maikuolan** [comment]
The structure for the report utilised CIDRAM's own specific report structure (e.g., like *"Automated report (20xx-xx-xxThh:mm:ss+xx:xx). Something detected. Reason for report here."*), and the API key in question shouldn't be being used anywhere other than at the specific CIDRAM installation in question (I use separate keys for each installation I maintain, in order to make it easier to diagnose when problems occur, to be able to delete any keys in case they become compromised at some point in the future without the need to change keys at every unaffected installation, etc).

But.. I've also recently had that same website try to send out emails to some of its users, citing a sender address which hasn't actually been actively used anywhere at all for almost three years now, and which, AFAICT, wasn't mentioned *anywhere* in any of that website's databases, in any software settings, configuration, in any hard files, or anywhere else (I went to the extent of FTPing the entire website from the server to my machine, in order to use HDSearch to check for any occurrences of the email address in question in any of the files, dumping the SQL database to sift through all tables, etc, all with no luck). Did find it though, after all that, just half an hour ago or so, cited as the original email address for the registrant in the whois records for the domain in question, which I've changed to the correct, current address just now. No idea why or how whois records would or could have any effect on the sender for outbound emails at the application level, but I couldn't find the address cited anywhere else, so.. we'll see whether that does anything, I guess.

That kind of weirdness in combination with the weirdness of a report to AbuseIPDB which doesn't seem to have any corresponding logged block event, I have no idea. Contemplating contacting the host to get them to look into it, but want to exhaust all possibilities at my end beforehand if possible, in case it's something I can solve all from my end, to avoid sounding clueless to them or wasting their time more than necessary, or my own time, in case they end up not being able to do anything themselves.

**Comment by mikeruss1** [comment]
clutching at straws, fake IP address?
have you checked the site log for that time and IP address, check the UA and related GETS?

**Comment by Maikuolan** [comment]
Seems that the hosting provider for the website in question discards the raw access logs every few hours, so looks like I won't be able to see the particular records in question, unfortunately.

I have a few ideas to try out later today though, if I have time.

**Comment by Maikuolan** [comment]
Yeah.. No luck. It hasn't happened again since the time I posted this issue though, so.. whatever the reason may be for it happening in the first place, hopefully it isn't something that should happen too often. Would really much prefer to be able to actually understand what exactly caused it in the first place, but given the failure to log anything, the hosting provider not keeping access logs available, and being unable to replicate the problem.. I think I'll need to just let it go for now and mark it as can't replicate.
