### ISSUE TITLE
CIDRAM blocking Itself :)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#503]
Query: cidram-page=backup
Signatures reference: extras.php:L74 
Why blocked: Probing for unsecured backup files not allowed!
Reconstructed URI: https : // www . xxxxxx . tld / hidden_for_security_admin.php?cidram-page=backup

:)

**Comment by Maikuolan** [comment]
Whoops. XD

I'll get that sorted out now.

**Comment by Maikuolan** [comment]
Should be fixed now. :-)
