### ISSUE TITLE
Statistics Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#506]
I have an Aux Rule 

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/cef05076-1963-46a5-9f1a-dbabe4678a22)

that while it IS logged

User agent: - »
Signatures reference: auxiliary.yml:Empty User Agent »
Why blocked: Empty User Agent! »
Infractions: 8 »

it is not anywhere in Statistics. Any ideas? Are statistics realtime?

**Comment by Maikuolan** [comment]
Has the *"Track this rule"* option under the *"Statistics:"* dropdown menu for that rule been selected?

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/52f17bc8-9c05-4ade-9442-d9c2ceae240f)

**Comment by eurobank** [comment]
Actully it is Leave it as it is .....

Mea culpa.
