### ISSUE TITLE
Question/Request - Blocking Proxies

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#515]
IP-API api returns also if the IP is PROXY, as i see.

> "mobile": false,
>     "proxy": true,
>     "hosting": true

Can we optionally use that to block somehow proxies?

**Comment by eurobank** [comment]
It can either be an option in IP-API settings, or a aux rule or whatever @Maikuolan thinks it is better.

**Comment by Maikuolan** [comment]
I have an idea about how that could be done. I'll experiment a little on this idea soon. :-)

**Comment by Maikuolan** [comment]
The latest update will profile the request wherever any IP-API lookups have been performed, if/when the lookup identifies the IP address being looked up as a proxy, hoster, or mobile endpoint. Worth noting though: It's still a lookup, so the lookup strategy still applies (so, the profiles won't be populated unless a lookup has occurred, or a lookup has been cached, and if the request at hand applies per the lookup strategy for the module).

To leverage it, an auxiliary rule can check for the following profiles:
- Mobile ISP
- Proxy
- Webhosting

**Comment by eurobank** [comment]
let's see how it works, plenty of attacks from proxies lately.

**Comment by eurobank** [comment]
@Maikuolan I see the profiles but how to use all that?

**Comment by Maikuolan** [comment]
When creating/editing an auxiliary rule, to leverage the profiles, just add a condition to check for the names of the profiles needed. :-)

![Untitled](https://github.com/CIDRAM/CIDRAM/assets/12571108/6fcccd41-c1cf-4d43-8832-4f0b7f30ca3c)

**Comment by eurobank** [comment]
Thanks works as it should. But most of the visits are reported as proxy, correctly, still not what exactly to the point.

**Comment by eurobank** [comment]
Also a total clear of the caching is needed, actually it is needed in most major changes.
