### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: fwrite()

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#516]
PHP Fatal error:  Uncaught TypeError: fwrite(): Argument # 1 ($stream) must be of type resource, bool given in /home/xxxxxx/vault/events/default.php:35

**Comment by eurobank** [comment]
btw: Also could that coming from your script?

![2023-09-17 19_38_42-FileZilla](https://github.com/CIDRAM/CIDRAM/assets/4467158/ce624a51-6699-47f5-bdf8-2bd6e1f36ab1)

**Comment by Maikuolan** [comment]
Cheers. I've sorted out a fix for that just now. I just need to finish up some other changes I've been working on the past few days first, so that I can prepare a clean commit before pushing everything. Should have that sorted out soon. :-)

**Comment by Maikuolan** [comment]
Done. :-)
