### ISSUE TITLE
Request for Live View of all connection

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#520]
I would kindly ask you to consider a new menu option, where we can view LIVE traffic (all connections) as they happen. 

Nothing fancy, just the connections as they come in. You already do that somehow in Rate Limit page (kind of).

Date/Time-IP-URL-User Agent.

**Comment by Maikuolan** [comment]
Multiple ways I could go about this, but still investigating which way would be the best way to go about this (to avoid performance issues and such). I'll reply back again later.
