### ISSUE TITLE
Idea to minimize APIs Rate Limits

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#525]
Take a look at this example:

ID: 1696810099-761437-0696458116 »
Date/Time: Mon, 09 Oct 2023 03:08:19 +0300 »
IP address: 172.104.28.113 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 »
Signatures reference: auxiliary.yml:Hostnames Regex »
Why blocked: Hostnames Regex! »
Infractions: 3 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-104-28-113.ip.linodeusercontent.com »

ID: 1696810099-631844-0566857262 »
Date/Time: Mon, 09 Oct 2023 03:08:19 +0300 »
IP address: 172.104.28.113 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 »
Signatures reference: auxiliary.yml:Hostnames Regex »
Why blocked: Hostnames Regex! »
Infractions: 2 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-104-28-113.ip.linodeusercontent.com »

ID: 1696810099-651438-0586464165 »
Date/Time: Mon, 09 Oct 2023 03:08:19 +0300 »
IP address: 172.104.28.113 »
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0 »
Signatures reference: auxiliary.yml:Hostnames Regex »
Why blocked: Hostnames Regex! »
Infractions: 1 »
Country code lookup: XX »
Request method: GET »
Hostname: 172-104-28-113.ip.linodeusercontent.com »

Those 3 hits were rate limited by IP-API. Hence the Country code:xx, since that ASN is blocked with an Aux Rule.  But it was blocked by an other aux rule. But all the IPs are the same, all the 3 hits at the same time are from the same IP.

So i was thinking that a simple check when contacting the IP-API, if the IPs are the same could solve this issue? So only one is allowed?

@Maikuolan Can that be done technically?

**Comment by Maikuolan** [comment]
Normally, the results of the lookups should be being cached. Is that not happening here?

**Comment by eurobank** [comment]
The lookups are probably new but happening all 3 at ONCE.

**Comment by Maikuolan** [comment]
Ah, okay. I see. Yeah.. That's a problem. Not really sure how to fix this offhandedly, but I'll ask around a bit.

**Comment by eurobank** [comment]
I see several issues that i opened about it and i'm closing them. Apparently it can't be done techically.
