### ISSUE TITLE
Recaptcha submit

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#526]
I am getting an excess label on the recaptcha screen, been happening for a while. Please see attached pic. Press submit still works OK

![Clipboard01](https://github.com/CIDRAM/CIDRAM/assets/26255535/87008f55-6bc7-497c-b0e2-b360fce63f29)

**Comment by Maikuolan** [comment]
Working on this now. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by mikeruss1** [comment]
thanks !
