### ISSUE TITLE
Updates suggestion

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#530]
if there are module updates to be done, we need to update each individually. Maybe have a tick box or something then they can be updated all together? No priority, maybe next major version.

**Comment by Maikuolan** [comment]
Have actually kind of wanted something like that myself for a long time, too. So.. I agree. Just hadn't quite yet figured out how to make it work properly with the existing code. '^^

Considering it as on the to-do list. :-)
