### ISSUE TITLE
Aux Rules Editor

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#532]
I added a User Agent

wp_is_mobile in a regex and then escaped it

wp\_is\_mobile

and then, after saving, the underscores were gone and became spaces?

**Comment by Maikuolan** [comment]
Confirmed. The problem seems to be due to the way the YAML handler escapes and unescapes backslashes and non-breaking spaces. Investigating possible solutions now.

**Comment by Maikuolan** [comment]
Should be fixed now. :-)
