### ISSUE TITLE
Redis down

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#534]
just discovered that redis was out for a few hours a few days ago

as far as I can tell it looks like CIDRAM picked up the flat file cache in whatever state it was in, then when redis came back, Redis dump was restored and CIDRAM reverted and continued with redis cache. So whatever happened while it was down was lost, but integrity is fine.

does that make sense?

**Comment by Maikuolan** [comment]
Yep, makes sense. :-)
