### ISSUE TITLE
The problem with the display in the logs.

### ISSUE THREAD

**Issue by vitprotas** [CIDRAM/CIDRAM#535]
Greetings and thank you for your work, over this project!
I am learning CIDRAM for a little more than a month, the possibilities are impressive!
But after the last update, there are problems with the appearance of the logs. A large picture, for each blocked host, a picture appears with reference to the AbuseIPB. The screenshot attached.
![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/75327472/a5eb49a4-838b-442b-b924-2a753088d4ed)
I have some problems or do I need?

Sincerely and all the best.

**Comment by Maikuolan** [comment]
The dimensions for that image should be being enforced by CIDRAM's CSS. I suspect, most likely, after the update, although now updated, the browser has cached CIDRAM's CSS file from before the update, causing the image the appear huge like that.

Try a hard refresh on the page (for most browsers, achieved by pressing Ctrl+F5) and let me know whether the problem persists. :-)

(I'm thinking I might try tinkering with the image a little later though anyway, to try to prevent this problem from occurring in the future, as the problem could potentially affect multiple users).

**Comment by vitprotas** [comment]
> The dimensions for that image should be being enforced by CIDRAM's CSS. I suspect, most likely, after the update, although now updated, the browser has cached CIDRAM's CSS file from before the update, causing the image the appear huge like that.
> 
> Try a hard refresh on the page (for most browsers, achieved by pressing Ctrl+F5) and let me know whether the problem persists. :-)
> 
> (I'm thinking I might try tinkering with the image a little later though anyway, to try to prevent this problem from occurring in the future, as the problem could potentially affect multiple users).

[Maikuolan](https://github.com/Maikuolan) thank you for the response! Problem solved. I cleaned the cache in the browser and panel, the tab data cache. The cache of these data is to delete:
LOGIN_5738aa0e7223743ca6218a7920970fd8e3d33887f8bef6b83979dac01bbe2c85

**Comment by Maikuolan** [comment]
Happy to help. :-)
