### ISSUE TITLE
Some corrections for signatures data

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#536]
Hi,

It seems that Choopa LLC, is actually The Constant Company (along with Vultr).

Also this seems like duplicate

Signatures reference: 192.185.64.0/18, 192.185.64.0/18
Why blocked: Cloud service ("WEBSITEWELCOME.COM", L24225:F0, ), Cloud service ("Network Solutions, LLC", L46500:F0,

Thanks

**Comment by Maikuolan** [comment]
Thanks for spotting these. Should be fixed now. :-)
