### ISSUE TITLE
Request about REDIS

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#540]
Hello.

Can we have a DATABASE name prefix and Number in REDIS setup? So we can use multiple sites using one redis?

Thanks

*** like in Wordpress for example:

// change the prefix and database for each site to avoid cache data collisions
define( 'WP_REDIS_PREFIX', 'mywebsite' );
define( 'WP_REDIS_DATABASE', 0 ); // 0-15

**Comment by mikeruss1** [comment]
check the first option ... supplementary_cache_options➡prefix:

whatever you enter is placed before the data name if cache, or DB name if mysql (I think)

**Comment by eurobank** [comment]
@mikeruss1 I don't think it works that way. Does it? I don't know. In my case, even that i can't use it, since CIDRAM (one instance) is used by more than 1 sites.

Also what about DB number?

**Comment by eurobank** [comment]
@Maikuolan Will the currect options work for me?

**Comment by mikeruss1** [comment]
I would guess if its only 1 CIDRAM processing multiple sites, there needs to be some way of carrying forward the site identity within the REDIS data names?

**Comment by eurobank** [comment]
After some reading, i think the prefix is enough for separation and the database number can be the same. Actually it should be the same for performance matters.

Am i getting this right?

**Comment by mikeruss1** [comment]
if you want your sites treated as one whole, so a block from one will affect all, then it should work. You can run Redis on a PC so if you have a wampserver then test it to make sure its what you want?

**Comment by eurobank** [comment]
I think my question was if we can use a different database NUMBER with CIDRAM.

**Comment by mikeruss1** [comment]
I think I am running out of knowledge and you need to wait for maikuolan. My understanding is Redis stores data items and is not a DB like mysql in the normal use of the word. You also need to be aware that storage is in memory, and therefore subject to loss.

**Comment by eurobank** [comment]
In Wordpress, you have to use a prefix for each site AND a different DB number. If you dont' use a different DB number (from what i'm told, i never tried it), each time you flush a site, all the sites are flushed.

So we have 0-15 db numbers available for use. 

I do like Redis a lot, main reason is that (for Wordpress sites) MariaDB seems to be very very happy when Redis is used.

**Comment by Maikuolan** [comment]
I've been doing some reading up about Redis database numbers. To be able to support that, I'm going to need to update some of the cache code first, as there's a specific command Redis uses to specify the database number to use which CIDRAM's cache code isn't currently using. I'll work on that soon. :-)

**Comment by Maikuolan** [comment]
I've pushed some updates just now. After updating, you should see a new configuration directive appear, __`supplementary_cache_options➡redis_database_number`__. :-)

**Comment by eurobank** [comment]
Thanks, updated now and i will report any (if any) issues or findings the next 24 hours...

**Comment by eurobank** [comment]
I don't see any issues, so all ok. Thanks :)
