### ISSUE TITLE
Restore question

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#545]
if I have a backup of all the options which is running on a Redis cache. then change the config to flat files and restore everything apart from the config, will that give me a duplicate setup but running on flat files? And use a reverse method to go from flat files to Redis?

**Comment by Maikuolan** [comment]
I assume you're referring to using the front-end backup page? For the most part, yes. Using the front-end backup page to create backups of data, changing from one caching mechanism to another, and then restoring from that backup, will effectively transfer that backed up data over to the newly chosen caching mechanism (where said data would typically be stored in the cache, that is). Take in mind, however, that not the entirety of all data (and all cache data) is backed up in the first place at the backup page (..yet). Of the data typically stored in the cache, the backup page currently can export/import IP tracking data and statistics. So, things like login sessions, API lookup results, temporary 2FA codes (which expire after 10 minutes anyway) and things like that aren't currently touched on at all by the backup page.

![Backup](https://github.com/CIDRAM/CIDRAM/assets/12571108/289e13b0-6c6d-4225-9f56-d18a1b4426ce)

Or do you mean something else? Not 100% sure I'm understanding correctly.

**Comment by mikeruss1** [comment]
thanks, yes thats what I meant

**Comment by mikeruss1** [comment]
tried going from flat files to Redis, all OK. It took a very long time, nearly a minute. It updated everything I hadnt, modules, languages, signatures, templates. 
Only concern, the Start Date looked much older than I expected Sept 22 with a time that was the update time.
in the backup it is set as
Since: 1662471453
This might just be my memory !
