### ISSUE TITLE
Can't Create / Edit / Save Aux Rules

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#547]
It seems that i can't create an Aux Rule or Edit one. 

No errors anywhere but the changes are not reflected.

**Comment by Maikuolan** [comment]
I pushed a commit just now which should at least have it now state on the page that the update failed if/when it fails to update. Though it doesn't fix any particular cause to why it might be failing, it should at least give us a clue as to whether the failure is occurring when it tries to update, or at some other point (e.g., if it updates, but then something on the server reverts the file, or if file caching at the server could be interfering with CIDRAM's ability to read the latest versions of its own files, other unexpected problems, etc).

I haven't replicated any such problems at my end. Current best guess might be something going on with permissions, maybe somehow the CHMOD permissions for the file were unexpectedly modified?

**Comment by eurobank** [comment]
No, no permissions issue. I think a BIG rule is doing that. A rule with several lines i mean. I can't edit that rule.

I have reseached this a lot and find no errors anywhere.

The rule i suspect is:

`ASN - Dangerous – (Enable this rule) (Move up) (Move to the top) (Move down) (Move to the bottom) (Export) (Delete)

    The reason given to the user when blocked:
    ASN - Dangerous
    HTTP status code override:
    403 Forbidden
    If the following conditions are met, block the request.
    ASN lookup ≅ /^(8280|61272|56322|12322|91101|197648|35624|26548|43444|46805|20804|396949|24768|62240|13213|15895)$/
    ASN lookup ≅ /^(64050|43289|40021|211936|35830|49581|43513|55256|210743|30693|212219|264850|206804|42831|40676)$/
    ASN lookup ≅ /^(39351|211760|43357|262287|36007|41436|141995|13448|62164|20278|209372|211252|40676|22363|42708)$/
    ASN lookup ≅ /^(263829|18978|33387|208046|44364|52068|21769|394352|2926|20857|46261|51167|40021|40861)$/
    ASN lookup ≅ /^(56655|62874|50837|64080|197071|44477|53667|51430|211138|210352|204601|394711|62005|24961|48635)$/
    ASN lookup ≅ /^(206092|206150|834|394474|26347|210558|22772|137409|51747|12552|8100|29761|42708)$/
    ASN lookup ≅ /^(39486|204287|134450|136557)$/
    Other options and special flags:
    Track this rule
    Disable this rule
    Use regular expressions to test the conditions.
    Any "equals" (=) conditions may trigger the rule, as long as all "not equals" (≠) conditions are also met.

`

**Comment by eurobank** [comment]
@Maikuolan Please take a look at the video. It is all in there.

1. I edit the Top Dangerous rule and i remove ONE line. Save and ALL OK.
2. I try to rename the Top rule (Dangerous) and it fails for the Name.
3. I create a New Rule for test at the bottom, Dangerous # 2. All ok.
4. I edit the TOP Dangerous rule and again i can't
5. The Bottom Dangerous Rule # 2 is GONE !!!!!!!!!!!!!!!!!!!

I hope that helps you. This is the best information i can give for the issue.

https://drive.google.com/file/d/18QWlCEXnY21vmo_KxulKABQRcNWqzhhx/view?usp=sharing

**Comment by Maikuolan** [comment]
Cheers; That helps. Found the problem. :+1:

Investigating possible solutions now.

**Comment by eurobank** [comment]
No Rush :)

**Comment by Maikuolan** [comment]
Should be fixed now. :-)

**Comment by eurobank** [comment]
Seems to be fine now ...
