### ISSUE TITLE
Two Duplicate / Wrong Companies in Signatures

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#548]
Signatures reference: 5.35.32.0/21, 5.35.33.0/24 »

Why blocked: Cloud service ("Hosting technology LTD", L30683:F0, ), Attacks ("OOO Trivon Networks", L20620:F2, )! 

&

Signatures reference: 192.210.128.0/18, 192.210.128.0/22

Why blocked: Cloud service ("ColoCrossing", L5096:F0, ), Cloud service ("B2 Net Solutions", L21071:F0, )

**Comment by Maikuolan** [comment]
Seems the IP addresses covered by the "OOO Trivon Networks" section were already being covered *in entirety* by the "Hosting technology LTD" section, making the "OOO Trivon Networks" section redundant, so I've gone ahead and removed that section. :-)

The other affected sections have been updated, but not sure yet what the do with the remaining duplicates. Will try to get to those at the next update.

**Comment by eurobank** [comment]
Ok, my topics about them are more **informative** than an issue, so ....
