### ISSUE TITLE
When ASN (or other) lookups api fail

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#550]
I have openeded here some related issues but this time i have details.

Look at the following:

Date/Time: Sat, 09 Dec 2023 17:11:52 +0200 »
IP address: 23.82.109.198 »
Signatures reference: auxiliary.yml:Host Names »
Why blocked: Host Names! »
Reconstructed URI: https: removed /contact »
Infractions: 1 »
Country code lookup: XX »
Hostname: ip198.ip-23-82-109.mpp.il.com »

--

ID: 1702134712-260871-5304446306 »
Date/Time: Sat, 09 Dec 2023 17:11:52 +0200 »
IP address: 23.82.109.198 »
Signatures reference: auxiliary.yml:Host Names »
Why blocked: Host Names! »
Reconstructed URI: https: removed /contact »
Infractions: 1 »
Country code lookup: XX »
Hostname: ip198.ip-23-82-109.mpp.il.com »

--

ID: 1702134715-564708-8608272053 »
Date/Time: Sat, 09 Dec 2023 17:11:55 +0200 »
IP address: 172.241.247.190 »
Signatures reference: auxiliary.yml:Host Names »
Why blocked: Host Names! »
Reconstructed URI: https:// removed /contact »
Infractions: 1 »
Country code lookup: XX »
Hostname: ip190.ip-172-241-247.mpp.dc.com »

--

I got 22 of those in less than 15 seconds and apparently the lookup failed. Rate Limited? If so, the 1st should have been ok and the rest blocked. Something else happened? I dunno.

Apparently when a storm of hits happen, the lookups fail. And storms like that are very very often nowadays.

And the hits were (thankfully) blocked due to "hostnames" aux rule i have (*.mpp.*) and not due to ASN. Otherwise they would have passed and not blocked.

I'm not a developer so i don't know if this can be somehow solved or improved. Still it is an issue of blocking or not. An important one i think.

**Comment by eurobank** [comment]
@Maikuolan 

Could we possibly use a local db for ASNs, like

https://dev.maxmind.com/geoip/docs/databases/asn

what do you think?

**Comment by Maikuolan** [comment]
Their data is licensed under the Apache license, which AFAICT, seems compatible with CIDRAM's licensing (GNU/GPLv2), so shouldn't be a problem there. It's provided via an account portal though, which means that getting it would require being logged in at their website (foregoing the availability of any APIs or similar as a means of getting it; I haven't yet investigated whether that might be a possibility, so I'll need to do that).

I'll call it a tentative "maybe" for now, I think. I'll need to look into it a bit further.
