### ISSUE TITLE
Wrong block AI

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#553]
40.84.180.224 is blocked due to Fake GPT but it is legitimate Ips.

https://platform.openai.com/docs/plugins/production

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by eurobank** [comment]
This doesn't seem fixed

ID: 1703331740-862345-0972036875 »
Date/Time: Sat, 23 Dec 2023 13:42:20 +0200 »
IP address: 40.84.180.232 »
User agent: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; ChatGPT-User/1.0; +https://openai.com/bot »
Signatures reference: Core.php:L3184 »
Why blocked: Fake ChatGPT-User »
Infractions: 4 »
Country code lookup: US »
Request method: GET »
Hostname: - »

**Comment by Maikuolan** [comment]
Should be okay now.
