### ISSUE TITLE
An other User Agent to block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#557]
I see that along with "mozlila" or standalone, a user agent i see in a lot of attacks is "moblie".

**Comment by eurobank** [comment]
for example:

User agent: **Mozlila**/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 **Moblie** Safari/537.36

**Comment by Maikuolan** [comment]
Previously had "Moblie Safari" blocked via the bot UAs module already, but I've modified it to now block just on "Moblie", too. :-)
