### ISSUE TITLE
Check IP

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#560]
Any ideas what Error means?

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/1c30d601-37ea-4b5f-a671-0a91e698a777)

**Comment by Maikuolan** [comment]
The `auxiliary.yml (1)` indicates that 1 error occurred while attempting to process the auxiliary rules for the given test. Probably a typo somewhere in one of the regular expressions for one of the rules (regular expression typos tend to be the most common culprit behind that particular error message).

Any changes made recently to any auxiliary rules, or in particular, to any regular expressions in any of the rules?

**Comment by eurobank** [comment]
Well no  changes recently, this must be there for a long time without me knowing.

I will check.
