### ISSUE TITLE
404 Support and Block

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#561]
Hi,

How feasible is the support for somekind of multiple 404 hits check and then ban after a number? 

We could exclude some urls from it maybe like

/favicon.ico
/apple-touch-icon*.png
/*@2x.png
/browserconfig.xml

Not sure how, a rule, a module or something else....

**Comment by mikeruss1** [comment]
I do this manually, wrote some code which scans the log each day and reports any unusual behaviour.

**Comment by Maikuolan** [comment]
Not sure. I'll investigate it a little a reply back later.
