### ISSUE TITLE
Wordpress: load CIDRAM with a snippet code. How?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#564]
In  a particular installation, i can't prepend anything more since auto prepend is already used.

So if there a way to include CIDRAM with a WP snippet (hook?) so i don't have to modify WP files in each update?

Any ideas?

**Comment by Maikuolan** [comment]
In the absence of the ability to use auto prepend, the easiest way to hook CIDRAM to WordPress, I think, would be to just create a simple, custom, one-page plugin to act as an entrypoint for CIDRAM.

Something like:
1. Creating a new directory, `/wp-content/plugins/cidram-entrypoint`.
2. Creating a new file, `/wp-content/plugins/cidram-entrypoint/cidram-entrypoint.php`, containing:
```PHP
<?php
/**
 * Plugin Name: CIDRAM Entrypoint
 * Version: 1.0.0
 * Description: A simple, custom, one-page entrypoint script for CIDRAM.
 */
 
require_once '/path/to/the/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();
```

Then, from your WordPress dashboard's plugin page, looking for "CIDRAM Entrypoint", and enabling it.

That way, CIDRAM should remain hooked up to WordPress, even after WordPress is updated, without the need to remodify any WordPress core files after each update.

**Comment by eurobank** [comment]
That is great, thank you !
