### ISSUE TITLE
Immunify

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#566]
did you get anywhere in engaging with Immunify to get default.php whitelisted - #558 and #556

I am getting a variation on the previous problem, its reporting it has blocked default.php even though its whitelisted, and it hasnt blocked it!

**Comment by Maikuolan** [comment]
Wasn't able to get anywhere with it, unfortunately. Not sure whether there's a better way to report false positives to Immunify, but what I tried before didn't seem to work, unfortunately.

**Comment by Maikuolan** [comment]
I've created a new ticket at their ticket tracker an hour or so ago. I'll reply back at #568 when I see a response from them.

**Comment by Maikuolan** [comment]
Fixed. :-)
