### ISSUE TITLE
Black hash triggering from Imunify360

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#568]
This time CIDRAM is blocked and no matter how i try to bypass/whitelist, it is impossible.

![2024-03-17 11_40_45-cPanel - — Mozilla Firefox](https://github.com/CIDRAM/CIDRAM/assets/4467158/94a0bc62-221d-4387-bd06-d0e2cbb9fff6)

**Comment by Maikuolan** [comment]
I've created a new ticket at their ticket tracker just now. I'll reply back here again when I see a response from them.

**Comment by eurobank** [comment]
Thanks, i was able finally to whitelist CIDRAM logs, after requesting help from my hosting company.

The bad is that ....  this was happening for 1-2 days and i didn't know.

**Comment by Maikuolan** [comment]
Initial response received from their issue tracker: The person responding wrote that they've created a task for their developers to look into the issue, and to expect a response from them within the next 1~2 business days. Fingers crossed. :-)

**Comment by mikeruss1** [comment]
I had this issue as well, for me it was producing the block report in Immunify, but it had no effect. The Immunify block only occurs when CIDRAM has detected a GET it wants to block, which it was still doing, and the CIDRAM log was still produced.
In other words its a bug in Immunify, the whitelist is detected and working, but it is producing the error report anyway.

**Comment by eurobank** [comment]
> I had this issue as well, for me it was producing the block report in Immunify, but it had no effect. The Immunify block only occurs when CIDRAM has detected a GET it wants to block, which it was still doing, and the CIDRAM log was still produced. In other words its a bug in Immunify, the whitelist is detected and working, but it is producing the error report anyway.

For me, the LOG stops working. Worst is that after resolving the issue, the LOG MUST BE DELETED to start again logging ....

**Comment by Maikuolan** [comment]
> within the next 1~2 business days

Well.. Almost 4 days now, and no further response from them yet. Hopefully just a little busy at the moment and not something more complicated going on.

**Comment by Maikuolan** [comment]
Received a response from them today.

> Thank you for your request.
>
> We have checked the provided information and added related files and flow hashes to white/exclude list. The updated ruleset has already been released globally.

Anyone able to confirm at their end whether the problem still persists?

**Comment by eurobank** [comment]
I will do so, still i need time since it is not something i can do  and watch in a few hours. I will update here.

**Comment by mikeruss1** [comment]
only had 1 event that would trigger it, but it seems to be working OK at last

**Comment by mikeruss1** [comment]
another 4 with no problem, I reckon its fixed for me.

**Comment by eurobank** [comment]
I guess i'm also good.

![Screenshot(2)](https://github.com/CIDRAM/CIDRAM/assets/4467158/0f7dfb56-4dfa-42cc-ae06-d7bbcb471e3b)

**Comment by eurobank** [comment]
thanks

**Comment by Maikuolan** [comment]
Fantastic. :-)
