### ISSUE TITLE
Class "CIDRAM\CIDRAM\FrontEnd" not found

### ISSUE THREAD

**Issue by uudruid74** [CIDRAM/CIDRAM#569]
OK, I can get an Access Denied message if I try to run the frontend from the command line.  When run via the webserver, all I get is ...

```
2024/03/17 09:55:34 [error] 98554#98554: *12896 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "CIDRAM\CIDRAM\FrontEnd" not found in /var/www/devel.pixelpotion.cafe/htdocs/cidram.php:3
Stack trace:
#0 {main}
  thrown in /var/www/devel.pixelpotion.cafe/htdocs/cidram.php on line 3" while reading response header from upstream, client: 208.63.89.42, server: devel.pixelpotion.cafe, request: "GET /cidram.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm-php8.1.sock:", host: "devel.pixelpotion.cafe"
```

Any idea on why this is not finding the class?   I did enable the front-end in the config.ini, and turned on a bunch of logs, but I'm not getting any log messages except for the nginx error above.   Spent 3 hours on this on not getting anywhere.

**Comment by Maikuolan** [comment]
Just to clarify, which major version of CIDRAM (e.g., v1, v2, v3) are you currently using?

**Comment by uudruid74** [comment]
I guess it's 2.15.0-8.  There weren't options on the download page.  I just grabbed the tarball assuming it's the current stable release.

On March 17, 2024 5:14:50 AM CDT, Caleb Mazalevskis ***@***.***> wrote:
>Just to clarify, which major version of CIDRAM (e.g., v1, v2, v3) are you currently using?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/CIDRAM/CIDRAM/issues/569#issuecomment-2002393652
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
---
Thank You,
Evan Langlois
Eddon Systems Consulting

**Comment by Maikuolan** [comment]
It seems the tarball and zip links were pointing to the wrong major version branch. I hadn't realised that. Sorry for the trouble and thanks for pointing out the problem.

I've fixed the links, so it should now be pointing to the correct major version (the current latest major version, v3). :-)

**Comment by Maikuolan** [comment]
Closing the issue for now as fixed. If there are any problems, let me know, and I can help to work through them with you if needed, and good luck. :-)
