### ISSUE TITLE
Redis Logout Issue

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#575]
The last month i'm facing a new issue. Using Redis for caching storage, i find myself logged out of CIDRAM admin, every few hours.

Switching to db caching, the issue is gone.

Any ideas what could be causing that? Is it the entry point located in a Wordpress site? Something else?

**Comment by mikeruss1** [comment]
maybe if your Redis is nearly full it is deleting unused files ? Wouldnt apply to DB.

**Comment by eurobank** [comment]
@mikeruss1 Could be what you say, but i have no way to check it out. And the strange is, that it started to happen a few weeks ago.
