### ISSUE TITLE
Bing bot blocked?

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#577]
https://www.bing.com/toolbox/bingbot.json

40.77.202.69 in in there, but:

Date/Time: Sat, 13 Apr 2024 21:59:13 +0300 »
IP address: 40.77.202.69 »
User agent: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/100.0.4896.127 Safari/537.36 »
Signatures reference: bobuam.php:L161 »
Why blocked: Outdated browser (C)! »
/wp-admin/admin-ajax.php »
Infractions: 1 »
Country code lookup: US »
Request method: GET »
Hostname: - »

Shouldn't that be whitelisted by default ?

**Comment by Maikuolan** [comment]
Should be fixed now. :-)
