### ISSUE TITLE
Aux problem

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#578]
the last aux rule is a test to allow captcha if signature count = 1, works fine

this one however doesnt work .. note captcha disabled

ID: 1713049580-785218-4104888896 Date/Time: Sun, 14 Apr 2024 00:06:20 +0100 IP address: 79.110.53.30 Query: - User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0 Signatures count: 1 Signatures reference: Core.php:L1240 Why blocked: Unverified Twitterbot! Reconstructed URI: https://xxxx/ Infractions: 1 Request method: GET Protocol: HTTP/1.1 Hostname: - CAPTCHA state: Disabled.

**Comment by Maikuolan** [comment]
What does the configuration for **`verification➡adjust`** currently look like? Could be that preventing the CAPTCHA from appearing in this case, potentially.

![adjust](https://github.com/CIDRAM/CIDRAM/assets/12571108/1d1279db-4970-428b-bd0b-f01d093c20c5)

**Comment by mikeruss1** [comment]
yes thats it. I think I would argue that aux should override that. But your call.
