### ISSUE TITLE
IP-API expiration / Country code lookup

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#579]
I see those two logs. The second shows country code lookup US. The First (top) is showing XX. 

Not sure if this is correct since i see that this is cached until 22 April. So why a new lookup is initiated and failed?

PDO.

-------

ID: 1713206246-095276-7932740349 »
Date/Time: Mon, 15 Apr 2024 21:37:26 +0300 »
IP address: 35.171.69.89
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 »
Signatures reference: bobuam.php:L168 »
Why blocked: Banned, Outdated browser (F)! »
Infractions: 13 »
Country code lookup: XX »
Request method: GET »
Hostname: ec2-35-171-69-89.compute-1.amazonaws.com »

ID: 1713190078-168130-0005576290 »
Date/Time: Mon, 15 Apr 2024 17:07:58 +0300 »
IP address: 35.171.69.89
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 »
Signatures reference: bobuam.php:L168 »
Why blocked: Banned, Outdated browser (F)! »
Infractions: 12 »
Country code lookup: US »
Request method: GET »
Hostname: ec2-35-171-69-89.compute-1.amazonaws.com »

**Comment by Maikuolan** [comment]
When a valid cache entry exists, it *should* be pulling data from that cache entry to populate the relevant fields, so I'm not sure what's going on there.

I looked over the code just now and couldn't see any obvious problems, so it could be something specific to PDO, maybe. I'll do some testing at my end and reply back later.

**Comment by eurobank** [comment]
Here is an other one:

154.16.164.46/32 – (Delete)

    Data 
  ASN => 0
  CC => XX
    Expires: Thu, 25 Apr 2024 17:12:02 +0300

____

**** The Log Order Sort in descending order ****

ID: 1713629383-730840-7295096057 »
Date/Time: Sat, 20 Apr 2024 19:09:43 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36 »
Signatures reference: - »
Why blocked: Banned! »
Infractions: 12 »
Country code lookup: XX »
Request method: GET »
Hostname: - »

ID: 1713629382-985484-6549734974 »
Date/Time: Sat, 20 Apr 2024 19:09:42 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36 »
Signatures reference: - »
Why blocked: Banned! »
Infractions: 12 »
Country code lookup: XX »
Request method: GET »
Hostname: - »

ID: 1713618893-228286-6792533356 »
Date/Time: Sat, 20 Apr 2024 16:14:53 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.132 Safari/537.36 »
Signatures reference: auxiliary.yml:Attacking ASNs 212238 »
Why blocked: Banned, Attacking ASNs 212238! »
Infractions: 12 »
Country code lookup: GB »
Request method: GET »
Hostname: - »

ID: 1713618892-488029-6052289771 »
Date/Time: Sat, 20 Apr 2024 16:14:52 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.132 Safari/537.36 »
Signatures reference: auxiliary.yml:Attacking ASNs 212238 »
Why blocked: Banned, Attacking ASNs 212238! »
Infractions: 11 »
Country code lookup: GB »
Request method: GET »
Hostname: - »

ID: 1713612431-922518-5486792649 »
Date/Time: Sat, 20 Apr 2024 14:27:11 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Iron Safari/537.36 »
Signatures reference: 154.16.164.0/23, auxiliary.yml:Attacking ASNs 212238 »
Why blocked: Cloud service ("CDN77", L32194:F0, ), Attacking ASNs 212238! »
Infractions: 10 »
Country code lookup: GB »
Request method: GET »
Hostname: - »

ID: 1713612429-784886-3349135738 »
Date/Time: Sat, 20 Apr 2024 14:27:09 +0300 »
IP address: 154.16.164.46
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Iron Safari/537.36 »
Signatures reference: 154.16.164.0/23, auxiliary.yml:Attacking ASNs 212238 »
Why blocked: Cloud service ("CDN77", L32194:F0, ), Attacking ASNs 212238! »
Infractions: 8 »
Country code lookup: GB »
Request method: GET »
Hostname: - »

**Comment by Maikuolan** [comment]
I think this might be related to #592. I'm going to go ahead and mark this as fixed for now accordingly. If the problem reappears though, let me know.
