### ISSUE TITLE
Small Cleanup Needed

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#580]
IP address: 147.124.198.194 »
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 »
Signatures reference: 147.124.198.0/23, 147.124.198.0/24, 147.124.198.0/24 »
Why blocked: Cloud service ("Tier.Net Technologies LLC", L40939:F0, ), Cloud service ("EGIHosting/H4Y", L6989:F0, ), Cloud service ("Taner Temel", L37025:F0, )! »
Infractions: 3 »

**Comment by Maikuolan** [comment]
Cheers. Done. :-)
