### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#584]
Back in #401 you gave me the API to request a validation only and return a report only, with no tracking, blocking, logging etc
$CIDRAM = new \CIDRAM\CIDRAM\FrontEnd();

$Results = $CIDRAM->lookup(
    '39.144.46.117', // The IP address to check.
    true, // Whether to check against modules (true or false).
    true, // Whether to check against auxiliary rules (true or false).
    false, // Whether to check against search engine and social media verification (true or false).
    'foo=bar', // The "query" part of the request, like in "hxxp://my-domain.com/page.php?foo=bar" (optional; can leave empty if you want).
    'http://i-came-from-here.com/', // The referrer (optional; can leave empty if you want).
    'Mozilla/5.0' // The user agent (optional; can leave empty if you want).
);

it still seems to work, is it OK to use?

I noticed it is going through every Aux rule and reporting when it is not satisfied, like below. Is this intentional ?

Apache aux block – User agent (lower-case) (mozilla/5.0) ≈ *apache-httpclient*: Not satisfied.

**Comment by Maikuolan** [comment]
> is it OK to use?

Yep. :-)

> Is this intentional ?

Also yep (relates to #430). :-)

**Comment by mikeruss1** [comment]
if this NOT SATISFIED detail is controlled by the fields table in config, I have * Conditions inspection turned off.

its working OK on my desktop version though
