### ISSUE TITLE
Question about "bobuam" and Outdated Browsers

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#590]
I have a LOT of blocked hits as outdated browsers. What i see is many of them to be "iPhone" related or something. And those IPs are not listed in ANY database for spam or other dangerous activity. None of them.

So could that be some wrong block? All they have Chrome marked as outdated. 

Here are some examples:

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.6235.1485 Mobile Safari/537.36

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.8143.1310 Mobile Safari/537.36

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.1071.1277 Mobile Safari/537.36 

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.1859.1244 Mobile Safari/537.36

**Comment by mikeruss1** [comment]
FWIW I have Chrome old browser limit set at 51 and if there is only 1 error it gets recaptcha offered. I have never seen recaptcha passed in that situation.

**Comment by eurobank** [comment]
@mikeruss1 The thing is that Immunify offers sometimes a recaptcha, my Wordpress also in contact and register, adding a 3rd recaptcha is not good for users. It is going already tooo much.

**Comment by mikeruss1** [comment]
my suggestion is these are not real users, or if they are they have never bothered to pass recaptcha
