### ISSUE TITLE
Country Lookup (BGPVIEW)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#592]
Many times the Country Lookup (and the ASN probably) is showing XX. While the IP is IN the database cache.

**Date/Time: Sun, 19 May 2024 16:14:17 +0300 »**
IP address: 104.128.191.5
User agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 »
Signatures reference: auxiliary.yml:ASN - Dangerous 9009 »
Why blocked: Banned, ASN - Dangerous 9009! »
Infractions: 22 »
**Country code lookup: RO »**
Request method: GET »
Hostname: - »

but

**Date/Time: Sun, 19 May 2024 21:04:41 +0300 »**
IP address: 104.128.191.5
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YaBrowser/22.7.0 Yowser/2.5 Safari/537.36 »
Signatures reference: - »
Why blocked: Banned! »
Infractions: 22 »
**Country code lookup: XX »**
Request method: GET »
Hostname: - »

and the data has NOT expired in the PDO cache, so a new call could be rate limited and explain the XXX:

![Screenshot(1)](https://github.com/CIDRAM/CIDRAM/assets/4467158/00655945-6b5d-402f-84bd-1bb804e11630)

**Comment by Maikuolan** [comment]
Able to replicate the bug at my end. Investigating the cause now.

**Comment by Maikuolan** [comment]
Fixed. :-)
