### ISSUE TITLE
How to whitelist everything from *.google.com

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#593]
Hi,

I need to completely whitelist everything comming from *.google.com and bypass all aux rules, modules, signatures. everything.

Please some help in that. Thanks

**Comment by Maikuolan** [comment]
As long as **`general➡force_hostname_lookup`** is `true`, it should be possible to whitelist everything from `*.google.com` via auxiliary rules, like so:

![google](https://github.com/CIDRAM/CIDRAM/assets/12571108/6d8421b0-5b65-4c91-96f2-b564b2276035)

Although auxiliary rules, modules, signature files, etc would still be processed, as long as whitelisting occurs, by the end of it, it shouldn't matter too much, as whitelisting clears out the signatures count and any accrued infractions regardless, preventing any block event from occurring for the request at hand.

**Comment by eurobank** [comment]
Thanks, i will try this. I have done something similar and didn't seem to work.

**Comment by eurobank** [comment]
@Maikuolan Does that seem right to you? Am i missing something?

![Screenshot](https://github.com/CIDRAM/CIDRAM/assets/4467158/964c6bdb-c2a2-4c6c-81f1-b0799c669c3e)
