### ISSUE TITLE
Blackhole with CIDRAM

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#594]
I'm thinking to setup a bots blackhole with CIDRAM.

The idea is to inject a nofollow link in all pages <body>, declare a NOFOLLOW for that link in robots.txt and use CIDRAM to check the restructured urls via an AUX RULE and block.

How does that sound to you ? Any issues ? Could that work?

**Comment by Maikuolan** [comment]
Sounds like a great idea to me. :-)

**Comment by mikeruss1** [comment]
you could do worse than also add a honey pot
https://www.projecthoneypot.org/home.php
I have one on each page and on the CIDRAM block page.

**Comment by eurobank** [comment]
@mikeruss1 Never got the projecthoneypot to work.

**Comment by eurobank** [comment]
The first stupid bot came in

ID: 1716747586-903857-4851281077 »
Date/Time: Sun, 26 May 2024 21:19:46 +0300 »
IP address: 40.77.167.243 »
Query: ************** »
User agent: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36 »
Signatures reference: auxiliary.yml: Trap »
Why blocked: Trap! »
Infractions: 0 »
Country code lookup: US »
Verified identity: Bingbot »
Request method: GET »
Hostname: msnbot-40-77-167-243.search.msn.com »

**Comment by eurobank** [comment]
Well, that is not good:

ID: 1716750701-257042-9204465245 »
Date/Time: Sun, 26 May 2024 22:11:41 +0300 »
IP address: 66.249.72.33 »
Query: ********************* »
User agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.65 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) »
Signatures reference: auxiliary.yml:Trap »
Why blocked: Trap! »
Reconstructed URI: ****************
Infractions: 0 »
Country code lookup: US »
Verified identity: Googlebot »
Request method: GET »
Hostname: crawl-66-249-72-33.googlebot.com »

**Comment by Maikuolan** [comment]
I would've expected Bingbot and Googlebot to correctly abide by `nofollow`. :-/

Might be worth double-checking whether everything has been set up correctly, i.e., the `nofollow` links properly include `nofollow`, and the rule correctly blocks only those URLs which match that `nofollow` link, just in case, because if everything has, in fact, been set up correctly, that would imply that Bingbot and Googlebot aren't correctly abiding by `nofollow`, which is definitely not a good thing, nor expected, and would warrant taking a closer look at exactly how those search engines operate in that regard, I think.

**Comment by Maikuolan** [comment]
I found an interesting snippet at one of [Google's blog posts](https://developers.google.com/search/blog/2019/09/evolving-nofollow-new-ways-to-identify) from late 2019:

> For crawling and indexing purposes, nofollow will become a hint as of March 1, 2020. Those depending on nofollow solely to block a page from being indexed (which was never recommended) should use one of the much more robust mechanisms listed on our ...

So.. It seems Google is officially not abiding by `nofollow` anymore (which I didn't know).

Seems `noindex`, as a potential alternative to `nofollow`, wouldn't be any good for the purpose of blackholes either, at least in regard to Googlebot. According to [Google's own documentation](https://developers.google.com/search/docs/crawling-indexing/control-what-you-share):

> **Important**: For the **noindex** rule to be effective, the page or resource **must not** be blocked by a robots.txt file, and it has to be otherwise accessible to the crawler. If the page is blocked by a robots.txt file or the crawler can't access the page, the crawler will never see the **noindex** rule, and the page can still appear in search results, for example if other pages link to it.

..Which kind of defeats the point, because it's basically saying that they'll still be trying to crawl said page, regardless of whether or not said page appears in their search results.

**Comment by eurobank** [comment]
Maybe the legit search engines need some time to re-read the updated robots.txt, i will see how this goes today and the next days from now.

Also there is something i can't do apparently with CIDRAM, that is immediately BAN some IP when it falls in the trap. Because right now it needs to be 10 times as per configuration to be banned.

**Comment by eurobank** [comment]
@Maikuolan 

If google crawls and indexes  such pages, ignoring robots.txt, it will be shown after a while in google webmasters data.

**Comment by mikeruss1** [comment]
Also there is something i can't do apparently with CIDRAM, that is immediately BAN some IP when it falls in the trap.
-------------------
try extended tracking in aux rules - it applies an immediate ban
discussed here
https://github.com/CIDRAM/CIDRAM/issues/591

**Comment by eurobank** [comment]
@mikeruss1 Where is that Extended Tracking? First time i hear that :)

Is that an InstaBan?

**Comment by eurobank** [comment]
Ok, found  it, Forcible Tracking enabled then the options are there ......

Thanks @mikeruss1 for the tip

**Comment by eurobank** [comment]
Where is the duration configured? 11-12 months?

![Screenshot(1)](https://github.com/CIDRAM/CIDRAM/assets/4467158/a1fa463b-e826-4974-af7e-3d1d043cf560)

**Comment by eurobank** [comment]
@Maikuolan With phpmailer enabled in CIDRAM, i get a fatal redeclare phpmailer error in Wordpress site that has the CIDRAM admin entrypoint.

Any ideas what i can do about it?

**Comment by mikeruss1** [comment]
Where is the duration configured? 11-12 months?
--------
if you need a quick answer ...
in \vault\modules\custom_mods.php there is a variable ...
/** Options for instantly banning (sets tracking time to 1 year and infraction count to 1000). */
$InstaBan = ['Options' => ['TrackTime' => 31536000, 'TrackCount' => 1000]];
tracktime is in seconds = 12 months

if you can wait for Maikuolan to confirm

**Comment by eurobank** [comment]
@mikeruss1 no such file in my directory.

**Comment by mikeruss1** [comment]
OK - it must be in the internal code
I suspect you could set the file up, and tell CIDRAM to read it as a module, but thats several steps too far for me to recommend!

**Comment by Maikuolan** [comment]
> @Maikuolan With phpmailer enabled in CIDRAM, i get a fatal redeclare phpmailer error in Wordpress site that has the CIDRAM admin entrypoint.
> 
> Any ideas what i can do about it?

I've been attempting to investigate that problem, to try to get to the bottom of it, but so far, I have no idea why that's happening. I'll reply with more information if/when I can figure out what's going on there.

**Comment by eurobank** [comment]
@Maikuolan Maybe this phpmailer is Hosting specific. We run under Cloudlinux and Cpanel. 

Not worth to spend more time with it.
