### ISSUE TITLE
Request: Expired Aux Rules (dates)

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#595]
IF it is easy and simple and feasible, could Expired Aux Rules (dates) to be also Disabled?

**Comment by Maikuolan** [comment]
Yeah, that should be doable. I'll work on changing that soon. :-)

**Comment by Maikuolan** [comment]
Expired auxiliary rules will now be properly labelled as expired at the auxiliary rules view mode page.

Expired rules should functionally already be disabled in the sense that, like disabled rules, expired rules aren't acted upon (beyond the initial check to determine whether they were expired to begin with).
