### ISSUE TITLE
Search engine visibility

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#598]
Back in #244 you said there was a variable $CIDRAM['BlockInfo']['Verified']  which defined access from a search engine. Is this visible ? If not and it is an easy job, could it be on the ToDo list please?

**Comment by Maikuolan** [comment]
It's still visible, but as v3 is more object-oriented than previous major versions, to access it, along with any/all other "block information", you would be wanting to access it via the object responsible for executing CIDRAM in the first place.

For example, if your main entrypoint looked something like this:
```PHP
$CIDRAM = new \CIDRAM\CIDRAM\Core();
$CIDRAM->protect();
```

To access the "verified" information, you would want `$CIDRAM->BlockInfo['Verified']`.

Or, if your main entrypoint looked something like this:
```PHP
$BlahBlahBlah = new \CIDRAM\CIDRAM\Core();
$BlahBlahBlah->protect();
```

To access the "verified" information, you would want `$BlahBlahBlah->BlockInfo['Verified']`.

But yeah; Still accessible. But, as of v3, how to access it depends slightly on how your entrypoint has been structured.

**Comment by mikeruss1** [comment]
good news thank you. not really into object-oriented
I have ... 
require_once 'C:\xxx\zzz\cidram/vault/loader.php';
(new \CIDRAM\CIDRAM\Core())->protect();

what do I need on the return from the call, and what are the value options?

**Comment by mikeruss1** [comment]
OK have sorted access after trying a few things, could you confirm the possible values

**Comment by Maikuolan** [comment]
Sorry for the delay. Possible values are:

```
AdSense
AmazonAdBot
Amazonbot
Applebot
Baidu
Bingbot
ChatGPT-User
DuckDuckBot
Embedly
Facebook external hit
GPTBot
Googlebot
Grapeshot
MojeekBot
Neevabot
PetalBot
Pinterest
Qwantify
SeznamBot
Snapchat
Sogou
Twitterbot
Yahoo
Yandex
YoudaoBot
```

(Or empty/blank, for in the event that nothing is verified, verification fails, for non-verifiable requests, etc).

**Comment by mikeruss1** [comment]
No problem, many thanks.
