### ISSUE TITLE
Outdated Browser Question

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#601]
Isn't this:

Mozilla/5.0 (Windows; Windows NT 10.2;; en-US) AppleWebKit/537.3 (KHTML, like Gecko) Chrome/52.0.1828.122 Safari/601.0 Edge/16.67893

Outdated? It seems to pass all tests and blocks.

**Comment by Maikuolan** [comment]
More than just outdated: Pretty sure that's entirely faked. The double semi-colon (";;"), for starters: Generally, for any user agent utilising that structure (i.e., any Windows-based, Chromium-based browser), we would expect there to be a `Win64; x64`, `Win32, x32`, `Win32, x86`, or something like that to come after the "Windows NT xx.x" part.

Also, to my knowledge, no legitimate user agent anywhere should be citing "Windows NT 10.2". The current latest release build of NT from Microsoft at this time, released May 29 this year, is "23H2", internally versioned as `10.0.22631.3672`. The current latest *preview* build is "24H2", internally versioned as `10.0.26100.712`. To my understanding, the "Windows NT xx.x" part in the user agent is derived from the client being built for a Windows NT system, the version part reflecting the first two segments of the build version of that system. Whether that's `10.0.26100.712` or `10.0.22631.3672`, either way, I would expect that to be represented as "Windows NT 10.0".

Of course, whether we're talking Microsoft, Google, or whoever else, pretty much everyone is regularly changing, or breaking the convention entirely when it comes to their browsers' user agents, so who knows? I might be wrong, and it might be the legitimate user agent for some kind of mobile browser, some relatively obscure third-party browser based on Chromium which just pushes a weird user agent like that for some reason, or whatever else. But, I *strongly suspect* that it's entirely faked; that it's some kind of bot or scraper (and that whoever wrote it likely thinks they're being clever by pretending that their bot is a browser running on the latest build of Windows 10, doesn't know the exact version of the latest build, or how that gets represented in a user agent, so just took a guess at it and put down "10.2").

As for it passing all tests and blocks: I'll try to do something about that in a moment and push out an update later today. :-)

**Comment by eurobank** [comment]
No problem, no rush.

**Comment by eurobank** [comment]
That 

Hostname: ec2-54-149-109-115.us-west-2.compute.amazonaws.com

is what i see all kind of strange and different user agents. Probably a smart (not so smart) scraper ....

**Comment by Maikuolan** [comment]
Made some changes to the BOBUAM, adding a new directive specifically for Edge (though Chrome and Edge version tokens should generally always be in lockstep together, thus why we never needed a directive specifically for Edge before, for cases like these, where they aren't, it seems the signatures for dealing with Chrome aren't sufficient for dealing with outdated Edge version tokens, so I've gone ahead and added one for Edge to cover these kinds of.. "edge" cases). Also added a directive for fine-tuning CAPTCHA options per which specific kind of block is being enforced by BOBUAM, and optimised a few other modules a bit further.

Also added a signature to the bot UAs module to check for ";;", so.. this should all be solved now, I think. :-)
