### ISSUE TITLE
Idea for new utility

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#602]
This one would validate the behaviour of the user with the objective of distinguishing browsers from bots. The site would need to add a new IMG call to a defined PHP program which calls cidram and returns a 1 byte image. If the image is fetched it's a browser, if it isn't it's a bot or a search engine, or a set of allowed UAs like Wikipedia.
Possible options could be ...
Storage, suggest cache preferred
How many URLs allowed before trap operates, maybe 1 or 2
How many IP address sections constitute a single user, 4 or 3 or 2?
(Within 30 mins suggest 2 sections is ok, for banning maybe should be 4)
How long to operate a trap, 30 mins?
Use sessions for storage of  a valid user indicator, ie ignore call.
Treat IP as banned
Send email notification to website admin

Currently coding a version of this, will update with how it goes.

The long term thought is perhaps we can get rid of the Cloud service checks. More ideas needed to make that possible.

**Comment by eurobank** [comment]
Well, all the above and also other suggestions probably require a strong database. Am i correct?

**Comment by mikeruss1** [comment]
The basic mechanism only needs cache

**Comment by mikeruss1** [comment]
just an update - all coded and tested. Only a few lines of code needed. Waiting for some other changes to settle down before implementing. My expectation is that it will find stuff that CIDRAM misses like site strippers using a valid UA.

**Comment by mikeruss1** [comment]
would you mind checking if 
$whatever->BlockInfo['Verified'];
is correctly setup
I got a request from IP 52.167.144.xx
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible;
bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76
Safari/537.36
I think this is a valid bingbot and CIDRAM didnt block it
I am testing that the Verified field is larger than 2 characters. I am not 100% sure yet that this bit of the code works as I cant simulate a request from a search engine, but I tried other fields like "ID" and I get that OK
It looks like my code thinks that Verified is not completed
thank you !

**Comment by mikeruss1** [comment]
More info - it looks like Googlebot is working OK, but not Bingbot. The settings for "Bypass used" are different, Googlebot is off, Bingbot on.  The settings for Verification are the same, On, apart from Block non verified which is off. The Bingbot problem applies to multiple IP groups, like 40.77.167.xx and 157.55.39.xx

**Comment by mikeruss1** [comment]
Definite proof now, Googlebot is setting $whatever->BlockInfo['Verified'];
Bingbot is not

**Comment by mikeruss1** [comment]
Implemented and finding interesting stuff, reporting only ATM

**Comment by mikeruss1** [comment]
suggest forget this, have taken it out. It is complicated by various low level network retries and by the browser back button. Not finding much either.
