### ISSUE TITLE
PHP Error in bobuam

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#605]
PHP Fatal error:  Uncaught Error: Call to undefined method CIDRAM\CIDRAM\Core::enactOptions() in /vault/modules/bobuam.php:154

also lines 183 and 201

started on 14 June the last time I updated

**Comment by Maikuolan** [comment]
If you go to the updates page, what does it show as the currently installed version for the "CIDRAM Core"?

**Comment by mikeruss1** [comment]
I updated it as soon as I saw the error, it would have been maybe a couple of months old

that fixes it?

**Comment by Maikuolan** [comment]
Should do. :-)

**Comment by mikeruss1** [comment]
generally I keep up to date with modules and signatures, and update the core for major releases

if modules are tied to changes elsewhere I guess they should force update or something?

**Comment by mikeruss1** [comment]
what would have been the effect - less blocks ?

**Comment by Maikuolan** [comment]
> what would have been the effect - less blocks ?

Nah, blocks would've been the same. The changes to the core needed by the latest BOBUAM version was some supporting code for the newly added "options" configuration directive; In short, that new configuration directive would've failed to actually do anything. Should all be good though if everything is now up to-date. :-)

I'll push some changes to the dependency information in the update metadata shortly to ensure that anyone else that might've missed the changes gets the necessary accompanied updates.
