### ISSUE TITLE
Bombarded !!!!!!!!!

### ISSUE THREAD

**Issue by eurobank** [CIDRAM/CIDRAM#606]
With this user agent, never seen something like that as UA, 500+ hits in a 3 minutes, brought the hosting plan to be "limited" .....

User agent: datasets/2.20.0; python/3.10.14; huggingface_hub/0.23.4; pyarrow/15.0.2; torch/2.1.2 

Isn't that malformed, or superflus, or something?

**Comment by Maikuolan** [comment]
Youch. o.0

Looks like more AI crap, AFAICT. Found via googling: https://huggingface.co/docs/huggingface_hub/en/index

I'll add some new signatures to block that now.

**Comment by Maikuolan** [comment]
It's possible that the intent of these requests may be a little more severe that merely excessive scraping; that these requests may be an actual attempted attack:
- *https://nsfocusglobal.com/ai-supply-chain-security-hugging-face-malicious-ml-models/*
- *https://www.darkreading.com/application-security/hugging-face-ai-platform-100-malicious-code-execution-models*
- *https://vulcan.io/blog/understanding-the-hugging-face-backdoor-threat/*

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by mikeruss1** [comment]
high volume crap best blocked in .htaccess

BrowserMatchNoCase (Bytespider|Go-http-client|python|Firefox/3.5|Firefox/3.6|curl/|trafilatura|imagesift|externalhit_uatext) bad_bot
Order Deny,Allow
Deny from env=bad_bot

**Comment by eurobank** [comment]
btw the IP was IP address: 54.70.184.189, AWS (Amazon)
