### ISSUE TITLE
Help pl - unknown Google bot?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#607]
does anyone know what this is ...
IP 193.186.4.64.xx 
UA Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
or
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

its been downloading around 200 pages a month (only, no images, css, js)  since late 2021
the referror is always google.com.
Its apparently Google, the hostname is 193-186-4-xx.v4.fetch.tunnel.googlezip.net, seems to come out of Leeds UK, and there are sporadic reports that IPs in that group are spam.

Its fairly well behaved so my guess is it is some Google function so unwise to block?

**Comment by Maikuolan** [comment]
Had to do some searching, but from what I've read, it seems this is a service provided by Google, tied specifically into some older versions of Chrome, as a way to reduce bandwidth usage (whether this bandwidth usage reduction is intended for the client or for the server isn't entirely clear), by intercepting traffic between the server and client and compressing it before delivery.

Some of what I found:

- https://www.fastvue.co/sophos/blog/google-data-saver-affect-security-confidentiality-reporting/
- https://support.google.com/webmasters/thread/257944529/how-can-i-stop-tunnel-google-zip-from-excessive-crawling-of-site?hl=en

Based on that, it should *probably* be okay to leave it be for now, but I see quite a large number of nasty reports concerning that particular range [at AbuseIPDB](https://www.abuseipdb.com/check-block/193.186.4.0/24), so.. hard to say for sure.

Maybe don't block outright, but continue keeping an eye on it, just in case..?

**Comment by mikeruss1** [comment]
good finds, thank you
sounds related but some things about it dont add up. The page is compressed anyway by my server, and its only the page thats fetched, none of the related images, js, etc. Its only a few pages a day so likely not worth worrying about.
