### ISSUE TITLE
API for reporting not validation ?

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#608]
we have discussed a few times the ability for an API which does no validation, just reporting, logging + tracking, 

now #602 is working it would be neat to have it 

has this crept into your code already, or maybe on the horizon ?

**Comment by Maikuolan** [comment]
Have earmarked some ideas I want to try, but had been feeling a bit under the weather the past week, not really able to focus on getting much done beyond basic maintenance and such (though I had managed to sneak in some basic support for client hints, which ended up being a heck of a lot easier and simpler than I'd anticipated; at least for the low-entropy ones.. *hooray..!!* ..though looks likely to be just as annoying as we'd anticipated for the not-low-entropy ones, so those not-low-entropy ones can be dealt with later; all seems to be working properly for those which've now had support added in for now though). Feeling a bit better now though so hoping to try a few things out soon. :-)

**Comment by mikeruss1** [comment]
thank you, only if its a priority for you pl

**Comment by mikeruss1** [comment]
status for me is now useful but not needed in the near future
