### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#611]
this is from the frontend on my windows desktop system, so nothing urgent

( ! ) Fatal error: Uncaught Error: Call to undefined function Maikuolan\Common\curl_init() in C:\zzz\aaa\xxx\vault\Maikuolan\Common\Request.php on line 149
--
reporting as 3.6 on the password screen
the last time I updated was 5th July, cant remember if I tested it at the time, (or since) probably not I guess, been busy with other stuff
 its a wampserver and I think curl is not available

I have a backup of the setup, so can reinstall 3.7 if thats easiest?

checked the logs and its not been run since 12th July when I updated to php 8.3.9, (and cleared the logs)

**Comment by Maikuolan** [comment]
Fixed. :-)

**Comment by mikeruss1** [comment]
many thanks - can I patch it easily so it will run, or reinstall ?
copy request.php from live version ?

**Comment by Maikuolan** [comment]
Either either; The change is pretty small and isn't dependent on changes elsewhere, so should be good, either way. :-)

**Comment by mikeruss1** [comment]
reinstalled. All working OK but the updates page has unable to determine against every item. Tried restoring from backup. Every file reports not available at upstream.
sorry - suspect I have forgotten something !

**Comment by mikeruss1** [comment]
cache page ...
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\aaa\www\bbb\vault\CIDRAM\CIDRAM\FrontEndMethods.php on line 794

**Comment by Maikuolan** [comment]
> cache page ... Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\aaa\www\bbb\vault\CIDRAM\CIDRAM\FrontEndMethods.php on line 794

Definitely not passing null anywhere there, so no idea offhandedly why it's generating an error like that, but.. it is nearly 2AM, so.. I'll take a closer look again after I've had some sleep, I think; I might see something with fresher eyes that I'm not seeing currently (there'll obviously be a cause in there somewhere, after all, else there wouldn't be the error in the first place).

Reopening the issue.

**Comment by Maikuolan** [comment]
Before I call it for the night though.. At the front-end homepage, where it says __`Extension➡Installed/Available`__, if you click on that, what information does it show?

For example, what I see at my current local test installation:

![Untitled](https://github.com/user-attachments/assets/4c6dc595-f0aa-4e70-81c2-6cd514a7b5b0)

**Comment by mikeruss1** [comment]
PCRE yes

curl no

apcu no

memcache no

PDO yes 

all the cache options SB turned off and using native local storage

**Comment by mikeruss1** [comment]
incidentally - all the pages say generated by CIDRAM 3.6 even though I just reinstalled

**Comment by mikeruss1** [comment]
enjoy the weekend, its my test system so no rush.

**Comment by mikeruss1** [comment]
Bit more info - enabled CURL and it made no difference
the first time I ran the updates page I got ...
Can't fetch metadata <https://raw.githubusercontent.com/CIDRAM/CIDRAM/v3/vault/installed.yml>: Unknown error!
Can't fetch metadata <https://raw.githubusercontent.com/CIDRAM/CIDRAM-Extras/master/modules/modules.yml>: Unknown error!
2nd time didnt get this, but everything still unable to determine

**Comment by mikeruss1** [comment]
ran it again, and fixed !
not sure how, restarted wampserver a few times, did some CURL tests, nothing that should have made a difference.
puzzled ...

**Comment by mikeruss1** [comment]
the deprecated error on the cache page occurs twice, the cache contents are shown fine.

**Comment by mikeruss1** [comment]
the deprecated error has gone away ....
my guess is it was an artifact of rebuilding the system. I built it from scratch, then loaded a backup on top. Probably something was missing as a result that has now been reestablished ?
