### ISSUE TITLE
Cloudflare IPs getting blocked

### ISSUE THREAD

**Issue by soumsps** [CIDRAM/CIDRAM#62]
Today I have seen multiple instances in log where cloudflare IPs getting blocked.
To be noted : I have not enabled Cloudflare block list.
```
ID: 597
Script Version: CIDRAM v1.5.0
Date/Time: Sat, 07 Apr 2018 15:16:12
IP Address: 162.158.67.83
Signatures Count: 1
Signatures Reference: 162.158.64.0/20
Why Blocked: Cloud service ("CloudFlare, Inc", L797:F0, [US])!
User Agent: Mozilla/5.0 (compatible; CloudFlare-AlwaysOnline/1.0; +http://www.cloudflare.com/always-online) AppleWebKit/534.34
Reconstructed URI: https://example.com/
reCAPTCHA State: Enabled.
```
```
ID: 587
Script Version: CIDRAM v1.5.0
Date/Time: Sat, 07 Apr 2018 15:16:06
IP Address: 162.158.64.234
Signatures Count: 1
Signatures Reference: 162.158.64.0/20
Why Blocked: Cloud service ("CloudFlare, Inc", L797:F0, [US])!
User Agent: Mozilla/5.0 (compatible; CloudFlare-AlwaysOnline/1.0; +http://www.cloudflare.com/always-online) AppleWebKit/534.34
Reconstructed URI: https://example.com/
reCAPTCHA State: Enabled.
```
```
ID: 586
Script Version: CIDRAM v1.5.0
Date/Time: Sat, 07 Apr 2018 15:16:05
IP Address: 2400:cb00:36:1008:0:0:a29e:40ea
Signatures Count: 1
Signatures Reference: 2400:cb00:36::/48
Why Blocked: Cloud service ("CloudFlare, Inc", L180:F0, [US])!
User Agent: Mozilla/5.0 (compatible; CloudFlare-AlwaysOnline/1.0; +http://www.cloudflare.com/always-online)
Reconstructed URI: https://example.com/
reCAPTCHA State: Enabled.
```

**Comment by soumsps** [comment]
Now added `Ignore CloudFlare, Inc` in my `Ignore.dat` file.

Thank You, :-) 
Actually, I thought Cloudflare IPs will only get blocked when we activate Cloudflare blocklist.

**Comment by soumsps** [comment]
Thanks a lot for detailed response :-) 
You have answered all my queries :+1:

**Comment by Maikuolan** [comment]
So.. None of the people I talked to were able to produce any evidence for current unwanted HTTP/S traffic from Cloudflare. A few suggested that they think they *might've* seen something, but didn't have any logs for it anymore. Anyway.. I'm going to go ahead and remove them from the signature files for now. If evidence turns up, they can always be re-added in the future I guess, but for now, I'm inclined to believe that there's no value reason to keep them in the signature files anymore.
