### ISSUE TITLE
AS lookup.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#69]
A feature requested by a user via private channels a month or so back. Still investigating this (just creating the issue here, in case they visit the issues page and think I've forgotten about their request :D). Will comment more later. Marking as "attention required".

**Comment by Maikuolan** [comment]
Actually have made a little progress on this recently. Holding off on committing any new features or significant changes until I can sort out some higher priorities first, but have already sent a manual patch to the user in question via private channels.

**Comment by 737simpilot** [comment]
Are you planning on implementing this in version 2?

**Comment by Maikuolan** [comment]
Possibly both v1 and v2 alike. I've already got working code for it on my local machine, and it can definitely be done (working code doesn't produce any errors or other problems, works as intended, etc); I just need to come up with a good plan to cleanly integrate it, in terms of how it should conceptually affect everything else already in the package, whether (and how) it should integrate with signature files, modules, auxiliary rules, and whatever else, or whether it should stand alone as its own thing, how I should document it and that kind of thing, because it's all looking kind of messy at the moment in those regards. Because of those considerations, it's been perpetually postponed over the past few months as I find other priorities to busy myself with. We'll get there at some point though (hopefully soon).

**Comment by 737simpilot** [comment]
Sounds good.

**Comment by Maikuolan** [comment]
Well.. This had been on the backburner for quite a while now, so I decided to finally get it sorted out.

Seeing as that the only way to do this, while still avoiding the need to implement a massive database locally at CIDRAM (which isn't desirable, because it would significantly bloat the size of the package, and would also add another really big thing for me to continually maintain into the future, making the project overall less maintainable), is to implement some kind of lookup to fetch the needed data from elsewhere (i.e., an external API), I decided to just do this as a module, instead of implementing something into the CIDRAM core itself.

That way, the CIDRAM core isn't directly coupled into yet another external API, and those that don't want the added functionality can simply disregard the new module. It also means that CIDRAM remains as a "CIDR Access Manager", and doesn't start gradually drifting towards being an "ASN Access Manager" (ASNAM?), which.. although having a way to natively block ASNs may sound nice, and isn't necessarily bad in itself.. I find it generally preferable that the project maintains its scope as best as it can moving forward. Something in a module = Not something in the core = Scope creep isn't much of a concern anymore.

In order to avoid the question of exactly how this should best affect signature files, the signature file format, auxiliary rules and so on, I decided that it just.. won't. Taking advantage of the recently added ability for modules to supply their own configuration directive defaults, the new module will just add some new configuration directives where users can specify in their configuration which ASNs (and also which countries) they want to either block or whitelist, pending a successful match for those ASNs and countries at the external API used.

The external API used (and also the name of the newly added module) is "[BGPView](https://bgpview.docs.apiary.io/)".

The newly added module was pushed just a few minutes ago (https://github.com/CIDRAM/CIDRAM-Extras/commit/f82948144e76459669cb42a85b35f51ce961d7d8), so should now be available.

Due to how I've structured the new module, it'll need CIDRAM v2 in order to work correctly (i.e., it isn't compatible with CIDRAM v1). That's something that I hadn't originally been planning when I'd first created this issue, but I think that CIDRAM v2 has been "stable" for long enough now that it shouldn't matter too much at this point.

As a final note: I have absolutely no idea what the resources behind that external API are like, and I don't know the people behind it, so.. I'm not making any promises about the likelihood of it staying online for a long time into the future or about any potential downtime that it might experience. In other words: Only install it and activate it if you think you might need it. If you don't think you need it, just disregard it.

Marking this as implemented and closing.
