### ISSUE TITLE
Aesthetic bug: Logs page stretches with non-breaking log entries.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#71]
*Aesthetic bug: Logs page stretches with non-breaking log entries.*

(Sometimes.. Not always).

Example:

![example](https://user-images.githubusercontent.com/12571108/41101280-5025bd00-6a96-11e8-8ad1-b2e2cb008a89.png)

Creating an issue for it, because it's something I've noticed, it annoys me a bit, and I want to fix it, but it's also something I consider __low-priority__, due to being a purely aesthetic bug, rather than a functional bug, and it won't hinder normal package operation at all.

Had a quick play around with the code tonight but haven't been able to fix it yet, and running a bit short on time (starting my shift at work in the next few hours). I'll continue working on it a bit later though.

**Comment by soumsps** [comment]
Finally, you noticed it :D 
I didn't create this issue earlier because this was not a functional bug. I am also trying to figure out the problem.

**Comment by soumsps** [comment]
Solved this CSS bug.

Fix for Tally mode
`td.h1 {
    word-break: break-all;
}`

Fix for Fancy mode
`.s {
    word-break: break-all;
}`

Just try adding this code in CSS file.

Reason for bug: Sometimes we get a long referrer text like Yandex provides. In that case, 80% width of Right-hand column side is not followed by CSS as the referrer text is without space. Above CSS code will break those long text and then 80% width will be happily followed by any browser.

**Comment by Maikuolan** [comment]
Yep. ^.^

Also, got the fix working locally. :+1: 

I'll get it committed shortly.

**Comment by Maikuolan** [comment]
Done. :+1:
