### ISSUE TITLE
Please add frontend page to enable/disable SPAM Risk networks.

### ISSUE THREAD

**Issue by soumsps** [CIDRAM/CIDRAM#75]
As there are false positive in these blockings. So I feel there must be an easy way for the user to enable/disable blocking for individual networks from the frontend only.

**Comment by Maikuolan** [comment]
I'll see what I can do. :+1: 

For the moment, the best way to go about this would be to edit the `ignore.dat` file to list the names of the networks in question.

Locating `ignore.dat` via the front-end file manager:

![step1](https://user-images.githubusercontent.com/12571108/41808314-1633313e-770e-11e8-9484-e97dbb4307d3.png)

Listing the name of a network (replacing "NETWORK-NAME" with whatever the name of the actual relevant network is):

![step2](https://user-images.githubusercontent.com/12571108/41808317-190c69ac-770e-11e8-9cae-818edcc7c6dc.png)

I'll reply again though when I've had a chance to look at this a bit more closely.

**Comment by Maikuolan** [comment]
Working on this at the moment.

**Comment by Maikuolan** [comment]
I've repurposed the front-end "sections list" page as means of enabling users to ignore/unignore sections directly via the front-end. Makes more sense than creating a separate page I think, and most of the old information provided there before wasn't really used by anyone I think. Anyhow, when you get a chance, let me know what you think, whether there are any problems and so on. :-)

**Comment by Maikuolan** [comment]
*Marking as implemented and closing.*
