### ISSUE TITLE
Omit block page to bots

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM#83]
Since bots mostly don't have JS on, I think it would be nice to not spit out the block page data based on JS. If the user has JS they are presented with the block page, no JS, no block page. I don't foresee too many issues, and in fact if a user was blocked then there's a 99.9% chance he was up to no good. So the block page doesn't need to be presented to them with an E-mail address for rectification. I feel this will also save on data bandwidth, albeit small.  But if a user has lots of traffic it could add up.

**Comment by Maikuolan** [comment]
Still thinking a bit on the best way to approach this. Got a few ideas I could try out. Will reply again in the next day or so.

**Comment by 737simpilot** [comment]
Okay, thanks.

**Comment by Maikuolan** [comment]
I know I've been very delayed in replying here. Just been caught up with other things, and this had been put on the back-burner a bit.

Just to confirm: Is this suggestion and the suggestion made at #86 basically the same suggestion, or are there some differences in what is being suggested exactly between the two issues? If they're the same, I could close one of them as a duplicate, and just focus my replies at the other instead. Cheers.

**Comment by 737simpilot** [comment]
> "I know I've been very delayed in replying here. Just been caught up with other things, and this had been put on the back-burner a bit.
> 
> Just to confirm: Is this suggestion and the suggestion made at #86 basically the same suggestion, or are there some differences in what is being suggested exactly between the two issues? If they're the same, I could close one of them as a duplicate, and just focus my replies at the other instead. Cheers."

I did mention this in my other suggestion. Both ideas do overlap.  The JS block module may be a lot easier to implement.

**Comment by 737simpilot** [comment]
I can't seem to use the crapy quote in here.

**Comment by Maikuolan** [comment]
Cheers, and no worries. :+1: 

I'll close this issue in that case then in favour of the other issue (the two are related enough that we can probably just address it all there I think).
