### ISSUE TITLE
Combined logfile.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#88]
This issue extends out from the discussion at #70. Creating a new issue so that I can close the old issue (and because the old issue covered multiple, separate tasks).

*@mikeruss1:*
> merging the logs is a great idea, saves crossreferring

*@soumsps:*
> I also agree with this.

**Comment by 737simpilot** [comment]
Would this affect the way I have log files by date? I like them to be organized by date in my log files folder.

**Comment by Maikuolan** [comment]
> Would this affect the way I have log files by date? I like them to be organized by date in my log files folder.

Nope. This would just be introducing some new options for logging, for the benefit of those that like all their logs to be merged together, but wouldn't modify any existing options (backwards-compatibility and all that, plus I like organising things separately myself anyhow). Haven't yet started working on this yet though.

**Comment by 737simpilot** [comment]
Okay, thanks.

**Comment by Maikuolan** [comment]
@mikeruss1 @soumsps In regards to displaying reCAPTCHA entries in the main logfile: In doing this, would you guys also want a separate reCAPTCHA logfile as well, or would just having the one, singular combined logfile be sufficient? Asking because I'm looking into this now, and I'm considering two very different, alternative approaches to it. Cheers. :-)

**Comment by mikeruss1** [comment]
for me no separate logfile needed, suggest remove enabled I cant see that adds very much, and add passed or failed if reCaptcha is processed

**Comment by Maikuolan** [comment]
Made some small changes in with the latest commit so that an extra newline will now be added to the end of reCAPTCHA entries if CIDRAM detects that the name specified for the reCAPTCHA logfile is the same as the name specified for the standard block event logfile. So, it should now be possible to have a consistently formatted combined logfile, all without the need to add any new configuration directives, files, etc to CIDRAM. :-)

After updating, try changing the value of the reCAPTCHA logfile directive to match that of the standard block event logfile directive and let me know how it goes.

**Comment by mikeruss1** [comment]
works, neat - thank you !

**Comment by Maikuolan** [comment]
Excellent! And you're welcome. ^.^
