### ISSUE TITLE
Validator/Fixer BETA.

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/CIDRAM#9]
**https://github.com/Maikuolan/CIDRAM/commit/0feffa0967960eee4e47efeacca4ba0d9cdce8a3 - `Early stage validator/fixer BETA implemented as CLI functionality.`**

---

Not yet documented and still a work-in-progress; I've tested my code prior to committing and it seemed to all work correctly for my tests, but it should nonetheless be regarded as "unstable", due to being an early work-in-progress and neither documented nor yet tested by others.

Both a "validator" and a "fixer" for signature files is available as of this commit; However, this commit offers only a CLI-mode implementation for the validator/fixer (alternative arrangements aren't yet available, but will be later).

Current usage for the validator is:
- `/path/to/php.exe /path/to/cidram/loader.php -v SignatureFile.dat`

![v](https://cloud.githubusercontent.com/assets/12571108/14247238/5e76baa8-fa9f-11e5-9464-ac1bdf8bdc27.png)

Current usage for the fixer is:
- `/path/to/php.exe /path/to/cidram/loader.php -f SignatureFile.dat`

![f](https://cloud.githubusercontent.com/assets/12571108/14247251/77fb66fe-fa9f-11e5-881a-34d99e819bbb.png)

Usage assumes that the signature file to be validated/fixed is located as `/path/to/cidram/vault/SignatureFile.dat`.

The "validator" will check the specified signature file against a set of rules and will issue a notice, a warning, an error, or a fatal error (depending on the nature of the rule) whenever a rule fails to be met or whenever the condition associated with a rule is met.

The "fixer" operates on the same set of rules as the validator, but rather than issuing notices, warnings and errors, the fixer will attempt to automatically correct the problem, saving the corrected signature file as `/path/to/cidram/vault/SignatureFile.dat.fixed`.

For the purposes of providing an example of the validator at work, if we parse a signature file through it that looks like this:

```
# A hashed comment.
An unhashed comment.

# Some good signatures.
1.2.3.4/32 Deny Generic
2001::1/128 Deny Generic
127.0.0.1/32 Deny Bogon
10.0.0.0/8 Deny Bogon
Tag: Foobar1

# Some crappy broken signatures.
# (#1 is not a valid CIDR, #2 doesn't start at the beginning of its range, and #3/#4 are "accidentally" duplicated).
666.777.888.999/32 Deny Generic
127.0.0.1/31 Deny Bogon
10.0.0.0/8 Deny Bogon
10.0.0.0/8 Deny Bogon
Tag: Foobar2

# This  comment has a   bunch   of  annoying    tabs
# This comment has excess trailing whitespace                

# EoF
```

The validator will show us this:

![vtest](https://cloud.githubusercontent.com/assets/12571108/14247429/b9618afa-faa0-11e5-81b7-577029bbbf24.png)

If we parse that same signature file through the fixer, it will create a new file, `SignatureFile.dat.fixed`, that looks like this:

```
# A hashed comment.
# An unhashed comment.

# Some good signatures.
1.2.3.4/32 Deny Generic
2001::1/128 Deny Generic
127.0.0.1/32 Deny Bogon
10.0.0.0/8 Deny Bogon
Tag: Foobar1

# Some crappy broken signatures.
# (#1 is not a valid CIDR, #2 doesn't start at the beginning of its range, and #3/#4 are "accidentally" duplicated).
#666.777.888.999/32 Deny Generic
127.0.0.0/31 Deny Bogon
Tag: Foobar2

# This    comment    has    a    bunch    of    annoying    tabs
# This comment has excess trailing whitespace

# EoF
```

**Comment by DanielRuf** [comment]
L1 is the second line in the file, L7 the eigth line and so on, is this correct?

**Comment by Maikuolan** [comment]
Yep, correct. :+1:

**Comment by Maikuolan** [comment]
**"Error" (or message) levels.**
_BETA / Work-In-Progress / Subject to change at any time._
- **Notice:** Informative, but not really an error or a problem; Least severe. When concerning a specific line (as opposed to concerning the progress of the validator/fixer), can be fixable, but isn't necessary to fix.
- **Warning:** Not necessarily a problem, but _could_ be a problem. Not severe, but recommended to be fixed.
- **Error:** Definitely a problem, but not critical, severe, fatal, etc. This won't harm CIDRAM or anything else, but could potentially result in failure to block undesirable requests.
- **Fatal Error:** A problem that prevents the validator/fixer from completing its task (such as, for example, if asked to validate/fix a non-existent or zero-byte signature file), or a problem that could severely hinder CIDRAM from functioning as intended; Highest severity (an error can be considered "fatal" if it prevents a related task from being completed). The fixer should _NOT_ attempt to correct fatal errors by itself (these should be addressed manually by the user).

---

**Current validator ruleset (displayed in the order of processing).**
_This list is purely a reflection of the codebase as it currently stands, and doesn't necessarily reflect the final form that the ruleset is intended to take._
_More rules are planned to be added; This list will be modified accordingly as they are implemented._
_BETA / Work-In-Progress / Subject to change at any time._
- Notify the user when the validator/fixer begins (Notice).
- Supplied signatures file should exist and shouldn't be empty (Fatal Error).
- Warn the user if the signatures file isn't normalised to LF linebreaks (Warning).
- Warn the user if the signatures file doesn't terminate with an LF linebreak (Warning).
- Notify the user when the validator progresses from overall file checks to line-by-line checks (Notice).
- Warn the user about possible readability problems if the line length exceeds 120 bytes (Warning).
- Empty lines should not be processed by the following rules (skip to the next line and return to the first rule if the line is empty).
- Notify the user that lines can be merged if the line being currently analysed is identical to the succeeding line (Notice).
- Warn the user if/when excess trailing whitespace is detected (Warning).
- Hashed comments shouldn't be processed by the following rules (skip to the next line and return to the first rule if the line is a hashed comment).
- Warn the user if/when tabs are detected (Warning).
- Warn the user if/when any control characters are detected within the line being analysed; Skip this rule if tabs were detected (Warning).
- Warn the user about readability if/when any section tags exceed 20 bytes in length (Warning).
- Warn the user if/when any expiry tags don't contain a valid ISO 8601 date/time (Error).
- Warn the user that the line being analysed isn't syntactically precise if we're not sure what the line is for, eg, whether it's supposed to be comment, a signature, a tag, etc (Warning).
- Warn the user if/when the line seems to contain something resembling an IP address, but which isn't a valid IPv4 or IPv6 address (Error).
- Warn the user if/when we detect any signatures that don't possess an accompanying `%Function%` (Deny, Whitelist, Run, etc) on the line (Error).
- Warn the user if/when we detect any unrecognised `%Function%` value on the line (Error).
- Warn the user if/when we detect any duplicated signatures (Warning).
- Warn the user if/when the signature on the line being analysed is non-triggerable (Error).
- Warn the user if/when the signature on the line being analysed is subordinate to an already existing signature elsewhere (Warning).
- Warn the user if/when the signature on the line being analysed is a superset to an already existing signature elsewhere (Warning).

**Current fixer ruleset (displayed in the order of processing).**
_This list is purely a reflection of the codebase as it currently stands, and doesn't necessarily reflect the final form that the ruleset is intended to take._
_More rules are planned to be added; This list will be modified accordingly as they are implemented._
_BETA / Work-In-Progress / Subject to change at any time._
- Notify the user when the validator/fixer begins (Notice).
- Supplied signatures file should exist and shouldn't be empty (Fatal Error).
- Check if the signatures file is normalised to LF linebreaks; If it isn't, attempt to normalise it.
- If tabs are detected, convert them to four spaces each.
- If control characters are detected within the signature file, remove them.
- Check if the signatures file terminates with an LF linebreak; If it doesn't, add a terminating LF when fixing.
- Notify the user when the validator/fixer progresses from overall file checks to line-by-line checks (Notice).
- Empty lines should not be processed by the following rules (skip to the next line and return to the first rule if the line is empty).
- If the line being currently analysed is identical to the succeeding line, drop one of them from the signatures file.
- If excess trailing whitespace is detected, remove it.
- Hashed comments, section tags and expiry tags shouldn't be processed by the following rules (skip to the next line and return to the first rule if the line is a hashed comment).
- If we're not sure what it is, if it resembles a signature but isn't valid, or if it resembles a comment, and if it isn't hashed, hash it.
- If we fail to validate a CIDR, hash it.
- If the signature is valid and triggerable, check for duplicates; If duplicates are found, drop all instances of the signature other than the first instance (currently works for "Deny" and "Whitelist" signatures; "Run" signatures are currently ignored by this rule).
- If the signature on the line being analysed is non-triggerable, attempt to repair it.
- Check the signatures file being analysed for signatures that are subordinate to the signature on the line being analysed; If any are found, remove them. Currently, "Deny" and "Whitelist" are supported, but "Run" is ignored by this rule.
- Check the signatures file being analysed for signatures that are supersets to the signature on the line being analysed; If any are found, remove the signature on the line being analysed. Currently, "Deny" and "Whitelist" are supported, but "Run" is ignored by this rule.

**Fixer wishlist (not yet implemented; would like to eventually implement).**
_BETA / Work-In-Progress / Subject to change at any time._
- Aggregate the CIDRs within any section being analysed whenever possible (same function, same param, mergeable ranges, etc).
- Modify subordinate/superset rules to allow analysing of "Run" signatures (not safe to do this yet).

**Comment by Maikuolan** [comment]
Removed _Work-In-Progress_ label and added _Testing_ label.

I haven't had time to thoroughly test everything yet (mostly everything has been tested, and so far, there hasn't been any problems, but there are some certain small things that still need testing), but I'll do this a little later today (shouldn't take too long to do this, either); If all goes well, **v0.2.0** should be released very soon. There's still some more i18n work to be done, but that shouldn't take too long (not too much left to do of that for **v0.2.0**, at least).

Validator/Fixer still only has a CLI implementation, but I'm thinking I'll start working on a non-CLI implementation a little later, after **v0.2.0** has been released (because many changes have been made now, and the release of **v0.2.0** probably shouldn't be delayed for too much longer if it can be avoided).

**Comment by Maikuolan** [comment]
Testing complete. :+1:
