### ISSUE TITLE
Incompatibility with RunCloud's Hybrid stack 

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#90]
After been a [ServerPilot](https://serverpilot.io/) user for more than 2 years, I was started migrating to [RunCloud](https://runcloud.io/) with my new dedicated server. The first thing I needed to install CIDRAM, so I archived my current CIDRAM directory & extracted it new stack.

RunCloud offers 2 stack.

1. Native Nginx
2. Hybrid - Ngnix + Apache (reverse proxy)

So, I picked Hybrid since I do rely on .htaccess. But the problem was the "loader.php" wasn't loading. I tried many things like changing PHP versions, I even tried to install a new CIDRAM instances. But no matter what I did, the loader.php wasnt loading, neither it was producing any errors.

Then, I changed the stack from Hybrid to **Native Ngnix and it started to working perfectly fine**.

ServerPilot uses the same technique RunCloud does (nginx as reverse proxy in front of apache), But I don't understand why it was not working with RunCloud Hybrid stack. There might some internal difference of both companies how they configured the stacks.

**Comment by Maikuolan** [comment]
Are any error messages or `error_log` files produced at all?

**Comment by harryqt** [comment]
Nope. That's the weird part. I checked many times. There is no errors at all (nginx, apache, fpm) nothing.. no errors.

There is nothing wrong with using native nginx, but I thought you should know about it.

**Comment by Maikuolan** [comment]
Cheers for the heads up. :+1: 

Would be good to get to the bottom of it, but that'll be difficult without any error logs or such produced. :-/

I think, if we wanted to pursue this further, we would need to find more information about exactly what the differences are between their two stack options, whether maybe configuration needs to be different at all (like maybe different `ipaddr` values due to the reverse proxy), whether maybe they're using customised PHP builds, whether error reporting has been forcibly disabled at their end, things like that.

**Comment by Maikuolan** [comment]
Are any error logs produced? If so, does it show a line number or any debug information?

**Comment by Dibbyo456** [comment]
I'm digging into it..

**Comment by harryqt** [comment]
Does CIDRAM store any error logs in itself?

**Comment by Maikuolan** [comment]
Not in itself, but Apache should usually generate an `error_log` file or similar in the base directory of the file causing the error. Could be something there. Nginx usually logs errors into a `error.log` file in a dedicated `logs` directory in the Nginx base directory. (Of course, this can all be changed and customised by the host, so whether this actually applies in this case, would depend on however they've configured their servers).
