### ISSUE TITLE
Does CIDRAM cache front-end client information?

### ISSUE THREAD

**Issue by harryqt** [CIDRAM/CIDRAM#92]
Does CIDRAM cache frontend client information?

Because my current IP is different from what shown in the front-end of CIDRAM.
I tried re-logging but result is the same.

**Comment by Maikuolan** [comment]
> Does CIDRAM cache frontend client information?

Nope. Anything cached can be found on "Cache Data" page (and deleted from there, when necessary).

Could be a configuration problem maybe?

**Comment by harryqt** [comment]
> Nope. Anything cached can be found on "Cache Data" page (and deleted from there, when necessary).

IP Shown in front-end (RunCloud Instance): https://s.put.re/4BtGBZ3.png
My actual **current IP**: https://s.put.re/UAQJSeN.png

I have 2 cidram instance, what irony is that, the other instance shows **another IP**..!!!
ServerPilot Instance: https://s.put.re/6qz3pKL.png 

Hell of a bug...! :flushed:

> Could be a configuration problem maybe?

I don't think so. My ISP (broadband) gives me dynamic public IPs.. Look at those IPs, they're from same CIDR. I would say this is **definitely** cache or cache related issue.

**Comment by ghost** [comment]
Any general server side page cache in action?

@Dibbyo456 Unnecessary question probably, but you are only logged into one instance of CIDRAM at a time, and log out of it when you are done?

**Comment by harryqt** [comment]
Both logged in same time. They're both in different servers.

**Comment by ghost** [comment]
What if you try with logging out all over, then only log into one at a time?

I'm suggesting it because I have seen some unexpected results when I have been logged in on both my production server and my work server. They do share domain though, so I would guess that is why.

**Comment by harryqt** [comment]
> I'm suggesting it because I have seen some unexpected results when I have been logged in on both my production server and my work server. They do share domain though, so I would guess that is why.

Here's what I did. First I logged out from both instances. (both instances are in different servers). Then I cleared my Chrome cache & cookies too.

Then, I logged into my first instance, IP showed: `114.29.227.2`
Then, I logged into my second instance, IP showed: `114.29.227.64`

But my **actual current public IP address** is: `114.29.227.34` :fearful:

FYI, I have been noticing this bug from many months ago, but I always ignored it due to laziness.

**Comment by dev-101** [comment]
Does your IP change frequently? Any chance you are behind NAT? This can make sense, since you are in the same network 114.29.227.* but it may change every few minutes or so, depending on the concurrent load.

**Comment by harryqt** [comment]
> Does your IP change frequently?

Yes. It does.

> Any chance you are behind NAT?

No. I'm NOT behind NAT. (I'm not sure though)

------

But, even all the things are true, isn't CIDRAM supposed to show my current public facing IP ?

**Comment by dev-101** [comment]
How frequently does it change? And how can you be sure? Did you call your ISP to verify it?

**Comment by dev-101** [comment]
One way (or first step) to debug this is to test what your server "see" when you access it.

For example, in PHP you can create a small file called test.php (or similar) in the root of your site, then go to **yoursite . com/test.php** and check all the reported fields, hopefully, one of them will be your *real* (current) IP (usually this is REMOTE_ADDR value):

`<?php echo '<pre>';print_r($_SERVER);echo '</pre>'; ?>`

Refresh page couple of times, in different intervals, and see if things change regarding your IP.

**Comment by harryqt** [comment]
> hopefully, one of them will be your real (current) IP (usually this is REMOTE_ADDR value)

    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => ################
    [SERVER_PORT] => 80
    [SERVER_ADDR] => ################
    [REMOTE_PORT] => 60494
    [REMOTE_ADDR] => 114.29.227.64
    [SERVER_SOFTWARE] => nginx/1.15.1
    [GATEWAY_INTERFACE] => CGI/1.1
    [REQUEST_SCHEME] => http
    [SERVER_PROTOCOL] => HTTP/1.1
    [DOCUMENT_URI] => /info.php
    [REQUEST_URI] => /info.php
    [SCRIPT_NAME] => /info.php

**Comment by dev-101** [comment]
Now, does it match with e.g. when you google "my ip" and what CIDRAM reports?

**Comment by harryqt** [comment]
**Update**: The server where I ran the PHP code, of that CIDRAM instance, now showing correct IP. But the other instance still showing old/incorrect IP.

> google "my ip" and what CIDRAM reports?

<del>Indeed. Why would not it?</del>

NOPE. It does not. Google saying `114.29.227.108` where REMOTE_ADDR showing `114.29.227.64`

**Comment by dev-101** [comment]
It shouldn't under "normal" (e.g. static IP) circumstance. However, if your IP changes frequently, without you being aware of it, naturally, then you might see discrepancies in reports. Keep monitoring.

**Comment by harryqt** [comment]
@dev-101 I have updated my reply.

**Comment by dev-101** [comment]
> NOPE. It does not. Google saying 114.29.227.108

I am now convinced that you are behind NAT. Make a call to your ISP to verify this ;)

**Comment by harryqt** [comment]
Okay.. Is this BAD ? What's the solution ?

**Comment by dev-101** [comment]
There is none. I'm behind NAT, too and had same mystery to solve :) :(

IPv4 pool is exhausted, and only way to get static IP (v4) in most cases is to call your ISP and activate that option, for extra cost, of course. Alternative is static IPv6, but it is not yet widespread everywhere for various reasons, which, again, depends on your ISP.

**Comment by harryqt** [comment]
> There is none. I'm behind NAT, too and had same mystery to solve :) :(

:satisfied::satisfied::satisfied::satisfied:

They would not allow such thing, it's a take it or leave it package.. They're the best where I live, so I'm stuck with it. :disappointed:

**Comment by dev-101** [comment]
Again, just make a call to their tech support, to be sure.
But, if your IP "floats" around ~ same network range, it must be that.

**Comment by ghost** [comment]
It does sound a bit like a ISP carrier grade NAT used as load balancer. 

Carrier grade NAT's should not change that often as it can induce issues with other sites. We have them for mobile networks here, and they rotate on a daily scheme mostly.

From a user perspective being behind one only impacts if you run servers that must be reached from the outside on your connection. Still, give tech support a call. Some ISP's are happy to change to static IP's for those who asks and lets those who don't ask use "the pool".

One way to make sure if you are NAT'ed or not would be to check the IP your own firewall has on the outside (WAN) and compare that with what Google or your server reports.

**Comment by Maikuolan** [comment]
*Marking as "resolved" and closing.*
